force-app/main/default/objects/Case/fields/Awaiting_user__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_user__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set automatically whenever an email is received related to the case. The flag can also be set manually by the user. Flag is used to make it possible to show an image on listviews, in order for the case to stick out.</description>
    <label>Awaiting user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Activation_Check_Result__c.field-meta.xml
<CustomField>
    <fullName>Case_Activation_Check_Result__c</fullName>
    <label>Activation Check Result</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Activation_Check_Time__c.field-meta.xml
<CustomField>
    <fullName>Case_Activation_Check_Time__c</fullName>
    <label>Activation Check Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Customer_Service_Case.recordType-meta.xml
<RecordType>
    <fullName>Customer_Service_Case</fullName>
    <active>true</active>
    <businessProcess>Customer Service Process</businessProcess>
    <description>CS. Used for customer requests regarding service and support</description>
    <label>Customer Service Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Order_Fulfilment_Case.recordType-meta.xml
<RecordType>
    <fullName>Order_Fulfilment_Case</fullName>
    <active>true</active>
    <businessProcess>Order Fulfilment Process</businessProcess>
    <description>A case that is an order fulfilment, e.g. for activating a mobile or data product.</description>
    <label>Order Fulfilment Case</label>
</RecordType>

force-app/main/default/objects/Case_Status_Change__c/Case_Status_Change__c.object-meta.xml
<CustomObject>
    <label>Case Status Change</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Status Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Status_Change__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Status Changes</relationshipLabel>
    <relationshipName>Case_Status_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Status_Change__c/fields/Change_Time__c.field-meta.xml
<CustomField>
    <fullName>Change_Time__c</fullName>
    <label>Status End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Status_Change__c/fields/Set_Time__c.field-meta.xml
<CustomField>
    <fullName>Set_Time__c</fullName>
    <label>Status Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CaseSelector.cls
public with sharing class CaseSelector {

    public Id getCaseTeamRoleIdByName( String name ){
        Id teamRoleId = null;

        List<CaseTeamRole> teamRoles = [SELECT Id FROM CaseTeamRole WHERE Name = :name ];

        if(!teamRoles.isEmpty() && teamRoles.size() == 1){
            teamRoleId = teamRoles.get(0).Id;
        }

        return teamRoleId;
    }

    public List<Case_Status_Change__c> getCurrentCaseChangeStatus(Set<Id> cases){
        return [
			SELECT Id, Name, Set_Time__c, Case__c, Change_Time__c
			FROM Case_Status_Change__c
			WHERE Case__c IN :cases AND Change_Time__c = NULL
		];
    }

    public static Case getById(String id) {
        return [
            SELECT Id, Case_Activation_Check_Result__c, Case_Activation_Check_Time__c, CaseNumber
            FROM Case
            WHERE Id = :id
            LIMIT 1
        ];
    }
    
    public static List<Case> getOrderFulfilmentCasesByAccountId(String accountId){
        return [
            SELECT Id FROM Case WHERE Status = 'Gather information'
              AND RecordType.DeveloperName = 'Order_Fulfilment_Case'
              AND AccountId = :accountId
          ];
    }
    
    //Only used by LWC topEncryptionKey - can probably be deleted
    @AuraEnabled(Cacheable=true)
    public static String getByCurrentUser() {
        String userId = UserInfo.getUserId();
        User currentUser = [
            SELECT Id, ContactId
            FROM User
            WHERE Id = :userId
            LIMIT 1
        ];

        Contact currentContact = [
            SELECT Id
            FROM Contact
            WHERE Id = :currentUser.ContactId
            LIMIT 1
        ];

        // Retrieve the current user's Account Id
        Id userAccountId = [
            SELECT AccountId
            FROM Contact
            WHERE Id = :currentContact.Id
        ].AccountId;
        
        // Query for the Case related to the Account and meets the specified criteria
        List<Case> theCase = [
            SELECT Id, Subject, Status, RecordType.DeveloperName
            FROM Case
            WHERE AccountId = :userAccountId
                AND Status = 'Gather Information'
                AND RecordType.DeveloperName = 'Order_Fulfilment_Case'
        ];

        if(theCase.size() > 0) {
            return theCase.get(0).Id;
        }
        
        return null;
    }

    public static List<Case> getCasesByOpportunityIds(Set<Id> opportunityIds) {
        return [
            SELECT Type, Opportunity__c
            FROM Case
            WHERE Opportunity__c IN :opportunityIds
            WITH SECURITY_ENFORCED
        ];
    }

    public List<Case> getCustomerServiceCasesByIds(List<Id> caseIds) {
        return [
            SELECT Id, RecordTypeId, Awaiting_user__c
            FROM Case
            WHERE Id IN :caseIds
                AND RecordTypeId = :Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName().get('Customer_Service_Case').getRecordTypeId()
        ];
    }
}