force-app/main/default/objects/EventExecutor__e/EventExecutor__e.object-meta.xml
<CustomObject>
    <label>EventExecutor</label>
    <pluralLabel>EventExecutors</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventExecutor__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>A JSON string that contains parameters that is used in the execute functions</description>
    <inlineHelpText>A JSON string that contains parameters that is used in the execute functions</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventExecutorExampleImpl.cls
public with sharing class EventExecutorExampleImpl implements IEventExecutableHandler {
    private final DAWAClient dawaClient;

    @TestVisible
    private EventExecutorExampleImpl(DAWAClient dawaClient) {
        this.dawaClient = dawaClient;
    }

    public EventExecutorExampleImpl() {
        this(SingletonFactory.getFactory());
    }

    private EventExecutorExampleImpl(SingletonFactory singletonFactory) {
        this.dawaClient = (DAWAClient) singletonFactory.getOrRegisterSingleton(DAWAClient.class);
    }

    /**
     * @description Parses the provided JSON Parameters into EventExecutorExampleImpl.parameter
     */
    public Parameters parseParameters(String parameters) {
        Logger.logInfo(String.format('parseParameters( {0} )', new List<Object>{ parameters }));

        if (parameters == null) {
            return null;
        }

        return (Parameters) System.JSON.deserialize(parameters, Parameters.class);
    }

    public void execute(EventExecutor__e event) {
        Logger.logInfo(String.format('execute( {0} )', new List<Object>{ event }));

        Parameters params = parseParameters(event.Parameters__c);

        switch on params?.action {
            when 'SUCCESS' {
                //Unit test:
                //EventExecutorServiceTest.publishEventExecutor_withSUCCESSActionProperty_createTaskInQueueableAndUpdateInFinalizer
                //uses this task to verify that the EventExecutor "chain" works.
                if (Test.isRunningTest()) {
                    insert new Task(Subject = 'EventExecutorServiceTest');
                }
                return;
            }
            when 'EXCEPTION' {
                String s;
                s.charat(5); //throws a nullpointer
            }
            when 'RETRY' {
                throw new EventExecutorRetryException('We are going to retry');
            }
            when 'CALLOUT' {
                //THIS SHOULD BE IN A SERVICE CLASS AND NOT BE CALLED DIRECTLY FROM THIS STUFF!
                DAWAClient.DAWADataVaskDTO dataFromServiceCall = dawaClient.addresseVask(params.address);
            }
        }
    }

    public class Parameters {
        public String action;
        public String address;
    }
}