force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogging_Test.cls
@IsTest
private class ErrorLogging_Test {
	@IsTest
    private static void addingToListAndControlersInsertAtTheEnd(){
        String testErrorText = 'Test Error Text Lorem Ipsum Parolem', testAddInfo = 'Error happened in some class', startOriginName = 'Apex', switchOriginName = 'Flow', defoultOrigin = 'Not defined';
        ErrorLogging withOriginSetUp = new ErrorLogging( startOriginName ), WithOutOriginSetUp = new ErrorLogging();
        
        withOriginSetUp.addError( testErrorText, testAddInfo );
        withOriginSetUp.addError( testErrorText, testAddInfo, switchOriginName );
        
        WithOutOriginSetUp.addError( testErrorText, testAddInfo );
        WithOutOriginSetUp.addError( testErrorText, testAddInfo, switchOriginName );
        
        System.assertEquals( 2, withOriginSetUp.listOfLogs.size(), 'Number of record for set up origin is wrong.');
        System.assertEquals( 2, WithOutOriginSetUp.listOfLogs.size(), 'Number of record for not set up origin is wrong.');
        
        for( System_Log__c singleLog : withOriginSetUp.listOfLogs ){
            System.assertEquals( testErrorText, singleLog.Error_Body__c, 'The error text body is incorect.');
            if( singleLog.Origin__c != startOriginName ) System.assertEquals( switchOriginName, singleLog.Origin__c, 'The origin should be Flow.');
            else System.assertEquals( startOriginName, singleLog.Origin__c, 'The origin should be Apex.');
        }        
        for( System_Log__c singleLog : WithOutOriginSetUp.listOfLogs ){
            System.assertEquals( testErrorText, singleLog.Error_Body__c, 'The error text body is incorect.');
            if( singleLog.Origin__c != defoultOrigin ) System.assertEquals( switchOriginName, singleLog.Origin__c, 'The origin should be Flow.');
            else System.assertEquals( defoultOrigin, singleLog.Origin__c, 'The origin should be "Not defined".');
        }
        
        withOriginSetUp.logErrors();
        WithOutOriginSetUp.logErrors();
        
        List<System_Log__c> theLogs = [SELECT Id FROM System_Log__c];
        System.assertEquals( 4, theLogs.size(), 'Number of inserted logs is not correct');
    }
}