force-app/main/default/objects/Fokus_Campaign__c/Fokus_Campaign__c.object-meta.xml
<CustomObject>
    <description>Requested by Telia IT. Used for Fokus data sync</description>
    <label>Fokus Campaign</label>
    <nameField>
        <displayFormat>Cam-{00000}</displayFormat>
        <label>Fokus Campaign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fokus Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fokus_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Campaign Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fokus_Campaign__c/fields/Campaign_Value__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Value__c</fullName>
    <label>Campaign Value</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Campaign__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignSelector.cls
public with sharing class CampaignSelector {
	private static final String ERROR_ORIGIN = 'Apex';
	private static final String ERROR_ADDITIONAL_INFO = 'CampaignSelector';

	private static ErrorLogging errorLogging = new ErrorLogging(ERROR_ORIGIN);

	@auraenabled(cacheable=true)
	public static Fokus_Campaign__c getCampaignByProductId(String productId) {
		Fokus_Campaign__c[] campaigns = [
			SELECT Id, Campaign_Id__c, Campaign_Value__c, Product_Id__c
			FROM Fokus_Campaign__c
			WHERE Product_Id__c = :productId
		];

		if (campaigns.size() > 0) {
			return campaigns.get(0);
		}
		return null;
	}

	public static Map<String, Fokus_Campaign__c> getCampaignsByProductIds(List<String> productIds) {
		Map<String, Fokus_Campaign__c> campaingsByProductIds = new Map<String, Fokus_Campaign__c>();
		List<Fokus_Campaign__c> campaigns = [
			SELECT Id, Campaign_Id__c, Campaign_Value__c, Product_Id__c
			FROM Fokus_Campaign__c
			WHERE Product_Id__c IN :productIds
		];

		for(Fokus_Campaign__c campaign: campaigns) {
			campaingsByProductIds.put(campaign.Product_Id__c, campaign);
		}
		return campaingsByProductIds;
	}
}