force-app/main/default/objects/Fokus_Campaign__c/Fokus_Campaign__c.object-meta.xml
<CustomObject>
    <description>Requested by Telia IT. Used for Fokus data sync</description>
    <label>Fokus Campaign</label>
    <nameField>
        <displayFormat>Cam-{00000}</displayFormat>
        <label>Fokus Campaign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fokus Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fokus_Campaign__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Campaign Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fokus_Campaign__c/fields/Campaign_Value__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Value__c</fullName>
    <label>Campaign Value</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Campaign__c/fields/Product_Campaign_Composite_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Campaign_Composite_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Should contain the composition of product id and campaign id separated with a dot (&quot;.&quot;). E.g. &quot;GPMBBS.GPMBBS12&quot; if the priceplan = GPMBBS and discount = GPMBBS12.</description>
    <externalId>true</externalId>
    <label>Product.Campaign Composite Key</label>
    <length>99</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fokus_Campaign__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignSelectorTest.cls
/**
 * 
 * @author 
 * @since 
 */
@IsTest
public with sharing class CampaignSelectorTest {
	
	/**
	 * makeData
	 */
	@TestSetup
	static void makeData() {
		List<Fokus_Campaign__c> campaigns = new List<Fokus_Campaign__c>();
		Fokus_Campaign__c campaign1 = new Fokus_Campaign__c(
			Campaign_Id__c = 'FI06HOF03',
			Campaign_Value__c = 0,
			Product_Id__c = 'FIBHOF03',
			Product_Campaign_Composite_Key__c = 'FIBHOF03.FI06HOF03'
		);
		campaigns.add(campaign1);

		Fokus_Campaign__c campaign2 = new Fokus_Campaign__c(
			Campaign_Id__c = 'FI06HOF02',
			Campaign_Value__c = 0,
			Product_Id__c = 'FIBHOF02',
			Product_Campaign_Composite_Key__c = 'FIBHOF02.FI06HOF02'
		);
		campaigns.add(campaign2);
		insert campaigns;
	}

	/**
	 * getCampaignByProductId_invalidCampaignId_returnsNull
	 */
	@IsTest
	static void getCampaignByProductId_invalidCampaignId_returnsNull() {
		//ARRANGE
				
		//ACT
		Test.startTest();
		Fokus_Campaign__c noCampaign = CampaignSelector.getCampaignByProductId('Test');
		Test.stopTest();

		//ASSERT
		Assert.isNull(noCampaign);
	}

	/**
	 * getCampaignByProductId_validCampaignId_returnsCampaign
	 */
	@IsTest
	static void getCampaignByProductId_validCampaignId_returnsCampaign() {
		//ARRANGE
		
		//ACT
		Test.startTest();
		Fokus_Campaign__c hasCampaign = CampaignSelector.getCampaignByProductId('FIBHOF03');
		Test.stopTest();

		//ASSERT
		Assert.isNotNull(hasCampaign);
	}

	/**
	 * getCampaignsByProductIds_validIds_returnsMapOfCampaigns
	 */
	@IsTest
	static void getCampaignsByProductIds_validIds_returnsMapOfCampaigns() {
		//ARRANGE
		List<String> productIds = new List<String>{ 'FIBHOF03', 'FIBHOF02' };

		//ACT
		Test.startTest();
		Map<String, Fokus_Campaign__c> campaigns = CampaignSelector.getCampaignsByProductIds(productIds);
		Test.stopTest();

		//ASSERT
		Assert.isTrue(campaigns.size() > 0);
	}
}