force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identify the different activation parts in a Renewal process since existing subcription renewal process will be different than the upsell subscriptions</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renew Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>Company name</inlineHelpText>
    <label>Company Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <label>Delivery City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Delivery_Country__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Country__c</fullName>
    <defaultValue>&apos;Danmark&apos;</defaultValue>
    <inlineHelpText>Always defaults to Danmark - however can be changed</inlineHelpText>
    <label>Delivery Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Delivery_Street_and_number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Street_and_number__c</fullName>
    <inlineHelpText>Enter name of street, number and any other indication on floor etc</inlineHelpText>
    <label>Delivery Street and number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <inlineHelpText>Enter the 4 digit postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_UC_License__c.field-meta.xml
<CustomField>
    <fullName>VAS_UC_License__c</fullName>
    <inlineHelpText>Add the UC license relevant for the specific user if part of quote</inlineHelpText>
    <label>UC License</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UC_License</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>These field has been created to hold 255 signs of additional information that might be useful in problem solving of this error.</description>
    <inlineHelpText>Additional helpful information like name of class/flow ect.</inlineHelpText>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Activation_line_Create_Iterable.cls
public class Activation_line_Create_Iterable implements Database.Batchable<sObject> {
	public String query;
	public String recordId;
	public Database.querylocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext bc, List<SBQQ__QuoteLine__c> scope) {
		List<Activation_line__c> activationLineCreateList = new List<Activation_line__c>();
		Activation_line__c activationLineRecord = new Activation_line__c();
		List<SBQQ__QuoteLine__c> updateQuoteLinewithActivated = new List<SBQQ__QuoteLine__c>();

		try {
						
			Map<String, Id> activationIdsPerRecordType = new Map<String, Id>();
			Map<String, Id> caseIdByActivationRecordType = new Map<String, Id>();

			for (Activation__c ac : [SELECT Id, RecordType.name, Type__c, Case__c FROM Activation__c WHERE Case__r.Quote__c = :recordId]) {
				activationIdsPerRecordType.put(ac.RecordType.name.remove(' activation') + '-' + ac.Type__c, ac.Id);
				caseIdByActivationRecordType.put(ac.RecordType.name.remove(' activation') + '-' + ac.Type__c, ac.Case__c);
			}

			for (SBQQ__QuoteLine__c s : scope) {
				for (Integer i = 1; i <= s.SBQQ__Quantity__c; i++) {							
					activationLineRecord = new Activation_line__c(
						Activation__c = activationIdsPerRecordType.get(s.Activation_Record_Type__c + '-New'),
						Case__c = caseIdByActivationRecordType.get(s.Activation_Record_Type__c + '-New'),
						Quote_line__c = s.Id,
						RecordTypeId = Schema.sObjectType.Activation_line__c.getRecordTypeInfosByName()
							.get(s.Activation_Record_Type__c + ' activation line')
							.getRecordTypeId(),
						Delivery_City__c = s.SBQQ__Quote__r.SBQQ__BillingCity__c,
						Delivery_Country__c = s.SBQQ__Quote__r.SBQQ__BillingCountry__c,
						Delivery_Street_and_number__c = s.SBQQ__Quote__r.SBQQ__BillingStreet__c,
						Postal_Code__c = s.SBQQ__Quote__r.SBQQ__BillingPostalCode__c,
						Manual_Product__c = s.SBQQ__Product__c,
						Company_Name__c = s.SBQQ__Quote__r.Account_Name__c
					);

					if (s.SBQQ__ProductCode__c == '11105') { //	TPX Corporate Fri Tale 
						activationLineRecord.VAS_UC_License__c = 'TPXSOFTP';
					}

					if (s.SBQQ__ProductCode__c == '26000') { //	DN Access 4G Backup - DK
						activationLineRecord.Case__c = caseIdByActivationRecordType.get('Fiber' + '-New');
					}

					activationLineCreateList.add(activationLineRecord);
				}
				
				updateQuoteLinewithActivated.add(new SBQQ__QuoteLine__c(Id = s.Id, Activation_Created__c = true));
			}
			
			insert activationLineCreateList;
			update updateQuoteLinewithActivated;

		} catch (Exception e) {
			System.debug('### Error Occured while creating activation lines : ' + e.getMessage());
			System_Log__c logerror = new System_Log__c(
				Origin__c = 'Apex',
				Error_Body__c = e.getMessage() + ' LineNumber: ' + e.getLineNumber(),
				Additional_Information__c = 'Activation_line_Create_Iterable'
			);
			insert logerror;
		}
	}

	public void finish(Database.BatchableContext bc) {
		List<Id> records = new List<Id>();
		list<SBQQ__Quote__c> quoteList = [
			SELECT Id, SBQQ__Opportunity2__r.SBQQ__Renewal__c, SBQQ__Opportunity2__r.SBQQ__AmendedContract__c
			FROM SBQQ__Quote__c
			WHERE Id = :recordId
		];
		//Find out if the quote is renewal
		if (quoteList[0].SBQQ__Opportunity2__r.SBQQ__Renewal__c == true) {
			records.add(recordId);
			Activation_line_CreateRenewal.Activation_line_Create(records);
		}

		//Find out if the quote is amendment
		if (quoteList[0].SBQQ__Opportunity2__r.SBQQ__AmendedContract__c != null) {
			records.add(recordId);
			Activation_lineCreateAmendment.Activation_line_Create(records);
		}
	}
}