force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <label>Delivery City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDF_ActivationLineUtils.cls
@IsTest
public with sharing class TDF_ActivationLineUtils {
    public static List<Activation_line__c> createActivationlines(List<SBQQ__QuoteLine__c> theLines) {
		List<Activation_line__c> result = new List<Activation_line__c>();
		List<String> activationTypeList = new List<String>();
		for (SBQQ__QuoteLine__c singleLine : theLines) {
            Id tmpActivation = singleLine.Activation__c;
            Id tmpQuoteLine = singleLine.Id;
            String tmpRecordTypeName = singleLine.Activation_Record_Type__c + ' activation line';
            String tmpBillingCity = singleLine.SBQQ__Quote__r.SBQQ__BillingCity__c;
            Id tmpProduct = singleLine.SBQQ__Product__c;
            String noActivationNeeded = TDF_Constants.NO_ACTIVATION_NEEDED;

            if(!tmpRecordTypeName.contains(noActivationNeeded)) {
                result.add(
                    new Activation_line__c(
                        Activation__c = tmpActivation,
                        Quote_line__c = tmpQuoteLine,
                        RecordTypeId = Schema.sObjectType.Activation_line__c.getRecordTypeInfosByName()
                            .get(tmpRecordTypeName)
                            .getRecordTypeId(),
                        Delivery_City__c = tmpBillingCity,
                        Manual_Product__c = tmpProduct
                    )
                );
            }
		}
		insert result;
		return result;
	}
}