force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/No_of_Location_Lines__c.field-meta.xml
<CustomField>
    <fullName>No_of_Location_Lines__c</fullName>
    <description>No of Location Lines when the Opportunity was closed and data was moved from Location Line to Activation Line.</description>
    <inlineHelpText>Summary of number of valid Location Lines when the Opportunity was closed.</inlineHelpText>
    <label>No. of Location Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Installation_address__c.field-meta.xml
<CustomField>
    <fullName>Installation_address__c</fullName>
    <inlineHelpText>Customer address where site will be documented in SmallWorld</inlineHelpText>
    <label>Installation address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>Street Number</description>
    <label>Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <formula>CASESAFEID(Activation__r.Case__r.Opportunity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Installation_Address__c/Installation_Address__c.object-meta.xml
<CustomObject>
    <description>Installation address for Wholesale orders</description>
    <label>Installation Address</label>
    <nameField>
        <displayFormat>IA-{00000000}</displayFormat>
        <label>Installation Address No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Address__c/fields/Installation_Address__c.field-meta.xml
<CustomField>
    <fullName>Installation_Address__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Installation_Address__c/&quot;&amp;Id&amp;&quot;/view&quot;,
IF(ISBLANK(Secondary_Street__c), 
    IF(ISBLANK(Primary_Street__c), Name ,Primary_Street__c &amp; &quot; &quot; &amp;  Primary_Street_Number__c ),
     Primary_Street__c &amp;&quot; to &quot;&amp; Secondary_Street__c),&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK( Street_Name__c ), &apos;&apos;, (Street_Name__c + &apos; &apos; + Number__c)) +
IF(ISBLANK( Floor__c ), &apos;&apos;, (&apos;, &apos; + Floor__c)) +
IF(ISBLANK( Door__c ), &apos;&apos;, IF((FIND(&apos;.&apos;, Floor__c)) &gt; 0, (&apos; &apos; + Door__c), (&apos;. &apos; + Door__c))) +
IF(ISBLANK( ZIP_Code__c ), &apos;&apos;, (&apos;, &apos; + ZIP_Code__c)) +
IF(ISBLANK( City__c ), &apos;&apos;, (&apos; &apos; + City__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The QuoteLine that resulted from this LocationLine.</description>
    <inlineHelpText>The QuoteLine that resulted from this LocationLine.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Framework</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomeOfficeFlowActionSpecifiedTest.cls
/** 
 * Testing HomeOfficeFlowAction class
 * 
 * @author  Kirstine Nielsen
 * @since   07-05-2025
 * @see     https://jira.atlassian.teliacompany.net/browse/DKT-44508
 */
@IsTest 
private with sharing class HomeOfficeFlowActionSpecifiedTest {    
    
    @IsTest  
    private static void singleOpportunity_Specified() {
        // ARRANGE     
        List<String> cvrList = new List<String>{'87654321'};   
        TDF_HomeOfficeUtils.makeDataSpecified(cvrList);  
        
        // get the opportunity and Location Line that was created in TestSetup
        Opportunity testOpportunity = [SELECT Id, Agreement_Type__c FROM Opportunity LIMIT 1];        
        List<Location_Line__c> testLocationLines = [SELECT Id, Address__c FROM Location_Line__c WHERE Opportunity__c = :testOpportunity.Id];

        List<Activation__c> testActivations = [SELECT Id FROM Activation__c];
        
        List<SBQQ__Quote__c> testQuotes = [SELECT Id FROM SBQQ__Quote__c];
        List<Product2> listOfProductsToUse = [SELECT Id FROM Product2];
        List<PricebookEntry> listOfPricebookEntries = [SELECT Id, Product2Id FROM PricebookEntry];
        Map<Id, PricebookEntry> mapOfProductToPricebookEntries = TDF_ProductUtils.createProductIdToPricebookEntryMap(
            listOfPricebookEntries, 
            listOfProductsToUse
        );

        // create extra quote line under same quote (to test multiple quote lines under same quote works)
        List<SBQQ__QuoteLine__c> testQuoteLines1 = TDF_QuoteLineUtils.createQuoteLinesForQuote(
            testQuotes, 
            false, 
            listOfProductsToUse, 
            mapOfProductToPricebookEntries
        );     
        testQuoteLines1[0].Activation__c = testActivations[0].Id;
        update testQuoteLines1;

        // prep your inputVariables object and add to inputVariablesList
        HomeOfficeFlowAction.InputVariables inputVariables = new HomeOfficeFlowAction.InputVariables();
        inputVariables.inputOpportunity = testOpportunity;
        List<HomeOfficeFlowAction.InputVariables> inputVariablesList = new List<HomeOfficeFlowAction.InputVariables>{inputVariables};

        // ACT
        Test.startTest();
        
        List<HomeOfficeFlowAction.OutputVariables> testOutputVariablesList = 
            HomeOfficeFlowAction.getHomeOfficeRelatedRecordsToActOn(inputVariablesList);

        Test.stopTest();
        
        // ASSERT
        Assert.areEqual(1, testOutputVariablesList.size(), 'We expected 1 OutputVarables');
        // loop the outputVariables and compare the results with your expected variables
        for (HomeOfficeFlowAction.OutputVariables testOutputVariables : testOutputVariablesList) {
            Assert.areEqual(1, testOutputVariables.activationLinesToUpdate.size(), 'We expected 1 Activation Line to update');
            // we don't expect location lines to be updated since they already have their quote line lookup field set
            Assert.areEqual(0, testOutputVariables.locationLinesToUpdate.size(), 'We expected 0 Location Line to update');
            Assert.areEqual(0, testOutputVariables.quoteLinesToUpdate.size(), 'We expected 0 Quote Line to update');
            Assert.areEqual(0, testOutputVariables.activationLinesToDelete.size(), 'We expected 0 Activation Lines to delete');
            Assert.areEqual(1, testOutputVariables.activationToUpdate.No_of_Location_Lines__c, 'We expected No_of_Location_Lines__c on Activation to be 1');
            Assert.areEqual(testOpportunity.Id, testOutputVariables.activationLinesToUpdate[0].Opportunity_ID__c, 
                'Opportunity Id should match Opportunity Id on Activation Line');
            Assert.areEqual(
                testLocationLines[0].Address__c, 
                testOutputVariables.activationLinesToUpdate[0].Installation_address__c, 
                'Installation Address should match Address on the Location Line'
            );
        }
    }

    /**
     * Bulk 2 opportunities for specified
     */
    @IsTest
    private static void bulkOpportunity_Specified() {
        // ARRANGE     
        List<String> cvrList = new List<String>{'12345678', '87654321'};   
        TDF_HomeOfficeUtils.makeDataSpecified(cvrList);   
        
        // get the opportunities that were created in TestSetup
        List<Opportunity> testOpportunities = [SELECT Id, Agreement_Type__c FROM Opportunity];      
        List<Location_Line__c> testLocationLines = [SELECT Id, Address__c FROM Location_Line__c WHERE Opportunity__c IN :testOpportunities];

        // prep your inputVariables object and add to inputVariablesList
        List<HomeOfficeFlowAction.InputVariables> inputVariablesList = new List<HomeOfficeFlowAction.InputVariables>();
        // for each opp, create a new inputVariables object and add to inputVariablesList
        for (Opportunity testOpportunity : testOpportunities) {
            HomeOfficeFlowAction.InputVariables inputVariables = new HomeOfficeFlowAction.InputVariables();
            inputVariables.inputOpportunity = testOpportunity;
            inputVariablesList.add(inputVariables);
        }

        // ACT
        Test.startTest();
        
        List<HomeOfficeFlowAction.OutputVariables> testOutputVariablesList = 
            HomeOfficeFlowAction.getHomeOfficeRelatedRecordsToActOn(inputVariablesList);

        Test.stopTest();
        
        // ASSERT
        Assert.areEqual(2, testOutputVariablesList.size(), 'We expected 2 OutputVarables');
        // loop the outputVariables and compare the results with your expected variables
        for (Integer i = 0; i < testOutputVariablesList.size(); i++) {
            HomeOfficeFlowAction.OutputVariables testOutputVariables = testOutputVariablesList[i];
            Assert.areEqual(1, testOutputVariables.activationLinesToUpdate.size(), 'We expected 1 Activation Line to update');

            // we don't expect location lines to be updated since they already have their quote line lookup field set
            Assert.areEqual(0, testOutputVariables.locationLinesToUpdate.size(), 'We expected 0 Location Line to update');
            Assert.areEqual(0, testOutputVariables.quoteLinesToUpdate.size(), 'We expected 0 Quote Line to update');
            Assert.areEqual(0, testOutputVariables.activationLinesToDelete.size(), 'We expected 0 Activation Lines to delete');
            Assert.areEqual(1, testOutputVariables.activationToUpdate.No_of_Location_Lines__c, 'We expected No_of_Location_Lines__c on Activation to be 1');
            Assert.areEqual(inputVariablesList[i].inputOpportunity.Id, testOutputVariables.activationLinesToUpdate[0].Opportunity_ID__c, 
                'Opportunity Id should match Opportunity Id on Activation Line');
        }
    }
    
    /**
     * test quote line on activation line is null
     * We have 3 location lines
     * We have 3 activation lines, but where one has quote line set to null
     * Ensure there are only 2 activation lines to update, since the third has quote line as null.
     */
    @IsTest  
    private static void quoteLineOnActivationLineIsNull_Specified() {
        // ARRANGE     
        List<String> cvrList = new List<String>{'87654321'};   
        TDF_HomeOfficeUtils.makeDataSpecified(cvrList);  
        
        // get the opportunity and Location Line that was created in TestSetup
        Opportunity testOpportunity = [SELECT Id, Agreement_Type__c FROM Opportunity LIMIT 1];

        // we have one quote line
        List<SBQQ__QuoteLine__c> testQuoteLines = [
            SELECT 
                Id, 
                Activation__c, 
                Activation_Created__c,
                Activation_Record_Type__c, 
                SBQQ__Product__c,
                SBQQ__Product__r.Name,
                SBQQ__Quote__c,
                SBQQ__Quote__r.Name,
                SBQQ__Quote__r.SBQQ__Opportunity2__c,
                SBQQ__Quote__r.SBQQ__BillingCity__c 
            FROM SBQQ__QuoteLine__c
        ];

        Integer extraCount = 2;
        // create extra location line, then insert    
        List<Location_Line__c> testExtraLocationLines = new List<Location_Line__c>();
        for (Integer i = 0; i < extraCount; i++) {
            Location_Line__c testExtraLocationLine = TDF_LocationLineUtils.createLocationLineForOpportunity(
                testOpportunity, 
                HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03,
                testQuoteLines[0]
            );
            testExtraLocationLine.OTC_product__c = 'CHXT02';
            testExtraLocationLines.add(testExtraLocationLine);
        }
        insert testExtraLocationLines;

        // create extra activation lines for same quote line, and set quote line to null on one of them
        List<Activation_Line__c> activationLinesExtraList1 = TDF_ActivationLineUtils.createActivationLines(testQuoteLines);
        activationLinesExtraList1[0].Quote_Line__c = null;
        update activationLinesExtraList1;
        List<Activation_Line__c> activationLinesExtraList2 = TDF_ActivationLineUtils.createActivationLines(testQuoteLines);

        // prep your inputVariables object and add to inputVariablesList
        HomeOfficeFlowAction.InputVariables inputVariables = new HomeOfficeFlowAction.InputVariables();
        inputVariables.inputOpportunity = testOpportunity;
        List<HomeOfficeFlowAction.InputVariables> inputVariablesList = new List<HomeOfficeFlowAction.InputVariables>{inputVariables};

        // ACT
        Test.startTest();
        
        List<HomeOfficeFlowAction.OutputVariables> testOutputVariablesList = 
            HomeOfficeFlowAction.getHomeOfficeRelatedRecordsToActOn(inputVariablesList);

        Test.stopTest();
        
        // ASSERT
        Assert.areEqual(1, testOutputVariablesList.size(), 'We expected 1 OutputVarables');
        // loop the outputVariables and compare the results with your expected variables
        for (HomeOfficeFlowAction.OutputVariables testOutputVariables : testOutputVariablesList) {
            Assert.areEqual(2, testOutputVariables.activationLinesToUpdate.size(), 'We expected 2 Activation Line to update');
            // we don't expect location lines to be updated since they already have their quote line lookup field set
            Assert.areEqual(0, testOutputVariables.locationLinesToUpdate.size(), 'We expected 0 Location Line to update');
            Assert.areEqual(0, testOutputVariables.quoteLinesToUpdate.size(), 'We expected 0 Quote Line to update');
            Assert.areEqual(0, testOutputVariables.activationLinesToDelete.size(), 'We expected 0 Activation Lines to delete');
            Assert.areEqual(3, testOutputVariables.activationToUpdate.No_of_Location_Lines__c, 'We expected No_of_Location_Lines__c on Activation to be 3');
            for (Activation_Line__c activationLine : testOutputVariables.activationLinesToUpdate) {
                Assert.areEqual(
                    testOpportunity.Id, 
                    activationLine.Opportunity_ID__c, 
                    'Opportunity Id should match Opportunity Id on Activation Line'
                );
            }
        }
    }

    /**
     * specified Quote Line on the Location Line is null.
     * Ensure that activationLinesToUpdate is empty because there is no match because Quote Line is null.
     */
    @IsTest
    private static void quoteLineOnLocationLineIsNull_Specified() {        
        // ARRANGE     
        List<String> cvrList = new List<String>{'87654321'};   
        TDF_HomeOfficeUtils.makeDataSpecified(cvrList);
        
        // get the opportunity and Location Line that was created in TestSetup
        Opportunity testOpportunity = [SELECT Id, Agreement_Type__c FROM Opportunity LIMIT 1];      
        List<Activation_Line__c> activationLinesList = [SELECT Id, Manual_Product__c, Quote_line__c, Activation__c FROM Activation_Line__c];  
        List<Location_Line__c> testLocationLines = [SELECT Id, Address__c, Quote_Line__c FROM Location_Line__c WHERE Opportunity__c = :testOpportunity.Id];

        // update the Quote Line field on the Location Line to null
        testLocationLines[0].Quote_Line__c = null;
        update testLocationLines;

        // query quote lines (there is one) that matches activation, this should be the one that eventually gets assigned ot location line
        List<SBQQ__QuoteLine__c> testQuoteLines = [
            SELECT Id, SBQQ__Product__c
            FROM SBQQ__QuoteLine__c
            WHERE Activation__c = :activationLinesList[0].Activation__c
        ];

        // prep your inputVariables object and add to inputVariablesList
        HomeOfficeFlowAction.InputVariables inputVariables = new HomeOfficeFlowAction.InputVariables();
        inputVariables.inputOpportunity = testOpportunity;
        List<HomeOfficeFlowAction.InputVariables> inputVariablesList = new List<HomeOfficeFlowAction.InputVariables>{inputVariables};

        // ACT
        Test.startTest();
        
        List<HomeOfficeFlowAction.OutputVariables> testOutputVariablesList = 
            HomeOfficeFlowAction.getHomeOfficeRelatedRecordsToActOn(inputVariablesList);

        Test.stopTest();
        
        // ASSERT
        Assert.areEqual(1, testOutputVariablesList.size(), 'We expected 1 OutputVarables');
        // loop the outputVariables and compare the results with your expected variables
        for (HomeOfficeFlowAction.OutputVariables testOutputVariables : testOutputVariablesList) {
            Assert.areEqual(0, testOutputVariables.activationLinesToUpdate.size(), 'We expected 0 Activation Line to update');
            // we don't expect location lines to be updated since they already have their quote line lookup field set
            Assert.areEqual(0, testOutputVariables.locationLinesToUpdate.size(), 'We expected 0 Location Line to update');
            Assert.areEqual(0, testOutputVariables.quoteLinesToUpdate.size(), 'We expected 0 Quote Line to update');
            Assert.areEqual(0, testOutputVariables.activationLinesToDelete.size(), 'We expected 0 Activation Lines to delete');
            Assert.isNull(testOutputVariables.activationToUpdate.No_of_Location_Lines__c, 'We expected No_of_Location_Lines__c on Activation to be null');
        }
    }

    /**
     * Multiple (2) Location and Activation Lines
     */
    @IsTest 
    private static void multipleLocationAndActivationLine_Specified() {
        // ARRANGE
        List<String> cvrList = new List<String>{'12345678'};
        TDF_HomeOfficeUtils.makeDataSpecified(cvrList);

        Opportunity testOpportunity = [SELECT Id, Agreement_Type__c FROM Opportunity LIMIT 1];    

        // we want to create more activation lines and location lines under the quote line (in this scenario there is one Quote Line)
        // requery to have the fields
        SBQQ__QuoteLine__c testQuoteLine = [
            SELECT 
                Id, 
                Activation__c, 
                Activation_Created__c,
                Activation_Record_Type__c, 
                SBQQ__Product__c,
                SBQQ__Product__r.Name,
                SBQQ__Quote__c,
                SBQQ__Quote__r.Name,
                SBQQ__Quote__r.SBQQ__Opportunity2__c,
                SBQQ__Quote__r.SBQQ__BillingCity__c 
            FROM SBQQ__QuoteLine__c
            LIMIT 1
        ];

        // create extra Location Line for opp, then insert
        Location_Line__c testLocationLineExtra = TDF_LocationLineUtils.createLocationLineForOpportunity(
            testOpportunity, 
            HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03,
            testQuoteLine
        );
        testLocationLineExtra.OTC_product__c = 'CHXT02';
        // adjust address
        testLocationLineExtra.ZIP_Code__c = '7700';
        testLocationLineExtra.City__c = 'Thisted';
        testLocationLineExtra.Number__c = '30';
        testLocationLineExtra.Street_Name__c = 'Asylgade';
        insert testLocationLineExtra;

        List<Location_Line__c> testLocationLines = [SELECT Id, Address__c, OTC_product__c FROM Location_Line__c];
        // make map of the location lines 
        Map<Id, Location_Line__c> testLocationLineMap = new Map<Id, Location_Line__c>(testLocationLines);

        // create and insert extra Activation Line for opp,
        List<Activation_Line__c> activationLinesExtraList = TDF_ActivationLineUtils.createActivationLines(new List<SBQQ__QuoteLine__c>{testQuoteLine});
        
        // prep your inputVariables object and add to inputVariablesList
        HomeOfficeFlowAction.InputVariables inputVariables = new HomeOfficeFlowAction.InputVariables();
        inputVariables.inputOpportunity = testOpportunity;
        List<HomeOfficeFlowAction.InputVariables> inputVariablesList = new List<HomeOfficeFlowAction.InputVariables>{inputVariables};

        // ACT
        Test.startTest();
        
        List<HomeOfficeFlowAction.OutputVariables> testOutputVariablesList = 
            HomeOfficeFlowAction.getHomeOfficeRelatedRecordsToActOn(inputVariablesList);

        Test.stopTest();
        
        // ASSERT
        Set<Id> usedLocationLineIdSet = new Set<Id>();

        Assert.areEqual(1, testOutputVariablesList.size(), 'We expected 1 OutputVarables');
        // loop the outputVariables and compare the results with your expected variables
        for (HomeOfficeFlowAction.OutputVariables testOutputVariables : testOutputVariablesList) {
            Assert.areEqual(2, testOutputVariables.activationLinesToUpdate.size(), 'We expected 2 Activation Line to update');
            // we don't expect location lines to be updated since they already have their quote line lookup field set
            Assert.areEqual(0, testOutputVariables.locationLinesToUpdate.size(), 'We expected 0 Location Line to update');
            Assert.areEqual(0, testOutputVariables.quoteLinesToUpdate.size(), 'We expected 0 Quote Line to update');
            Assert.areEqual(0, testOutputVariables.activationLinesToDelete.size(), 'We expected 0 Activation Lines to delete');
            Assert.areEqual(2, testOutputVariables.activationToUpdate.No_of_Location_Lines__c, 'We expected No_of_Location_Lines__c on Activation to be 2');
            // check the id for each activation line
            for (Activation_Line__c activationLine : testOutputVariables.activationLinesToUpdate) {
                Assert.areEqual(
                    testOpportunity.Id, 
                    activationLine.Opportunity_ID__c, 
                    'Opportunity Id should match Opportunity Id on Activation Line'
                );
                // 
                if (!usedLocationLineIdSet.contains(activationLine.Location_Line__c)) {
                    // not used yet
                    Location_Line__c locationLine = testLocationLineMap.get(activationLine.Location_Line__c);
                    Assert.areEqual(
                        locationLine.Address__c, 
                        activationLine.Installation_address__c, 
                        'Installation Address should match Address on the Location Line'
                    );
                    // add to set to keep track of used location lines
                    usedLocationLineIdSet.add(activationLine.Location_Line__c);
                }
            }
            // sanity check that you have used two location lines
            Assert.areEqual(2, usedLocationLineIdSet.size(), 'Expected 2 location lines used');
        }
    }

}