force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the specific activation line to a BAN (Billing Account).</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Fastnet_user__c.field-meta.xml
<CustomField>
    <fullName>Fastnet_user__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate in the Onboarding Portal if the user is a Fastnet user.</description>
    <label>Fastnet user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>Mobile_no__c</fullName>
    <description>Mobile number that can have max 8 digits</description>
    <inlineHelpText>Mobile number that can have max 8 digits</inlineHelpText>
    <label>Mobile no.</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_no_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_no_Status__c</fullName>
    <inlineHelpText>Chose what needs to be done with number</inlineHelpText>
    <label>Phone no Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Phone_no_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Related_Activation_line__c.field-meta.xml
<CustomField>
    <fullName>Related_Activation_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link the mobile activation line to the touchpoint activation line</description>
    <inlineHelpText>Shows the mobile activation line that the touchpoint activation line is linked to</inlineHelpText>
    <label>Related Activation line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Activation__c</field>
            <operation>equals</operation>
            <valueField>$Source.Activation__c</valueField>
        </filterItems>
        <filterItems>
            <field>Activation_line__c.Mobile_no__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Activation_line__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activation_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/TOP_Activation_Flow_Step__c.field-meta.xml
<CustomField>
    <fullName>TOP_Activation_Flow_Step__c</fullName>
    <description>Used to store current flow step during TOP activation process when clicked &quot;Save to continue later&quot;</description>
    <inlineHelpText>Used to store current flow step during TOP activation process when clicked &quot;Save to continue later&quot;</inlineHelpText>
    <label>TOP Activation Flow Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/TOP_Completed_Flows__c.field-meta.xml
<CustomField>
    <fullName>TOP_Completed_Flows__c</fullName>
    <description>Comma separated list of completed TOP activation flow ids</description>
    <inlineHelpText>Comma separated list of completed TOP activation flow ids</inlineHelpText>
    <label>TOP Completed Flows</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_UC_License__c.field-meta.xml
<CustomField>
    <fullName>VAS_UC_License__c</fullName>
    <inlineHelpText>Add the UC license relevant for the specific user if part of quote</inlineHelpText>
    <label>UC License</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UC_License</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ActivationLineService.cls
public class ActivationLineService {
    
    private final DatabaseService dataBaseService;
 
    @TestVisible
    private ActivationLineService(DatabaseService dbService) {
        this.dataBaseService = dbService;
    }

    public ActivationLineService(){
        this(SingletonFactory.getFactory());
    }
 
    private ActivationLineService(SingletonFactory singletonFactory) {
        this.dataBaseService = (DatabaseService) singletonFactory.getOrRegisterSingleton(DatabaseService.class);
    }
 
    public void createActivationLine(List<Activation_line__c> activationLineList) {
        Logger.logInfo(String.format('createActivationLine( {0} )', new List<Object>{ activationLineList }));
        List<Activation_line__c> activationLines = new List<Activation_line__c>();
 
        for (Activation_line__c al : activationLineList) {
            if (al.Fastnet_user__c && String.isNotBlank(al.VAS_UC_License__c)
                && al.TOP_Completed_Flows__c == 'Voice_Flow' && al.TOP_Activation_Flow_Step__c == 'FINISHED') {
                   
                Activation_line__c actiline = new Activation_line__c( Activation__c = al.Activation__c,
                                                                        Related_Activation_line__c = al.id,
                                                                        Case__c = al.Case__c,
                                                                        Quote_line__c = al.Quote_line__c,
                                                                        Manual_Product__c = system.label.TPX_Funktionnr,
                                                                        TOP_Activation_Flow_Step__c = 'FINISHED',
                                                                        TOP_Completed_Flows__c = 'Voice_Flow',
                                                                        RecordTypeId = '0121i000000HJjrAAG',
                                                                        Billing_Account__c = al.Billing_Account__c,
                                                                        Phone_no_Status__c = al.Phone_no_Status__c
                                                                    );
                activationLines.add(actiline);
            }    
        }
 
        if (!activationLines.isEmpty()){ 
            dataBaseService.insertRecords(activationLines); 
        }
    }

    public List<Activation_line__c> hasCompletedVoiceFlow(List<Activation_line__c> triggerNew, List<Activation_line__c> triggerOld) {
        Logger.logInfo(String.format('hasCompletedVoiceFlow( {0},{1} )', new List<Object>{ triggerNew, triggerOld}));
        List<Activation_line__c> activationLines = new List<Activation_line__c>();

        for (Integer i = 0; i < triggerNew.size(); i++) {
            Activation_line__c newRec = triggerNew[i];
            Activation_line__c oldRec = triggerOld[i];
            if (
                newRec.TOP_Activation_Flow_Step__c != oldRec.TOP_Activation_Flow_Step__c &&
                newRec.TOP_Completed_Flows__c != oldRec.TOP_Completed_Flows__c &&
                newRec.TOP_Completed_Flows__c == 'Voice_Flow'
            ) {
                activationLines.add(newRec);
            }
        }

        return activationLines;
    }

     /**
     * Retrieves a map of activationLineId to MobileNo when activation_line__c records are deleted.
     * 
     *
     * @param oldList The list of old activation_line__c records.
     * @return A map of activationLineId to MobileNo
     */
    public Map<Id, String> getMapOfActivationLineToPhoneNumberForActivationLineDeletes(List<Activation_Line__c> oldList){
        Logger.logInfo(String.format('getMapOfActivationLineToPhoneNumberForActivationLineDeletes( {0} )', new List<Object>{ oldList}));

        Map<Id, String> mapOfActivationLineToPhoneNumber = new Map<Id, String>();

        if (oldList == null) {
            Logger.logError('oldList is null.');
        }
        else {
            for (Activation_Line__c actLine : oldList) {
                mapOfActivationLineToPhoneNumber.put(actLine.Id, actLine.Mobile_No__c);  
            }
        }

        return mapOfActivationLineToPhoneNumber;
    } 
}