force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/TP_X_Upsell__c.field-meta.xml
<CustomField>
    <fullName>TP_X_Upsell__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify Type:New Activations created for existing mobile subscriptions</description>
    <label>TP/X Upsell</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Identify the different activation parts in a Renewal process since existing subcription renewal process will be different than the upsell subscriptions</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Renew Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Detail__c/Quote_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Detail</label>
    <nameField>
        <displayFormat>QLD-{000000}</displayFormat>
        <label>Quote Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Detail__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Quote Line Details</relationshipLabel>
    <relationshipName>Quote_Line_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Detail__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Line Details</relationshipLabel>
    <relationshipName>Quote_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>These field has been created to hold 255 signs of additional information that might be useful in problem solving of this error.</description>
    <inlineHelpText>Additional helpful information like name of class/flow ect.</inlineHelpText>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Activation_Create_Iterable.cls
public class Activation_Create_Iterable implements Database.Batchable<sObject> {
	public String query;
	public List<Id> recordId;
	public Database.querylocator start(Database.BatchableContext BC) {
		String squery =
			'SELECT Id,Activation_Record_Type__c,SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__c,Additional_Quantity__c,' +
			' SBQQ__RenewedSubscription__c,SBQQ__ProductOption__r.SBQQ__Feature__r.SBQQ__Category__c ' +
			' from SBQQ__QuoteLine__c where SBQQ__Quote__c in :recordId' +
			' and SBQQ__EffectiveQuantity__c >0 and Activation_Record_Type__c <>\'No activation needed\'';
			System.debug('Activation_Create_Iterable squery = ' + squery);
		return Database.getQueryLocator(squery);
	}

	public void execute(Database.BatchableContext BC, List<SBQQ__QuoteLine__c> scope) {
		System.debug('Activation_Create_Iterable execute called with scope = ' + scope);
		List<Activation__c> ActivationList = [
			SELECT Id, RecordType.name, Type__c, TP_X_Upsell__c
			FROM Activation__c
			WHERE Case__r.Quote__c IN :recordId
		];
		System.debug('ActivationList$ = ' + ActivationList);

		List<Quote_Line_Detail__c> QLDList = [
			SELECT Id, Quote_Line__c
			FROM Quote_Line_Detail__c
			WHERE Quote_Line__r.SBQQ__Quote__c IN :recordId
		];
		System.debug('QLDList = ' + QLDList);

		Map<String, Integer> QLDCount = new Map<String, Integer>();
		boolean TPUpsell = false;

		if (QLDList != null && QLDList.size() > 0) {
			for (Quote_Line_Detail__c qld : QLDList) {
				if (!QLDCount.containsKey(String.valueOf(qld.Quote_Line__c))) {
					QLDCount.put(String.valueOf(qld.Quote_Line__c), 1);
				}
			}
		}
		Map<String, Id> ActivationIdsPerRecordType = new Map<String, Id>(); //Voice-New,XXXX
		try {
			for (Activation__c ac : ActivationList) {
				ActivationIdsPerRecordType.put(ac.RecordType.name.remove(' activation') + ' - ' + ac.Type__c, ac.Id);
				if (ac.TP_X_Upsell__c) {
					TPUpsell = true;
				}
			}
			system.debug('ActivationIdsPerRecordType + ' + ActivationIdsPerRecordType);

			List<SBQQ__QuoteLine__c> updateQuoteLineList = new List<SBQQ__QuoteLine__c>();
			string typeCheck;
			for (SBQQ__QuoteLine__c s : scope) {
		
		
				// DISABLED 30/07/2024 - PROJECT CASE MANAGEMENT
				// //if there is TPupsell, activation type will be New for Voice activations
				// if (s.Activation_Record_Type__c == 'Voice' && TPUpsell == true) {
				// 	typeCheck = 'New';
				// } else if (
				// 	QLDCount.containsKey(String.valueOf(s.Id)) ==
				// 	true //If QLD exists mark as renew Existing
				// ) {
				// 	typeCheck = 'Renew Existing';
				// } else {
				// 	typeCheck = 'New';
				// }
				typeCheck = 'New';

				system.debug('typeCheck = ' + typeCheck);

				// DISABLED CASE MANAGEMENT
				system.debug(s.Activation_Record_Type__c);
				if (ActivationIdsPerRecordType.get(s.Activation_Record_Type__c + ' - ' + typeCheck) == null) {
					System.debug('Not found!');
					Activation__c NewActivation = new Activation__c(
						Case__c = s.SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__c,
						RecordTypeId = Schema.sObjectType.Activation__c.getRecordTypeInfosByName()
							.get(s.Activation_Record_Type__c + ' activation')
							.getRecordTypeId(),
						Name = s.Activation_Record_Type__c + ' - ' + typeCheck,
						Type__c = typeCheck
					);
					System.debug(Schema.sObjectType.Activation__c.getRecordTypeInfosByName().get(s.Activation_Record_Type__c + ' activation').getRecordTypeId());
					insert NewActivation;
					System.debug('NewActivation = ' + NewActivation);
					ActivationIdsPerRecordType.put(s.Activation_Record_Type__c + ' - ' + typeCheck, NewActivation.Id);
				}
				updateQuoteLineList.add(
					new SBQQ__QuoteLine__c(Id = s.Id, Activation__c = ActivationIdsPerRecordType.get(s.Activation_Record_Type__c + ' - ' + typeCheck))
				);
			}
			System.debug('updateQuoteLineList = ' + updateQuoteLineList);
			update updateQuoteLineList;
		} catch (Exception e) {
			System.debug('### Error Occured while updateing Quote lines with activations : ' + e.getMessage());
			System_Log__c logerror = new System_Log__c(
				Origin__c = 'Apex',
				Error_Body__c = e.getMessage() + ' LineNumber: ' + e.getLineNumber(),
				Additional_Information__c = 'Activation_Create_Iterable'
			);
			insert logerror;
		}
	}
	public void finish(Database.BatchableContext BC) {
		Activation_line_Create.Activation_line_Create(recordId);
	}
}