force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/HomeOfficeDataWrapper.cls
/** 
 * Wrapper class that holds maps belonging to an Opportunity.
 * Used in the Home Office solution to ensure that Activation Lines are updated with data from Location Lines.
 * 
 * @author  Kirstine Nielsen
 * @since   07-05-2025
 * @see     https://jira.atlassian.teliacompany.net/browse/DKT-44508
 */
public with sharing class HomeOfficeDataWrapper {
    
    public Map<Id, SBQQ__QuoteLine__c> quoteLineMap;
    public Map<String, List<SBQQ__QuoteLine__c>> concatenatedIdsToQuoteLinesMap;
    public Map<Id, Activation_Line__c> activationLineMap;
    public Map<Id, Activation__c> activationMap;
    public Map<Id, Location_Line__c> locationLineMap;
    public Map<Id, Activation_Line__c> locationLineIdToActivationLineMap;
    public Map<Id, List<Activation_Line__c>> quoteLineIdToActivationLinesMap;    
    
    // HomeOfficeDataWrapper with necessary map properties for a specific Opportunity
    public HomeOfficeDataWrapper() {
        this.quoteLineMap = new Map<Id, SBQQ__QuoteLine__c>();
        this.concatenatedIdsToQuoteLinesMap = new Map<String, List<SBQQ__QuoteLine__c>>();
        this.activationLineMap = new Map<Id, Activation_Line__c>();
        this.activationMap = new Map<Id, Activation__c>();
        this.locationLineMap = new Map<Id, Location_Line__c>();
        this.locationLineIdToActivationLineMap = new Map<Id, Activation_Line__c>();
        this.quoteLineIdToActivationLinesMap = new Map<Id, List<Activation_Line__c>>();   
    }

}