force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HomeOfficeFlowGetActivationLineTest.cls
/**
 * 
 * @author keh
 * @since 14032025
 */
@IsTest
private class HomeOfficeFlowGetActivationLineTest {

    /**
     * getActivationLine_validInput_returnsCorrectResult
     */
    @IsTest
    static void getActivationLine_validInput_returnsCorrectResult() {
        //ARRANGE
        Account acc = TDF_AccountUtils.creatActiveAccountWithCVRAndOwner();
        insert acc;

        // Create test data
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Qualification';
        opp.CloseDate = date.today();
        opp.AccountId = acc.Id;
        insert opp;
        
        Location_Line__c locationLine1 = new Location_Line__c(Opportunity__c = opp.id);
        Location_Line__c locationLine2 = new Location_Line__c(Opportunity__c = opp.id);
        Location_Line__c locationLine3 = new Location_Line__c(Opportunity__c = opp.id);
        insert new List<Location_Line__c>{locationLine1, locationLine2, locationLine3};
        
        Case case1 = new Case();
        insert case1;
            
       	Activation__c activation1 = new Activation__c(Case__c = case1.id);
        insert activation1;
            
        Activation_Line__c activationLine1 = new Activation_Line__c(Location_Line__c = locationLine1.Id, Activation__c = activation1.id);
        Activation_Line__c activationLine2 = new Activation_Line__c(Location_Line__c = locationLine2.Id, Activation__c = activation1.id);
        Activation_Line__c activationLine3 = new Activation_Line__c(Location_Line__c = locationLine3.Id, Activation__c = activation1.id);
        insert new List<Activation_Line__c>{activationLine1, activationLine2, activationLine3};

        List<Id> processedActivationLineIds = new List<Id>();
        processedActivationLineIds.add(activationLine1.Id);

        List<HomeOfficeFlowGetActivationLine.InputVariables> inputVariablesList = new List<HomeOfficeFlowGetActivationLine.InputVariables>();
        HomeOfficeFlowGetActivationLine.InputVariables inputVariables = new HomeOfficeFlowGetActivationLine.InputVariables();
        inputVariables.activationLines = new List<Activation_Line__c>{activationLine1, activationLine2, activationLine3};
        inputVariables.processedActivationLineIds = processedActivationLineIds;
        inputVariables.agreementType = 'Framework';
        inputVariables.selectionRecordId = activationLine2.Location_Line__c;
        inputVariablesList.add(inputVariables);

        //ACT
        // Call the method
        Test.startTest();
        List<HomeOfficeFlowGetActivationLine.OutputVariables> output = HomeOfficeFlowGetActivationLine.getActivationLine(inputVariablesList);
        Test.stopTest();

        //ASSERT
        // Verify the output
        System.assertEquals(1, output.size(), 'Expected one output record');
        Activation_Line__c selectedActivationLine = output[0].activationLine;
        System.assertEquals(activationLine2.Id, selectedActivationLine.Id, 'Unexpected activation line selected');
    }
}