force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HomeOfficeFlowActionDAO.cls
/** 
 * DAO class that helps provide the necessary data for the Home Office Flow Action.
 * Used in the Home Office solution to ensure that Activation Lines are updated with data from Location Lines.
 * 
 * @author  Kirstine Nielsen
 * @since   07-05-2025
 * @see     https://jira.atlassian.teliacompany.net/browse/DKT-44508
 */
public without sharing class HomeOfficeFlowActionDAO {    
    
    // we are only interested in products where 'Telia Product Id' (ProductAPI_Telia_Product_Id__c) is not null
    public static List<Product2> products = ProductSelector.getAllProductsHavingTeliaProductId();
    // map of teliaProductIdString and product
    public static Map<String, Product2> teliaProductIdStringToProductMap = getTeliaProductIdStringToProductMap(products);

    // Opportunities
    public Map<Id, Opportunity> opportunityMap;

    // Quote Lines
    public Map<Id, SBQQ__QuoteLine__c> quoteLineAllMap = new Map<Id, SBQQ__QuoteLine__c>();

    // Activation Lines
    public Map<Id, Activation_Line__c> activationLineAllMap =  new Map<Id, Activation_Line__c>();

    // Activation
    public Map<Id, Activation__c> activationAllMap = new Map<Id, Activation__c>();

    // Location Lines
    public List<Location_Line__c> locationLinesAll = new List<Location_Line__c>();
    
    /**
     * constructor accepting a list of opportunities
     */
    public HomeOfficeFlowActionDAO(List<Opportunity> opportunities) {
        // opportunity
        this.opportunityMap = new Map<Id, Opportunity>(opportunities);

        // quote lines
        this.quoteLineAllMap = getQuoteLineMap(this.opportunityMap.keySet());

        // activation lines
        this.activationLineAllMap = getActivationLineMap(this.opportunityMap.keySet());        

        // activations
        this.activationAllMap = getActivationMap(this.activationLineAllMap.values());

        // Location Lines
        this.locationLinesAll = retrieveLocationLines(this.opportunityMap.keySet());
    } 

    /**
     * Returns a map of activations based on activations related to the activation lines passed in
     * 
     * @param List<Id> activation lines
     * @return Map<Id, Activation__c> activationMap
     */
    private Map<Id, Activation__c> getActivationMap(List<Activation_Line__c> activationLines) {
        Set<Id> activationIdSet = getActivationIdSetFromActivationLines(activationLines);
        List<Activation__c> activations = new List<Activation__c>();
        activations = ActivationSelector.getHomeOfficeActivationByIds(activationIdSet);
        Map<Id, Activation__c> activationMapToReturn = new Map<Id, Activation__c>(activations);
        return activationMapToReturn;
    }

    /**
     * Returns Activation Line Map of records where the opportunity id matches an opportunity id in set passed in.
     * @param opportunityIdSet 
     * @return map of activation lines
     */
    private Map<Id, Activation_Line__c> getActivationLineMap(Set<Id> opportunityIdSet) {
        List<Activation_Line__c> activationLines = new List<Activation_Line__c>();
        activationLines = ActivationLineSelector.getHomeOfficeActivationLinesByOpportunityIds(opportunityIdSet);
        Map<Id, Activation_Line__c> activationLinesToReturnMap = new Map<Id, Activation_Line__c>(activationLines);
        return activationLinesToReturnMap;
    }

    /**
     * Returns set of activation Ids from list of Activation Lines
     * @param activationLines
     * @return set of activation Ids
     */
    public Set<Id> getActivationIdSetFromActivationLines(List<Activation_Line__c> activationLines) {
        Set<Id> activationIdSetToReturn = new Set<Id>();

        for (Activation_Line__c activationLine : activationLines) {
            // put in set
            activationIdSetToReturn.add(activationLine.Activation__c);
        }
        return activationIdSetToReturn;
    }

    /**
     * Retrieve Location Lines from DB that matches the Opportunity Id's in the set
     * passed to method, and that has valid address wash status.
     * 
     * @param opportunityIdSet
     * @return List<Location_Line__c>
     */
    private List<Location_Line__c> retrieveLocationLines(Set<Id> opportunityIdSet) {
        List<Id> opportunityIdList = new List<Id>(opportunityIdSet);    
        List<Location_Line__c> locationLinesToReturn = LocationLineSelector.getValidLocationLinesByOpportunityIds(
            opportunityIdList
        );
        return locationLinesToReturn;
    }

    /**
     * Returns Quote Line Map of records:
     * - that matches the Opportunity Id's in the set passed to method
     * - where both Activation and Product are populated
     * - of record type Activation Quote
     * 
     * @param opportunityIdSet
     * @return Map<Id, SBQQ__QuoteLine__c>
     */
    private Map<Id, SBQQ__QuoteLine__c> getQuoteLineMap(Set<Id> opportunityIdSet) { 
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines = QuoteLineSelector.getQuoteLinesByOpportunityIds(opportunityIdSet);
        Map<Id, SBQQ__QuoteLine__c> quoteLineMapToReturn = new Map<Id, SBQQ__QuoteLine__c>(quoteLines);
        return quoteLineMapToReturn;
    }

    /**
     * Returns map where ProductAPI_Telia_Product_Id__c is the key and the Product is the value
     * 
     * @param products
     * @return Map<String, Product2>
     */
    private static Map<String, Product2> getTeliaProductIdStringToProductMap(List<Product2> products) {
        Map<String, Product2> teliaProductIdStringToProductMap = new Map<String, Product2>();

        for (Product2 product : products) {
            // sanity check that ProductAPI_Telia_Product_Id__c is not empty and that the map doesn't already contain this key
            if (String.isNotEmpty(product.ProductAPI_Telia_Product_Id__c) && 
                !teliaProductIdStringToProductMap.containsKey(product.ProductAPI_Telia_Product_Id__c)) {
                teliaProductIdStringToProductMap.put(product.ProductAPI_Telia_Product_Id__c, product);
            }
        }

        return teliaProductIdStringToProductMap;
    }
}