force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <description>Used when posting data via the Order API to ensure the subscriptions are related to the correct BAN (Billing Account Number)</description>
    <label>BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/EAN_Number__c.field-meta.xml
<CustomField>
    <fullName>EAN_Number__c</fullName>
    <formula>TEXT(Case__r.Quote__r.EAN_number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EAN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <formula>Case__r.Quote__r.Invoice_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <inlineHelpText>If this is a new customer then an indication of different invoice units is needed by adding 1, 2, 3 etc - if billing units are to be in a hierarchy with more than 1 level under Root then indicate the parent BAN in the above &apos;Parent BAN&apos; field</inlineHelpText>
    <label>BAN</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <inlineHelpText>To be exposed on customer invoice</inlineHelpText>
    <label>Billing City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <inlineHelpText>To be exposed on customer invoice</inlineHelpText>
    <label>Billing Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Name__c</fullName>
    <inlineHelpText>Name of Billing Account (to be exposed on customer invoice)</inlineHelpText>
    <label>Billing Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <inlineHelpText>To be exposed on customer invoice</inlineHelpText>
    <label>Billing Postal Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>Company name</inlineHelpText>
    <label>Company Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/EAN_number__c.field-meta.xml
<CustomField>
    <fullName>EAN_number__c</fullName>
    <inlineHelpText>Enter the public 13 digit EAN number</inlineHelpText>
    <label>EAN number</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <inlineHelpText>Email to receive invoice</inlineHelpText>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>Mobile_no__c</fullName>
    <description>Mobile number that can have max 8 digits</description>
    <inlineHelpText>Mobile number that can have max 8 digits</inlineHelpText>
    <label>Mobile no.</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The order product that this line should activate.</description>
    <inlineHelpText>The order product that this line should activate.</inlineHelpText>
    <label>Order Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Case__c</field>
            <operation>equals</operation>
            <valueField>OrderItem.Order.Case__c</valueField>
        </filterItems>
        <infoMessage>Select a product from the order</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Bruger__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Bruger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether Touchpoint Bruger is a active SOC or a future SOC.</inlineHelpText>
    <label>Touchpoint Bruger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Receptionist__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Receptionist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Receptionist is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Receptionist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Softphone__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Softphone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Softphone is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Softphone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Statistik__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Statistik__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Statistik is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Statistik</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <description>The billing account number for the account related to this case.</description>
    <inlineHelpText>Use the billing account number to correctly bill the customer for the activated product(s).</inlineHelpText>
    <label>BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/Fokus_Subscription__c.object-meta.xml
<CustomObject>
    <label>Fokus Subscription</label>
    <nameField>
        <label>Fokus Subscription</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fokus Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fokus_Subscription__c/fields/AVG_MONTHLY_DATA_CONSUMPTION_MB__c.field-meta.xml
<CustomField>
    <fullName>AVG_MONTHLY_DATA_CONSUMPTION_MB__c</fullName>
    <label>AVG_MONTHLY_DATA_CONSUMPTION_MB</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <label>BAN</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BAN_OWNER_CONTROL_NUA__c.field-meta.xml
<CustomField>
    <fullName>BAN_OWNER_CONTROL_NUA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BAN_OWNER_CONTROL_NUA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BILLING_CITY__c.field-meta.xml
<CustomField>
    <fullName>BILLING_CITY__c</fullName>
    <label>BILLING_CITY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BILLING_COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>BILLING_COUNTRY__c</fullName>
    <label>BILLING_COUNTRY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BILLING_POSTAL_CODE__c.field-meta.xml
<CustomField>
    <fullName>BILLING_POSTAL_CODE__c</fullName>
    <label>BILLING_POSTAL_CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/BILLING_STREET_NO__c.field-meta.xml
<CustomField>
    <fullName>BILLING_STREET_NO__c</fullName>
    <label>BILLING_STREET_NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/CALLS_FROM_DK_TO_EUNB_MIN__c.field-meta.xml
<CustomField>
    <fullName>CALLS_FROM_DK_TO_EUNB_MIN__c</fullName>
    <label>CALLS_FROM_DK_TO_EUNB_MIN</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/COMPANY_NAME__c.field-meta.xml
<CustomField>
    <fullName>COMPANY_NAME__c</fullName>
    <label>COMPANY_NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/CUSTOMER_CURRENT_KEY__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_CURRENT_KEY__c</fullName>
    <label>CUSTOMER_CURRENT_KEY</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/DISCOUNT__c.field-meta.xml
<CustomField>
    <fullName>DISCOUNT__c</fullName>
    <label>DISCOUNT</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/EAN_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>EAN_NUMBER__c</fullName>
    <label>EAN_NUMBER</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/EXISTING_SIM__c.field-meta.xml
<CustomField>
    <fullName>EXISTING_SIM__c</fullName>
    <label>EXISTING_SIM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/EXTRA_SIM_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>EXTRA_SIM_NUMBER__c</fullName>
    <label>EXTRA_SIM_NUMBER</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/FIX_NO__c.field-meta.xml
<CustomField>
    <fullName>FIX_NO__c</fullName>
    <label>FIX_NO</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>LAST_NAME__c</fullName>
    <label>LAST_NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/MAX_MONTHLY_DATA_CONSUMPTION_MB__c.field-meta.xml
<CustomField>
    <fullName>MAX_MONTHLY_DATA_CONSUMPTION_MB__c</fullName>
    <label>MAX_MONTHLY_DATA_CONSUMPTION_MB</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/MOBILE_NO__c.field-meta.xml
<CustomField>
    <fullName>MOBILE_NO__c</fullName>
    <label>MOBILE_NO</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/ORDER_PRODUCT__c.field-meta.xml
<CustomField>
    <fullName>ORDER_PRODUCT__c</fullName>
    <label>ORDER_PRODUCT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/OWNER_CONTROL_NUA__c.field-meta.xml
<CustomField>
    <fullName>OWNER_CONTROL_NUA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OWNER_CONTROL_NUA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/OWNER_CONTROL_RCC__c.field-meta.xml
<CustomField>
    <fullName>OWNER_CONTROL_RCC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OWNER_CONTROL_RCC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/OWNER_CONTROL_TSRR__c.field-meta.xml
<CustomField>
    <fullName>OWNER_CONTROL_TSRR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OWNER_CONTROL_TSRR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/ROOT_CVR_NO__c.field-meta.xml
<CustomField>
    <fullName>ROOT_CVR_NO__c</fullName>
    <label>ROOT_CVR_NO</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/SERVICE_CODE__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_CODE__c</fullName>
    <label>SERVICE_CODE</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DataCollection_RenewalBatch.cls
public class DataCollection_RenewalBatch implements Database.Batchable<sObject> {
	public String query;
	public Database.querylocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		try {
			system.debug('start batch' + scope);
			SBQQ__Quote__c Quote_record = (SBQQ__Quote__c) scope[0];

			String quoteId = String.valueOf(Quote_record.Id);
			String quoteAccount = String.valueOf(Quote_record.SBQQ__Account__c);
			system.debug('start quote Id' + quoteId);
			system.debug('start quote Account' + quoteAccount);
			Map<String, String> TouchpointProducts = new Map<String, String>();
			//FieldName,ProductCode
			TouchpointProducts.put('Touchpoint_Bruger__c', 'TPSUSER');
			TouchpointProducts.put('Touchpoint_Receptionist__c', 'TPSRECEP');
			TouchpointProducts.put('Touchpoint_Softphone__c', 'TPSSOFT');
			TouchpointProducts.put('Touchpoint_Statistik__c', 'TPSSTAT');

			List<String> lstServices;
			List<Activation_line__c> ActivationLines = new List<Activation_line__c>();
			Activation_line__c ActivationLine = new Activation_line__c();

			List<Fokus_Subscription__c> Fokus_Subscription_list = [
				SELECT
					AVG_MONTHLY_DATA_CONSUMPTION_MB__c,
					BAN__c,
					BAN_OWNER_CONTROL_NUA__c,
					BILLING_CITY__c,
					BILLING_COUNTRY__c,
					BILLING_NAME__c,
					BILLING_POSTAL_CODE__c,
					BILLING_STREET_NO__c,
					BROADBAND_NO__c,
					CALLS_FROM_DK_TO_EUNB_MIN__c,
					COMPANY_NAME__c,
					CUSTOMER_CURRENT_KEY__c,
					CVR_NO__c,
					DISCOUNT__c,
					EAN_NUMBER__c,
					EXISTING_SIM__c,
					EXTRA_SIM_NUMBER__c,
					FIRST_NAME__c,
					FIX_NO__c,
					INVOICE_EMAIL__c,
					LAST_NAME__c,
					LOOKUP_MOBILE_USER__c,
					MAX_MONTHLY_DATA_CONSUMPTION_MB__c,
					Name,
					ORDER_PRODUCT__c,
					MOBILE_NO__c,
					OWNER_CONTROL_NUA__c,
					OWNER_CONTROL_RCC__c,
					OWNER_CONTROL_TSRR__c,
					ROOT_CVR_NO__c,
					SERVICE_CODE__c,
					SF_ACCOUNT_KEY__c,
					SUBSCRIBER_CURRENT_KEY__c,
					SUBSCRIBER_EMAIL__c,
					SUBSCRIBER_ID__c,
					SUBSCRIBER_NO__c
				FROM Fokus_Subscription__c
				WHERE SF_ACCOUNT_KEY__c = :quoteAccount
				ORDER BY ORDER_PRODUCT__c DESC
			];

			//Query the VAS services list
			Schema.DescribeSObjectResult activationline_desc = Activation_line__c.sObjectType.getDescribe();

			Map<String, Schema.SObjectField> activationline_fields = activationline_desc.fields.getMap();
			Map<String, String> Vasfields = new Map<String, String>();
			Map<String, List<String>> M2MPicklistProducts = new Map<String, List<String>>();
			//FieldName,FieldValue

			String columnNames = 'Id';

			for (Schema.sObjectField fld : activationline_fields.values()) {
				if (string.valueof(fld).indexOf('VAS_') == 0) {
					if (fld.getDescribe().getType().name().toupperCase() == 'BOOLEAN') {
						columnNames = columnNames + ',' + fld.getDescribe().getName();
					}
					Vasfields.put(fld.getDescribe().getName(), fld.getDescribe().getType().name().toupperCase());
					if (fld.getDescribe().getType().name().toupperCase() == 'PICKLIST') {
						List<String> lstPickvals = new List<String>();
						List<Schema.PicklistEntry> pick_list_values = fld.getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
						for (Schema.PicklistEntry a : pick_list_values) {
							//for all values in the picklist list
							lstPickvals.add(a.getValue()); //add the value  to our final list
						}
						M2MPicklistProducts.put(fld.getDescribe().getName(), lstPickvals); //add the value  to our final list
					}
				}
			}
			system.debug('quote id before soql ' + quoteId);

			List<Activation_line__c> ActivationLinesSelected = [
				SELECT
					Id,
					Mobile_no__c,
					First_name__c,
					Last_name__c,
					Phone_no__c,
					Touchpoint_Bruger__c,
					Touchpoint_Receptionist__c,
					Touchpoint_Softphone__c,
					Touchpoint_Statistik__c,
					Max_Monthly_Data_Used__c,
					Avg_Monthly_Data_Used__c,
					Calls_from_DK_to_EU__c,
					Case__c,
					Activation__c
				FROM Activation_line__c
				WHERE Activation__r.Case__r.Quote__c = :quoteId
			];
			system.debug('act lines ' + ActivationLinesSelected);

			integer i = 0;
			string service_name;
			string strServices = '';
			system.debug('act lines ' + ActivationLinesSelected);
			for (Activation_line__c ActivationLineRecord : ActivationLinesSelected) {
				ActivationLine.id = String.valueOf(ActivationLineRecord.Id);
				ActivationLine.Mobile_no__c = String.valueOf(Fokus_Subscription_list[i].MOBILE_NO__c);
				ActivationLine.First_name__c = Fokus_Subscription_list[i].FIRST_NAME__c;
				ActivationLine.Last_name__c = Fokus_Subscription_list[i].LAST_NAME__c;
				ActivationLine.Email_address__c = Fokus_Subscription_list[i].SUBSCRIBER_EMAIL__c;
				ActivationLine.Phone_no__c = String.valueOf(Fokus_Subscription_list[i].FIX_NO__c);
				ActivationLine.Existing_SIM_number__c = Fokus_Subscription_list[i].EXISTING_SIM__c;
				ActivationLine.Max_Monthly_Data_Used__c = Fokus_Subscription_list[i].MAX_MONTHLY_DATA_CONSUMPTION_MB__c;
				ActivationLine.Avg_Monthly_Data_Used__c = Fokus_Subscription_list[i].AVG_MONTHLY_DATA_CONSUMPTION_MB__c;
				ActivationLine.Calls_from_DK_to_EU__c = Fokus_Subscription_list[i].CALLS_FROM_DK_TO_EUNB_MIN__c;
				if (string.isNotBlank(String.valueOf(Fokus_Subscription_list[i].SERVICE_CODE__c))) {
					strServices = Fokus_Subscription_list[i].SERVICE_CODE__c;
					lstServices = Fokus_Subscription_list[i].SERVICE_CODE__c.split(',');
				}

				//Touchpoint assignments
				for (string key : TouchpointProducts.keySet()) {
					if (strServices.indexOf(TouchpointProducts.get(key)) >= 0) {
						ActivationLine.put(key, true);
					}
				}
				system.debug('M2MPicklistProducts:' + M2MPicklistProducts);
				//Picklist VAS assignments
				if (String.isNotBlank(strServices)) {
					for (string key : M2MPicklistProducts.keySet()) {
						for (String M2MPicklistVal : M2MPicklistProducts.get(key)) {
							if (strServices.indexOf(M2MPicklistVal) >= 0) {
								ActivationLine.put(key, M2MPicklistVal);
								system.debug(key);
								system.debug(M2MPicklistVal);
							}
						}
					}

					//VAS assignments
					for (String service_record : lstServices) {
						if (columnNames.indexOf(service_record) >= 0) {
							service_name = 'VAS_' + service_record + '__c';
							ActivationLine.put(service_name, true);
						}
					}
				}

				ActivationLines.add(ActivationLine);
				ActivationLine = new Activation_line__c();
				i = i + 1;
			}

			update ActivationLines;
			system.debug(ActivationLines);

			//Create a notification
			CustomNotificationType notificationType = [
				SELECT Id, DeveloperName
				FROM CustomNotificationType
				WHERE DeveloperName = 'Case_notifications'
			];

			Messaging.CustomNotification notification = new Messaging.CustomNotification();
			notification.setTitle('Renewal Quote is ready');
			notification.setBody('The renewal quote is ready for you to review');

			notification.setNotificationTypeId(notificationType.Id);
			notification.setTargetId(quoteId);
			set<String> recipientsIds = new Set<String>{ UserInfo.getUserId() };
			notification.send(recipientsIds);

			//Update the Activation Progress status as Cancelled
			Activation__c RenewalActivation = new Activation__c();

			if (ActivationLinesSelected.size() > 0) {
				RenewalActivation.Id = ActivationLinesSelected[0].Activation__c;
				RenewalActivation.Activation_progress__c = 'Fulfilled';
				RenewalActivation.Actual_Delivery_date__c = Date.today();
				RenewalActivation.SLA_due_date__c = null;
				update RenewalActivation;
			}

			//Update Case status ac Case Close -- ActivationLinesSelected[0].Case__c
			Case RenewalCase = new Case();
			if (ActivationLinesSelected.size() > 0) {
				RenewalCase.Id = ActivationLinesSelected[0].Case__c;
				RenewalCase.Status = 'Close case';
				RenewalCase.Power_of_attorney__c = 'Received and attached to case';
				update RenewalCase;
			}
		} catch (Exception e) {
		}
	}
	public void finish(Database.BatchableContext BC) {
	}
}