force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <formula>Case__r.Quote__r.Invoice_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <inlineHelpText>Email to receive invoice</inlineHelpText>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Not_to_Activation__c.field-meta.xml
<CustomField>
    <fullName>Not_to_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</description>
    <inlineHelpText>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</inlineHelpText>
    <label>Don&apos;t send to Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Sales_type__c.field-meta.xml
<CustomField>
    <fullName>Sales_type__c</fullName>
    <description>Is this activation line a renewal of an already existing subscription, or is it new in Telia. Set by flow from Quote Line</description>
    <inlineHelpText>Is this activation line a renewal of an already existing subscription, or is it new in Telia?</inlineHelpText>
    <label>Sales type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/recordTypes/Voice_activation_line.recordType-meta.xml
<RecordType>
    <fullName>Voice_activation_line</fullName>
    <active>true</active>
    <description>Activation of a single voice item, e.g. one phone number</description>
    <label>Voice activation line</label>
</RecordType>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/address_required__c.field-meta.xml
<CustomField>
    <fullName>address_required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the sale of one of this product connected to exactly one address? Used for creating address lines on the quote and enter into the activation lines.</description>
    <inlineHelpText>Is the sale of one of this product connected to exactly one address?</inlineHelpText>
    <label>Address required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Activation_Create_IterableClass_Test.cls
@IsTest
public class Activation_Create_IterableClass_Test {

    @TestSetup
    static void dataPrepMethod(){
        Integer numOfAccounts = 1, numOfOppsPerAccount = 1, numOfQuotesPerOpp = 1, numOfQuoteLinesPerQuote = 2, numOfDiffProducts = 2, numOfNoActionProducts = 0;
        Account theAccount = testDataFactory.createSingleAccountForTests();
        List<Opportunity> listOfOpportunities = testDataFactory.createOpportunitiesForAccounts( numOfOppsPerAccount , new List<Account>{ theAccount } );
        List<SBQQ__Quote__c> listOfQuotes = testDataFactory.createQuotesForOpps( numOfQuotesPerOpp, listOfOpportunities );
        listOfOpportunities = [SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c FROM Opportunity];
        List<Case> theRelatedToOppCases = testDataFactory.createCasesForOpportunitiesAndAssignThem( listOfOpportunities ); // Should be called after Quote creation
        listOfOpportunities = [SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c FROM Opportunity];
        List<SBQQ__QuoteLine__c> listOfQuoteLines = testDataFactory.createQuoteLineRecordsForQuote( numOfQuoteLinesPerQuote, listOfQuotes, numOfDiffProducts, numOfNoActionProducts,true );
        listOfQuoteLines = [SELECT Id, Activation_Record_Type__c, SBQQ__Quote__c,SBQQ__Quantity__c,SBQQ__Product__c,Sales_Type__c FROM SBQQ__QuoteLine__c];
       
           

    }

    @IsTest
    static void querySelectorTest(){

        List<SBQQ__Quote__c> quotesList = [SELECT Id FROM SBQQ__Quote__c];
        List<Id> quoteIdsList = new List<Id>();
        
        quoteIdsList.add(quotesList[0].Id);
       
        List<Case> caseListMain = [select id from case limit 1 ];
        caseListMain[0].Quote__c = quotesList[0].Id;
        update caseListMain[0];
        
        List<Case> caseList = [select id from case where Quote__c =:quotesList[0].Id ];
       
        Product2 pr = new Product2(ProductAPI_Telia_Product_Id__c='CORFRI10G', name = 'Corporate Fri tale EU 10 GB',
                                           SBQQ__SubscriptionType__c = 'Renewable', isActive=true, Activation_Record_Type__c ='Voice',
                                            activate_with_other_products__c = false);
        insert pr;
        
        Product2 pr2 = new Product2(ProductAPI_Telia_Product_Id__c='CORFRI20G', name = 'Home office',
                                           SBQQ__SubscriptionType__c = 'Renewable', isActive=true, 
                                            Activation_Record_Type__c ='Home office',
                                            activate_with_other_products__c = false, ProductCode = '3100',
                                            address_required__c = true);
        insert pr2;
        
        List<SBQQ__QuoteLine__c> quoteLinesList = [SELECT Id,SBQQ__Product__c FROM SBQQ__QuoteLine__c where SBQQ__Quote__c =: quotesList[0].Id ];
        quoteLinesList[0].Additional_Quantity__c = 3;
        quoteLinesList[0].SBQQ__Product__c = pr.Id;
        quoteLinesList[0].SBQQ__SegmentIndex__c =1;
        quoteLinesList[0].Address_filled_on_activation_lines__c = false;
        update quoteLinesList[0];
        
        quoteLinesList[1].Additional_Quantity__c = 3;
        quoteLinesList[1].SBQQ__Product__c = pr2.Id;
        quoteLinesList[1].SBQQ__SegmentIndex__c =1;
        quoteLinesList[1].Address_filled_on_activation_lines__c = false;
        update quoteLinesList[1];
        
        Activation__c acti = new Activation__c(Case__c = caseList[0].Id,
                                               RecordTypeId =  Schema.sObjectType.Activation__c.getRecordTypeInfosByName().get('Voice activation').getRecordTypeId());
        insert acti;
        
       
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Activation_line__c' and developername = 'Voice_activation_line'].Id;


        Activation_line__c actiline = new Activation_line__c( Activation__c = acti.Id, Case__c = caseList[0].Id, Quote_line__c = quoteLinesList[0].Id,
                                                                    RecordTypeId=strRecordTypeId, Manual_Product__c = quoteLinesList[0].SBQQ__Product__c,
                                                                     Invoice_Email__c='tuba@tuba.com', Not_to_Activation__c = false);
        insert actiline; 
      

         Test.startTest();
        
         Activation_Create_Iterable ProcessBatch = new Activation_Create_Iterable();
          ProcessBatch.recordId = quoteIdsList;
          ID batchprocessid = Database.executeBatch(ProcessBatch);
        
        
        Test.stopTest();
   }
    }