force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <description>Used when posting data via the Order API to ensure the subscriptions are related to the correct BAN (Billing Account Number)</description>
    <label>BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <inlineHelpText>If this is a new customer then an indication of different invoice units is needed by adding 1, 2, 3 etc - if billing units are to be in a hierarchy with more than 1 level under Root then indicate the parent BAN in the above &apos;Parent BAN&apos; field</inlineHelpText>
    <label>BAN</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Not_to_Activation__c.field-meta.xml
<CustomField>
    <fullName>Not_to_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</description>
    <inlineHelpText>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</inlineHelpText>
    <label>Don&apos;t send to Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF( ISBLANK(Order_Product__r.PricebookEntry.Product2.Name) , Manual_Product__r.Name , Order_Product__r.PricebookEntry.Product2.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product name from Telia&apos;s B2B product portfolio</inlineHelpText>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Bruger__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Bruger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether Touchpoint Bruger is a active SOC or a future SOC.</inlineHelpText>
    <label>Touchpoint Bruger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Receptionist__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Receptionist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Receptionist is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Receptionist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Softphone__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Softphone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Softphone is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Softphone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Statistik__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Statistik__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Statistik is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Statistik</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/BAN__c.field-meta.xml
<CustomField>
    <fullName>BAN__c</fullName>
    <description>The billing account number for the account related to this case.</description>
    <inlineHelpText>Use the billing account number to correctly bill the customer for the activated product(s).</inlineHelpText>
    <label>BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>In order to relate to relevant info on product (eg product sku for activation of UC solution)</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Root_BAN__c.field-meta.xml
<CustomField>
    <fullName>Root_BAN__c</fullName>
    <description>The root billing account number for the account related to this activation case.</description>
    <inlineHelpText>The root billing account number for the account related to this activation case.</inlineHelpText>
    <label>Root BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Validation_Check_Result__c.field-meta.xml
<CustomField>
    <fullName>Validation_Check_Result__c</fullName>
    <description>Calculates if Delivery address differs in ExtraDatacard activation lines and if VAS selection is not completed yet</description>
    <inlineHelpText>Calculates if Delivery address differs in ExtraDatacard activation lines and if VAS selection is not completed yet</inlineHelpText>
    <label>Validation_Check_Result</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for linking an order to a case. Usewd in the activation process where the case object is used to run the process</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Requires_Activation_Check__c.field-meta.xml
<CustomField>
    <fullName>Requires_Activation_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field is used to include/exclude the product from the activation check calculations</description>
    <inlineHelpText>The field is used to include/exclude the product from the activation check calculations</inlineHelpText>
    <label>Requires Activation Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Activation_check.cls
public class Activation_check {
	private static final String ERROR_ORIGIN = 'Apex';
	private static final String ERROR_ADDITIONAL_INFO = 'Activation_check';

	private static ErrorLogging errorLogging = new ErrorLogging(ERROR_ORIGIN);

	public string resultText { get; set; }
	public string recordId;
	Activation__c Activation_record;
	String QuoteId;

	public map<String, decimal> ActivationLineAvailability(string recordId) {
		try {
			list<Product2> ProductInfoList = [
				SELECT Name, Id, ProductAPI_Telia_Product_Id__c
				FROM Product2
				WHERE IsActive = TRUE AND Requires_Activation_Check__c = TRUE
			];
			Map<String, String> ALLProductNames = new Map<String, String>();
			//Name,ProductId
			for (Product2 pr : ProductInfoList) {
				ALLProductNames.put(pr.Name, pr.Id);
			}

			List<Activation__c> Activation_records = [
				SELECT Id, Case__r.Root_BAN__c, Case__r.Quote__c
				FROM Activation__c
				WHERE Id = :recordId
				LIMIT 1
			];
			if (Activation_records.size() <= 0) {
				resultText = 'Activation details can not be found with the Id value from:' + recordId;
				return null;
			} else {
				Activation_record = Activation_records[0];
			}

			list<Product2> VASProductInfoList = [
				SELECT Name, Id, ProductAPI_Telia_Product_Id__c
				FROM Product2
				WHERE IsActive = TRUE AND activate_with_other_products__c = TRUE AND Requires_Activation_Check__c = TRUE
			];
			Map<String, String> VasProducts = new Map<String, String>();
			//TeliaProductId,Id

			for (Product2 prVas : VASProductInfoList) {
				VasProducts.put(prVas.ProductAPI_Telia_Product_Id__c, prVas.Id);
			}

			//Query the VAS services list
			Schema.DescribeSObjectResult activationline_desc = Activation_line__c.sObjectType.getDescribe();

			Map<String, Schema.SObjectField> activationline_fields = activationline_desc.fields.getMap();
			Map<String, String> Vasfields = new Map<String, String>();
			String columnNames = 'Id';

			for (Schema.sObjectField fld : activationline_fields.values()) {
				if (string.valueof(fld).indexOf('VAS_') == 0) {
					columnNames = columnNames + ',' + fld.getDescribe().getName();
					Vasfields.put(fld.getDescribe().getName(), fld.getDescribe().getType().name().toupperCase());
				}
			}
			String ProductId;
			string VasName;
			//Query the ActivationLines
			List<Activation_line__c> Activation_line_list = Database.query(
				'SELECT ' +
					columnNames +
					',name, Product__c, Case__c, First_name__c, BAN__c , Manual_Product__r.Name , ' +
					' Manual_Product__r.ProductAPI_Telia_Product_Id__c, Manual_Product__c,  ' +
					' Touchpoint_Bruger__c, Touchpoint_Receptionist__c ,Touchpoint_Softphone__c, Touchpoint_Statistik__c ' +
					' FROM Activation_line__c WHERE Activation__c= :recordId and Not_to_Activation__c = false ' +
					' AND Manual_Product__r.Requires_Activation_Check__c = true  order by BAN__c'
			);

			//Loop through the activation lines
			Map<String, integer> ActivationLineProducts = new Map<String, integer>();
			integer quantity;
			boolean added = false;
			for (Activation_line__c ActivationLineData : Activation_line_list) {
				//START OF LOOPING ACTIVATION LINES
				//
				ProductId = ActivationLineData.Manual_Product__c;
				added = false;
				for (string key : ActivationLineProducts.keySet()) {
					if (key == ProductId) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
						added = true;
						break;
					}
				}
				if (added == false) {
					ActivationLineProducts.put(ProductId, 1);
				}

				added = false;

				//Touchpoint section
				if (ActivationLineData.Touchpoint_Bruger__c) {
					ProductId = ALLProductNames.get('Touchpoint Bruger');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Receptionist__c) {
					ProductId = ALLProductNames.get('Touchpoint Receptionist');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Statistik__c) {
					ProductId = ALLProductNames.get('Touchpoint Statistik');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Softphone__c) {
					ProductId = ALLProductNames.get('Touchpoint Softphone');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}

				//VAS services section
				boolean VASExistInQuoteDetails = false;
				for (string key : Vasfields.keySet()) {
					if (Vasfields.get(key) == 'BOOLEAN' && ActivationLineData.get(key) == true) {
						VasName = key.remove('VAS_').remove('__c');
						for (string vasTeliaProductId : VasProducts.keySet()) {
							if (VasName == vasTeliaProductId) {
								ProductId = VasProducts.get(vasTeliaProductId);
								break;
							}
						}
						system.debug('boolean VAS to be added ' + VasName);

						for (string vaskey : ActivationLineProducts.keySet()) {
							if (ProductId == vaskey) {
								quantity = ActivationLineProducts.get(ProductId) + 1;
								ActivationLineProducts.remove(ProductId);
								ActivationLineProducts.put(ProductId, quantity);
								added = true;
								break;
							}
						}
						if (added == false) {
							ActivationLineProducts.put(ProductId, 1);
						}
					}
					added = false;

					if (Vasfields.get(key) == 'INTEGER' && integer.valueof(ActivationLineData.get(key)) > 0) {
						system.debug('integer VAS to be added (not implemented) ' + VasName);
					}
					if ((Vasfields.get(key) == 'PICKLIST' || Vasfields.get(key) == 'STRING') && ActivationLineData.get(key) != null) {
						VasName = String.Valueof(ActivationLineData.get(key));
						system.debug('picklist or string VAS to be added ' + VasName);

						for (string vasTeliaProductId : VasProducts.keySet()) {
							if (VasName == vasTeliaProductId) {
								ProductId = VasProducts.get(vasTeliaProductId);
								break;
							}
						}
						for (string vasPickkey : ActivationLineProducts.keySet()) {
							if (ProductId == vasPickkey) {
								quantity = ActivationLineProducts.get(ProductId) + 1;
								ActivationLineProducts.remove(ProductId);
								ActivationLineProducts.put(ProductId, quantity);
								added = true;
								break;
							}
						}
						if (added == false) {
							ActivationLineProducts.put(ProductId, 1);
						}
					}
					added = false;
				}
			} //END OF LOOPING ACTIVATION LINES
			//system.debug(ActivationLineProducts);
			return ActivationLineProducts;
		} catch (Exception e) {
			System.debug('Error occured : ' + e.getMessage());
			errorLogging.addError('Error occured : ' + e.getMessage(), ERROR_ADDITIONAL_INFO);
			return null;
		} finally {
			errorLogging.logErrors();
		}
	}

	public map<String, integer> QuoteAvailability(string recordId) {
		try {
			List<Activation__c> Activation_records = [
				SELECT Id, Case__r.Root_BAN__c, Case__r.Quote__c
				FROM Activation__c
				WHERE Id = :recordId
				LIMIT 1
			];
			if (Activation_records.size() <= 0) {
				resultText = 'Activation details can not be found with the Id value from:' + recordId;
				return null;
			} else {
				Activation_record = Activation_records[0];
			}

			QuoteId = Activation_record.Case__r.Quote__c;

			if (String.isEmpty(QuoteId)) {
				resultText = 'Required field missing on Case: Quote';
				return null;
			}

			list<SBQQ__QuoteLine__c> QuoteLineInfoList = [
				SELECT
					SBQQ__ProductName__c,
					SBQQ__Product__c,
					SBQQ__Product__r.ProductAPI_Telia_Product_Id__c,
					SBQQ__Product__r.Activation_Record_Type__c,
					SBQQ__Quantity__c
				FROM SBQQ__QuoteLine__c
				WHERE SBQQ__Quote__c = :QuoteId AND SBQQ__Product__r.Requires_Activation_Check__c = TRUE
			];

			Map<String, integer> QuoteProducts = new Map<String, integer>();
			//ProductId, Quantity

			for (SBQQ__QuoteLine__c ql : QuoteLineInfoList) {
				QuoteProducts.put(ql.SBQQ__Product__c, Integer.valueOf(ql.SBQQ__Quantity__c));
			}
			return QuoteProducts;
		} catch (Exception e) {
			System.debug('Error occured : ' + e.getMessage());
			errorLogging.addError('Error occured : ' + e.getMessage(), ERROR_ADDITIONAL_INFO);
			return null;
		} finally {
			errorLogging.logErrors();
		}
	}

	@InvocableMethod
	public static void PortalEntryValidation(list<id> recordId) {
		String CaseId;
		String QuoteId;
		String VASresult = '';
		String EkstraDataresult = '';
		Case updateCase = new Case();
		try {
			List<Activation__c> Activation_records = [
				SELECT Id, Case__c, Case__r.Quote__c
				FROM Activation__c
				WHERE Id IN :recordId
				LIMIT 1
			];
			CaseId = Activation_records[0].Case__c;
			QuoteId = Activation_records[0].Case__r.Quote__c;

			list<Product2> ProductInfoList = [
				SELECT Name, Id, ProductAPI_Telia_Product_Id__c
				FROM Product2
				WHERE IsActive = TRUE AND Requires_Activation_Check__c = TRUE
			];
			Map<String, String> ALLProducts = new Map<String, String>();
			//ProductId,Name
			Map<String, String> ALLProductNames = new Map<String, String>();
			//Name,ProductId
			for (Product2 pr : ProductInfoList) {
				ALLProducts.put(pr.Id, pr.Name);
				ALLProductNames.put(pr.Name, pr.Id);
			}

			list<Product2> VASProductInfoList = [
				SELECT Name, Id, ProductAPI_Telia_Product_Id__c
				FROM Product2
				WHERE IsActive = TRUE AND activate_with_other_products__c = TRUE AND Requires_Activation_Check__c = TRUE
			];
			Map<String, String> VasProducts = new Map<String, String>();
			//TeliaProductId,Id

			for (Product2 prVas : VASProductInfoList) {
				VasProducts.put(prVas.ProductAPI_Telia_Product_Id__c, prVas.Id);
			}

			//Query the VAS products in the Quote lines
			list<SBQQ__QuoteLine__c> QuoteLineInfoList = [
				SELECT
					SBQQ__ProductName__c,
					SBQQ__Product__c,
					SBQQ__Product__r.ProductAPI_Telia_Product_Id__c,
					SBQQ__Product__r.Activation_Record_Type__c,
					SBQQ__Quantity__c
				FROM SBQQ__QuoteLine__c
				WHERE
					SBQQ__Quote__c = :QuoteId
					AND SBQQ__Product__r.Requires_Activation_Check__c = TRUE
					AND SBQQ__Product__r.activate_with_other_products__c = TRUE
			];

			Map<String, integer> QuoteProducts = new Map<String, integer>();
			//ProductId, Quantity

			for (SBQQ__QuoteLine__c ql : QuoteLineInfoList) {
				QuoteProducts.put(ql.SBQQ__Product__c, Integer.valueOf(ql.SBQQ__Quantity__c));
			}

			//Query the VAS services list
			Schema.DescribeSObjectResult activationline_desc = Activation_line__c.sObjectType.getDescribe();

			Map<String, Schema.SObjectField> activationline_fields = activationline_desc.fields.getMap();
			Map<String, String> Vasfields = new Map<String, String>();
			String columnNames = 'Id';

			for (Schema.sObjectField fld : activationline_fields.values()) {
				if (string.valueof(fld).indexOf('VAS_') == 0) {
					columnNames = columnNames + ',' + fld.getDescribe().getName();
					Vasfields.put(fld.getDescribe().getName(), fld.getDescribe().getType().name().toupperCase());
				}
			}

			String ProductId;
			String VasName;

			//Query the ActivationLines
			List<Activation_line__c> Activation_line_list = Database.query(
				'SELECT ' +
					columnNames +
					',name, Product__c, Case__c, First_name__c, BAN__c , Manual_Product__r.Name , ' +
					' Manual_Product__r.ProductAPI_Telia_Product_Id__c, Manual_Product__c,  ' +
					' Touchpoint_Bruger__c, Touchpoint_Receptionist__c ,Touchpoint_Softphone__c, Touchpoint_Statistik__c  ' +
					' FROM Activation_line__c WHERE Activation__c in:recordId and Not_to_Activation__c = false ' +
					' AND Manual_Product__r.Requires_Activation_Check__c = true  order by BAN__c'
			);

			//Loop through the activation lines
			Map<String, integer> ActivationLineProducts = new Map<String, integer>();
			integer quantity;
			boolean added = false;
			for (Activation_line__c ActivationLineData : Activation_line_list) {
				//START OF LOOPING ACTIVATION LINES
				//
				//Touchpoint section
				if (ActivationLineData.Touchpoint_Bruger__c) {
					ProductId = ALLProductNames.get('Touchpoint Bruger');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Receptionist__c) {
					ProductId = ALLProductNames.get('Touchpoint Receptionist');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Statistik__c) {
					ProductId = ALLProductNames.get('Touchpoint Statistik');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}
				if (ActivationLineData.Touchpoint_Softphone__c) {
					ProductId = ALLProductNames.get('Touchpoint Softphone');
					if (ActivationLineProducts.get(ProductId) > 0) {
						quantity = ActivationLineProducts.get(ProductId) + 1;
						ActivationLineProducts.remove(ProductId);
						ActivationLineProducts.put(ProductId, quantity);
					} else {
						ActivationLineProducts.put(ProductId, 1);
					}
				}

				//VAS services section
				boolean VASExistInQuoteDetails = false;
				for (string key : Vasfields.keySet()) {
					if (Vasfields.get(key) == 'BOOLEAN' && ActivationLineData.get(key) == true) {
						VasName = key.remove('VAS_').remove('__c');
						for (string vasTeliaProductId : VasProducts.keySet()) {
							if (VasName == vasTeliaProductId) {
								ProductId = VasProducts.get(vasTeliaProductId);
								break;
							}
						}
						system.debug('boolean VAS to be added ' + VasName);

						for (string vaskey : ActivationLineProducts.keySet()) {
							if (ProductId == vaskey) {
								quantity = ActivationLineProducts.get(ProductId) + 1;
								ActivationLineProducts.remove(ProductId);
								ActivationLineProducts.put(ProductId, quantity);
								added = true;
								break;
							}
						}
						if (added == false) {
							ActivationLineProducts.put(ProductId, 1);
						}
					}
					added = false;

					if (Vasfields.get(key) == 'INTEGER' && integer.valueof(ActivationLineData.get(key)) > 0) {
						system.debug('integer VAS to be added (not implemented) ' + VasName);
					}
					if ((Vasfields.get(key) == 'PICKLIST' || Vasfields.get(key) == 'STRING') && ActivationLineData.get(key) != null) {
						VasName = String.Valueof(ActivationLineData.get(key));
						system.debug('picklist or string VAS to be added ' + VasName);

						for (string vasTeliaProductId : VasProducts.keySet()) {
							if (VasName == vasTeliaProductId) {
								ProductId = VasProducts.get(vasTeliaProductId);
								break;
							}
						}
						for (string vasPickkey : ActivationLineProducts.keySet()) {
							if (ProductId == vasPickkey) {
								quantity = ActivationLineProducts.get(ProductId) + 1;
								ActivationLineProducts.remove(ProductId);
								ActivationLineProducts.put(ProductId, quantity);
								added = true;
								break;
							}
						}
						if (added == false) {
							ActivationLineProducts.put(ProductId, 1);
						}
					}
					added = false;
				}
			} //END OF LOOPING ACTIVATION LINES

			//Vær opmærksom på at kunden vil aktivere færre VAS end aftalt
			integer i;

			for (String keyId : QuoteProducts.Keyset()) {
				//if Activation lines does not have that key
				if (!ActivationLineProducts.keyset().contains(keyId)) {
					VASresult = VASresult + '<font style="color:blue;">Available ' + ALLProducts.get(keyId) + ':';
					VASresult = VASresult + String.valueOf(QuoteProducts.get(keyId)) + '</font> <br/>';
				} else {
					if (QuoteProducts.get(keyId) != ActivationLineProducts.get(keyId)) {
						i = Integer.valueOf(QuoteProducts.get(keyId)) - Integer.valueOf(ActivationLineProducts.get(keyId));
						if (i > 0) {
							VASresult = VASresult + '<font style="color:blue;">Available ' + ALLProducts.get(keyId) + ':';
							VASresult = VASresult + String.valueof(i) + '</font> <br/>';
						}
					}
				}
			} //for

			if (String.isNotBlank(VASresult)) {
				VASresult = '<font style="color:red;">Vær opmærksom på at kunden vil aktivere færre VAS end aftalt' + '</font><br/> ' + VASresult;
				updateCase.Id = CaseId;
				updateCase.Validation_Check_Result__c = VASresult;
				update updateCase;
			}
		} catch (Exception e) {
			System.debug('Error Occured : ' + e.getMessage());
			errorLogging.addError('Error occured : ' + e.getMessage(), ERROR_ADDITIONAL_INFO);
		} finally {
			errorLogging.logErrors();
		}
	}
}