force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Product_Group__c</fullName>
    <label>Delivery Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Onboarding_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Configuration__c</fullName>
    <description>Various settings for the onboarding flows, e.g., indicating where a product should be displayed and more.</description>
    <label>Onboarding Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ShowInValueAddedServicesSummary</fullName>
                <label>Show in ValueAddedServices Summary</label>
            </value>
            <value>
                <fullName>ShowInSubscriptionSummary</fullName>
                <label>Show in Subscription Summary</label>
            </value>
            <value>
                <fullName>ShowInBillingAccountSummary</fullName>
                <label>Show in BillingAccount Summary</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Requires_Activation_Check__c.field-meta.xml
<CustomField>
    <fullName>Requires_Activation_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field is used to include/exclude the product from the activation check calculations</description>
    <inlineHelpText>The field is used to include/exclude the product from the activation check calculations</inlineHelpText>
    <label>Requires Activation Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteLineSelectorTest.cls
@IsTest
public with sharing class QuoteLineSelectorTest {
	private static final String CVR = '12345678';
	
	//@TestSetup
	static void makeData() {
		Account acct = testDataFactory.createCVRAccountWithBillingAddress(CVR);
		List<Opportunity> listOfOpportunities = testDataFactory.createOpportunitiesForAccounts(1, new List<Account>{ acct });

		Integer numOfAccounts = 1,
			numOfOppsPerAccount = 1,
			numOfQuotesPerOpp = 1,
			numOfQuoteLinesPerQuote = 2,
			numOfDiffProducts = 2,
			numOfNoActionProducts = 0;

		List<SBQQ__Quote__c> listOfQuotes = testDataFactory.createQuotesForOpps(numOfQuotesPerOpp, listOfOpportunities);
		listOfOpportunities = [SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c FROM Opportunity];
		List<Case> theRelatedToOppCases = testDataFactory.createCasesForOpportunitiesAndAssignThem(listOfOpportunities); // Should be called after Quote creation
		listOfOpportunities = [SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c FROM Opportunity];
		List<SBQQ__QuoteLine__c> listOfQuoteLines = testDataFactory.createQuoteLineRecordsForQuote(
			numOfQuoteLinesPerQuote,
			listOfQuotes,
			numOfDiffProducts,
			numOfNoActionProducts,
			true
		);

		Product2 pr = new Product2(
			ProductAPI_Telia_Product_Id__c = 'HBOBTB4',
			name = 'HBO Max',
			SBQQ__SubscriptionType__c = 'Renewable',
			isActive = true,
			Activation_Record_Type__c = 'Voice',
			activate_with_other_products__c = true,
			Requires_Activation_Check__c = true,
			Delivery_Product_Group__c = 'Voice',
			Onboarding_Configuration__c = 'ShowInValueAddedServicesSummary'	
		);
		insert pr;

		Activation__c activation = new Activation__c(
			Case__c = theRelatedToOppCases[0].Id,
			RecordTypeId = Schema.sObjectType.Activation__c.getRecordTypeInfosByName().get('Voice activation').getRecordTypeId()
		);
		insert activation;

		for (SBQQ__QuoteLine__c quoteLine : listOfQuoteLines) {
			quoteLine.SBQQ__Product__c = pr.Id;
			quoteLine.Activation__c = activation.Id;
		}
		update listOfQuoteLines;
	}

	@IsTest
	static void getValueAddedServiceProductByQuote_quoteWithLines_returnsQuoteLines() {
		makeData();

		//ARRANGE
		SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

		//ACT
		Test.startTest();
		List<SBQQ__QuoteLine__c> quotelines = QuoteLineSelector.getValueAddedServiceProductByQuote(quote.Id);
		Test.stopTest();

		//ASSERT
		Assert.isTrue(quotelines.size() > 0);
	}

	@IsTest
	static void getValueAddedServiceProductByQuote_invalidQuote_returnsNoQuoteLines() {
		makeData();

		//ARRANGE

		//ACT
		Test.startTest();
		List<SBQQ__QuoteLine__c> quotelinesNullQuote = QuoteLineSelector.getValueAddedServiceProductByQuote(null);
		List<SBQQ__QuoteLine__c> quotelinesEmptyStringQuote = QuoteLineSelector.getValueAddedServiceProductByQuote('');
		List<SBQQ__QuoteLine__c> quotelinesNonExistingQuote = QuoteLineSelector.getValueAddedServiceProductByQuote('123');
		Test.stopTest();

		//ASSERT
		Assert.isTrue(quotelinesNullQuote.size() == 0);
		Assert.isTrue(quotelinesEmptyStringQuote.size() == 0);
		Assert.isTrue(quotelinesNonExistingQuote.size() == 0);
	}

	@IsTest
	static void getVASByActivationAndQuote_validActivation_returnsQuoteLines() {
		makeData();

		//ARRANGE
		Activation__c activation = [SELECT Id FROM Activation__c LIMIT 1];

		//ACT
		Test.startTest();
		List<SBQQ__QuoteLine__c> quotelines = QuoteLineSelector.getVASByActivationAndQuote(activation.Id);
		Test.stopTest();

		//ASSERT
		Assert.isTrue(quotelines.size() > 0);
	}

	@IsTest
	static void getVasWithOnboardingConfiguration_validQuoteLines_returnsQuoteLines() {
		makeData();

		//ARRANGE
		SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

		List<SBQQ__QuoteLine__c> quoteLines = QuoteLineSelector.getValueAddedServiceProductByQuote(quote.Id);

		//ACT
		Test.startTest();
		List<SBQQ__QuoteLine__c> quoteLinesWithOnboarding = QuoteLineSelector.getVasWithOnboardingConfiguration(quoteLines);
		Test.stopTest();

		//ASSERT
		Assert.isTrue(quoteLinesWithOnboarding.size() > 0);
	}

	@isTest
    static void getDeliveryProductGroups_validQuoteAndTypes_returnsQuoteLines() {
		makeData();
		
        //ARRANGE
		SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Set<Id> quoteIds = new Set<Id>{testQuote.Id};
        Set<String> existingTypes = new Set<String>{'Existing Group'};

		//ACT
        Test.startTest();
        List<SBQQ__QuoteLine__c> quotelines = QuoteLineSelector.getDeliveryProductGroups(quoteIds, existingTypes);
        Test.stopTest();

		//ASSERT
		Assert.isTrue(quotelines.size() > 0, 'Expected to have at least one quote line');
        Assert.areEqual('Voice', quotelines[0].SBQQ__Product__r.Delivery_Product_Group__c, 'Incorrect product group retrieved');
    }

	@IsTest
    static void testGetQuoteLinesByOpportunityIds() {
		makeData();
		
        // ARRANGE
		Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([SELECT Id FROM Opportunity]);

		// ACT
        Test.startTest();

		List<SBQQ__QuoteLine__c> quoteLines = QuoteLineSelector.getQuoteLinesByOpportunityIds(
			opportunityMap.keySet()
		);

        Test.stopTest();

		// ASSERT
		Assert.areEqual(2, quoteLines.size(), 'Expected 2 Quote Lines');
		Assert.areEqual(1, opportunityMap.size(), 'Expected 1 Opportunity in map');

		for (SBQQ__QuoteLine__c quoteLine : quoteLines) {			
			Assert.isNotNull(quoteLine.Activation__c, 'Expected Activation field to be populated');
			Assert.isTrue(
				opportunityMap.keySet().contains(quoteLine.SBQQ__Quote__r.SBQQ__Opportunity2__r.Id), 
				'Opportunity Id is incorrect'
			);
		}
	}

}