force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UploadTool.cls
public with sharing class UploadTool {
    @AuraEnabled(cacheable=false)
    public static void uploadLines(String jsonData, String actId, Boolean insertLinesWithoutId) {

        List<Activation_Line__c> als = (List<Activation_Line__c>)JSON.deserialize(jsonData, List<Activation_Line__c>.class);
        List<Activation_Line__c> alsWithId = new List<Activation_Line__c>();
        List<Activation_Line__c> alsWithoutId = new List<Activation_Line__c>();

        for (Activation_Line__c al : als) {
            if (String.isBlank(al.Id)) {
                al.Activation__c = actId;
                alsWithoutId.add(al);
            } else {
                alsWithId.add(al);
            }
        }

        try {
            if (insertLinesWithoutId == null || insertLinesWithoutId == true) {
                insert alsWithoutId;
            }
            update alsWithId;
        } catch (Exception e) {
            System.debug(e);
        }
        
    }
}