force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDF_ActivationUtils.cls
@IsTest
public with sharing class TDF_ActivationUtils {
    public static List<Activation__c> createActivationHeadersForQuoteLines(List<SBQQ__QuoteLine__c> listOfQuoteLines, List<Opportunity> listOfRelatedOpportunities) {
		Map<SBQQ__QuoteLine__c, Activation__c> mapOfQuoteLineToActivation = new Map<SBQQ__QuoteLine__c, Activation__c>();
        List<Activation__c> result = new List<Activation__c>();
		Map<Id, Opportunity> quoteIdToParentOpportunity = new Map<Id, Opportunity>();
		for (Opportunity singleOpp : listOfRelatedOpportunities) {
			quoteIdToParentOpportunity.put(singleOpp.SBQQ__PrimaryQuote__c, singleOpp);
		}
		List<String> activationTypeList = new List<String>();
		for (SBQQ__QuoteLine__c singleLine : listOfQuoteLines) {
			if ((!activationTypeList.contains(singleLine.Activation_Record_Type__c)) && quoteIdToParentOpportunity.containsKey(singleLine.SBQQ__Quote__c)) {
				String tmpName = singleLine.Activation_Record_Type__c;
				Id tmpQuote = singleLine.SBQQ__Quote__c;
				Opportunity tmpOpp = quoteIdToParentOpportunity.get(singleLine.SBQQ__Quote__c);
				Id tmpCase = tmpOpp.Case__c; //casen er på account og ikke opp?
				String tmpActivationRecordType = singleLine.Activation_Record_Type__c + ' activation';
                String noActivationNeeded = TDF_Constants.NO_ACTIVATION_NEEDED;

                if (!tmpActivationRecordType.contains(noActivationNeeded)){
                    Id tmpRecordTypeId = Schema.sObjectType.Activation__c.getRecordTypeInfosByName()
                    .get(tmpActivationRecordType)
                    .getRecordTypeId();

                    try{
                        Activation__c newActivation = new Activation__c(
                            Name = tmpName,
                            Case__c = tmpCase,
                            RecordTypeId = tmpRecordTypeId  
                        );

                        mapOfQuoteLineToActivation.put(singleLine, newActivation);
                    }
                    catch (Exception ex){
                        //System.debug('Error creating Activation Header.  Line: ' + ex);
                    }
                }
			}
		}

        insert mapOfQuoteLineToActivation.values();

        for (SBQQ__QuoteLine__c singleLine :listOfQuoteLines) {
            if (mapOfQuoteLineToActivation.containsKey(singleLine)) {
                singleLine.Activation__c = mapOfQuoteLineToActivation.get(singleLine).Id;
            }
        }

        update listOfQuoteLines;

		return result;
	}
}