force-app/main/default/objects/Contract/fields/Data_Part_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Data_Part_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US412 - Contracts migration.</description>
    <inlineHelpText>During the contract migration, some contracts had several end dates and needed to be split into several subcontracts (mobile, data, fastnet). If this field is checked, it indicates that this contract is the mobile part of the contract.</inlineHelpText>
    <label>Data Part of Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Fastnet_Part_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Fastnet_Part_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US412 - Contract Migration.</description>
    <inlineHelpText>During the contract migration, some contracts had several end dates and needed to be split into several subcontracts (mobile, data, fastnet). If this field is checked, it indicates that this contract is the mobile part of the contract.</inlineHelpText>
    <label>Fastnet Part of Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Migrated_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migrated_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US412 - Contract Migration. Indicated if the contract was migrated.

This contract was migrated (created before Salesforce CPQ then imported to the system). Please note that the migrated contracts had several end dates and needed to be split into several subcontracts (mobile, data, fastnet). The field &quot;Contract Type (if Migrated)&quot; indicates which subcontract. The fields &quot;Link to Original Contract&quot; contain the link to the original full contract (available in both X folder and Sharepoint). The field &quot;Products&quot; contains the Products for the whole contract. To see the other subcontracts, please go to the Account and look at the Contracts related list.</description>
    <inlineHelpText>Indicates if the contract was migrated. Contracts with several end dates were split in several subcontracts (mobile, fastnet, data), &quot;Contract Type (if Migrated)&quot; indicates which subcontract it is. Full contract can be found in &quot;Link to Original Contract&quot;</inlineHelpText>
    <label>Migrated Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Mobile_Part_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Part_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US412 - Contract Migration.</description>
    <inlineHelpText>During the contract migration, some contracts had several end dates and needed to be split into several subcontracts (mobile, data, fastnet). If this field is checked, it indicates that this contract is the mobile part of the contract.</inlineHelpText>
    <label>Mobile Part of Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Contract_value__c.field-meta.xml
<CustomField>
    <fullName>Total_Contract_value__c</fullName>
    <description>User Story ID: 46</description>
    <inlineHelpText>Total Contract value with discounts based on Subscriptions in Contract</inlineHelpText>
    <label>Total Contract Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Installation_Address__c/Installation_Address__c.object-meta.xml
<CustomObject>
    <description>Installation address for Wholesale orders</description>
    <label>Installation Address</label>
    <nameField>
        <displayFormat>IA-{00000000}</displayFormat>
        <label>Installation Address No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Address__c/fields/Installation_Address__c.field-meta.xml
<CustomField>
    <fullName>Installation_Address__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Installation_Address__c/&quot;&amp;Id&amp;&quot;/view&quot;,
IF(ISBLANK(Secondary_Street__c), 
    IF(ISBLANK(Primary_Street__c), Name ,Primary_Street__c &amp; &quot; &quot; &amp;  Primary_Street_Number__c ),
     Primary_Street__c &amp;&quot; to &quot;&amp; Secondary_Street__c),&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <description>User story ID: 94</description>
    <inlineHelpText>Specify here which products are included in this opportunity</inlineHelpText>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/Subscription_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Detail</label>
    <nameField>
        <displayFormat>SLD-{000000}</displayFormat>
        <label>Subscription Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Calls_from_DK_to_EU_MIN__c.field-meta.xml
<CustomField>
    <fullName>Calls_from_DK_to_EU_MIN__c</fullName>
    <label>Calls from DK to EU (MIN)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Ekstra_Data_SIM_number__c.field-meta.xml
<CustomField>
    <fullName>Ekstra_Data_SIM_number__c</fullName>
    <label>Ekstra Data SIM number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Fixed_no__c.field-meta.xml
<CustomField>
    <fullName>Fixed_no__c</fullName>
    <label>Fixed no.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Fokus_SOC__c.field-meta.xml
<CustomField>
    <fullName>Fokus_SOC__c</fullName>
    <description>The value of the FOKUS SOC code as it is</description>
    <label>Fokus_SOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Installation_address__c.field-meta.xml
<CustomField>
    <fullName>Installation_address__c</fullName>
    <label>Installation address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/INSTANCE_KEY__c.field-meta.xml
<CustomField>
    <fullName>INSTANCE_KEY__c</fullName>
    <externalId>true</externalId>
    <label>INSTANCE_KEY</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Invoice_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email__c</fullName>
    <label>Invoice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Details (Manual Product)</relationshipLabel>
    <relationshipName>Subscription_Line_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Max_Monthly_Data_Used_MB__c.field-meta.xml
<CustomField>
    <fullName>Max_Monthly_Data_Used_MB__c</fullName>
    <label>Max Monthly Data Used (MB)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>Mobile_no__c</fullName>
    <label>Mobile no.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/NUA_Owner_Control__c.field-meta.xml
<CustomField>
    <fullName>NUA_Owner_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NUA Owner Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/RCC_Owner_Control__c.field-meta.xml
<CustomField>
    <fullName>RCC_Owner_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RCC Owner Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Subscriber_Id__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Id__c</fullName>
    <label>Subscriber Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Details</relationshipLabel>
    <relationshipName>Subscription_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/TSRR_Owner_Control__c.field-meta.xml
<CustomField>
    <fullName>TSRR_Owner_Control__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TSRR Owner Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SLD_TriggerTest.cls
@IsTest
public class SLD_TriggerTest {
    @IsTest
    static void dataSettingUp(){
 	Integer numberOfDifferentBundles = 2, numberOfDifferentCategories = 2, numberOfDifferentFeaturesPerBundle = 4, numberOfDifferentProductsPerFeature = 2, numberOfDifferentOptionsPerBundle = 5;

        List<Product2> testBundlesWithOptions = testDataFactory.createBundles( numberOfDifferentBundles, numberOfDifferentCategories, numberOfDifferentFeaturesPerBundle, numberOfDifferentProductsPerFeature, numberOfDifferentOptionsPerBundle );

        SBQQ.TriggerControl.disable();
        List<Account> testAccounts = testDataFactory.createAccountsForTests( 1 );

        List<Opportunity> testOpps = testDataFactory.createOpportunitiesForAccounts( 1, testAccounts );

        List<SBQQ__Quote__c> testQuote = testDataFactory.createQuotesForOpps( 1, testOpps );

        List<SBQQ__QuoteLine__c> testQL = testDataFactory.createQuoteLinesForBundle( testBundlesWithOptions, testQuote );
	
        Id standardPriceBookId = Test.getStandardPricebookId();
            
        Contract cr = new Contract(AccountId = testAccounts[0].Id,
                                   Total_Contract_value__c = 100,
                                   ContractTerm = 36,
                                   StartDate = Date.today().addDays(-1),
                                   Migrated_Contract__c = false,
                                   Pricebook2Id = standardPriceBookId,
                                   SBQQ__AmendmentPricebookId__c = standardPriceBookId,
                                   SBQQ__RenewalPricebookId__c = standardPriceBookId,
                                   SBQQ__AmendmentRenewalBehavior__c = 'Latest End Date',
                                   Product_s_in_scope__c = 'Voice',
                                   SBQQ__RenewalTerm__c = 36,
                                   Mobile_Part_of_Contract__c =  TRUE ,
                                   Fastnet_Part_of_Contract__c =  FALSE,
                                   Data_Part_of_Contract__c = FALSE
                                   ); 
        insert cr;
        Product2 pr = new Product2(ProductAPI_Telia_Product_Id__c='CORFRI10G', name = 'Corporate Fri tale EU 10 GB',
                                           SBQQ__SubscriptionType__c = 'Renewable', isActive=true, Activation_Record_Type__c ='Voice');
                insert pr;
        
            Product2 pr2 = new Product2(ProductAPI_Telia_Product_Id__c='CORFRI20G', name = 'Corporate Fri tale EU 20 GB',
                                           SBQQ__SubscriptionType__c = 'Renewable', isActive=true, Activation_Record_Type__c ='Voice');
                insert pr2;
        
         SBQQ__Subscription__c newSubscription = new SBQQ__Subscription__c(
        				SBQQ__Contract__c = cr.Id,
                         SBQQ__Product__c = pr.Id,
                         SBQQ__Quantity__c = 1, //TODO!!
                         SBQQ__Account__c = testAccounts[0].Id,
                         SBQQ__ProductSubscriptionType__c = 'Renewable',
                         SBQQ__SubscriptionType__c = 'Renewable',
                         SBQQ__RenewalQuantity__c = 1,   //TODO trigger
                         SBQQ__RenewalPrice__c = 100,
                         SBQQ__NetPrice__c = 100,
                         SBQQ__CustomerPrice__c = 100);
        insert newSubscription;
        
          SBQQ__Subscription__c newSubscription2 = new SBQQ__Subscription__c(
        				SBQQ__Contract__c = cr.Id,
                         SBQQ__Product__c = pr2.Id,
                         SBQQ__Quantity__c = 1, //TODO!!
                         SBQQ__Account__c = testAccounts[0].Id,
                         SBQQ__ProductSubscriptionType__c = 'Renewable',
                         SBQQ__SubscriptionType__c = 'Renewable',
                         SBQQ__RenewalQuantity__c = 1,   //TODO trigger
                         SBQQ__RenewalPrice__c = 100,
                         SBQQ__NetPrice__c = 100,
                         SBQQ__CustomerPrice__c = 100);
        insert newSubscription2;
        
        Subscription_Line_Detail__c newSLD = new Subscription_Line_Detail__c(
        			INSTANCE_KEY__c = '1234',
            		Subscription__c = newSubscription.Id,
                    Subscriber_Id__c =  newSubscription.Id,
                    First_name__c = 'Test',
                    Max_Monthly_Data_Used_MB__c = 100,
                    Manual_Product__c = pr.Id,
                    Fokus_SOC__c = 'CORFRI10',
                    Mobile_no__c = '12345678',
                    Installation_address__c = 'test address',
                    Email__c = 'test@test.com',
                    RCC_Owner_Control__c = FALSE,
                    TSRR_Owner_Control__c = FALSE,
                    Last_name__c = 'Test',
                    Invoice_Email__c = 'test@test.com',
                    Ekstra_Data_SIM_number__c = '251625173',
                    Calls_from_DK_to_EU_MIN__c =  100,
                    Fixed_no__c = '5273627',
                    NUA_Owner_Control__c = FALSE);
        
        
        List<Subscription_Line_Detail__c> testSLDList = new List<Subscription_Line_Detail__c>();
        Test.startTest();
        insert newSLD;
        
        newSLD.Subscription__c = newSubscription2.Id;        
        update newSLD;
        Test.stopTest();
          
    }
}