force-app/main/default/objects/NorlysNow_Case__c/NorlysNow_Case__c.object-meta.xml
<CustomObject>
    <label>NorlysNow Case</label>
    <nameField>
        <displayFormat>NN-{000000000}</displayFormat>
        <label>NorlysNow Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NorlysNow Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NorlysNow_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NorlysNow Cases</relationshipLabel>
    <relationshipName>NorlysNow_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Service</fullName>
                <default>true</default>
                <label>Customer Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/NorlysNow_Id__c.field-meta.xml
<CustomField>
    <fullName>NorlysNow_Id__c</fullName>
    <externalId>true</externalId>
    <label>NorlysNow Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>NorlysNow Cases</relationshipLabel>
    <relationshipName>NorlysNow_Cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
                <default>true</default>
                <label>Major</label>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Reported_On__c.field-meta.xml
<CustomField>
    <fullName>Reported_On__c</fullName>
    <description>Date with the date of the creation of the parent case</description>
    <formula>Parent_Case__r.CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reported On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Request_Source__c.field-meta.xml
<CustomField>
    <fullName>Request_Source__c</fullName>
    <label>Request Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Care</fullName>
                <default>true</default>
                <label>Customer Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>for NorlysNow updates</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Redirected</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Sync_Message__c.field-meta.xml
<CustomField>
    <fullName>Sync_Message__c</fullName>
    <label>Sync Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>NorlysNow status delivery</description>
    <inlineHelpText>Please set Sync Status to &quot;Pending&quot; If you need to resend the NorlysNow case</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSM</fullName>
                <default>true</default>
                <label>GSM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Technology_Type__c.field-meta.xml
<CustomField>
    <fullName>Technology_Type__c</fullName>
    <label>Technology Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile Services</fullName>
                <default>true</default>
                <label>Mobile Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NorlysNow_Case__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BSS</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>VAS</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
                <default>true</default>
                <label>Voice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NorlysNowSelector.cls
public with sharing class NorlysNowSelector {

    public Map<Id, NorlysNow_Case__c> getNorlysNowCasesMap(Set<Id> recordIds) {
        Logger.logInfo(String.format('getNorlysNowCasesMap( {0} )', new List<Object>{ recordIds }));

        Map<Id, NorlysNow_Case__c> norlysNowCasesMap = new Map<Id, NorlysNow_Case__c>(
        (List<NorlysNow_Case__c>) new Query('NorlysNow_Case__c')
        .selectFields(new List<String>{
            'Id',
            'Name',
            'Account__c',
            'Parent_Case__c',
            'Parent_Case__r.Status',
            'Parent_Case__r.OwnerId',
            'CreatedBy.Id',
            'Priority__c',
            'Description__c',
            'Title__c',
            'Type__c',
            'Status__c',
            'Reported_On__c',
            'NorlysNow_Id__c',
            'Request_Source__c',
            'Category__c',
            'Technology_Type__c',
            'Technology__c',
            'Sync_Status__c',
            'Sync_Message__c'
        })
        .byId(recordIds)
        .addConditionNotNull('Parent_Case__c')
        .addConditionNotEq('Parent_Case__r.Status', 'Closed')
        .run()
        );

        return norlysNowCasesMap;
    }

    public List<NorlysNow_Case__c> getAllNorlysNowCasesUnderParentCases(Set<Id> parentCaseIds) {
        Logger.logInfo(String.format('getAllNorlysNowCasesUnderParentCases( {0} )', new List<Object>{ parentCaseIds }));

        List<NorlysNow_Case__c> norlysNowCases = new List<NorlysNow_Case__c>(
        (List<NorlysNow_Case__c>) new Query('NorlysNow_Case__c')
        .selectFields(new List<String>{
            'Id',
            'Parent_Case__c',
            'Status__c',
            'Sync_Status__c'
        })
        .addConditionIn('Parent_Case__c', parentCaseIds)
        .run()
        );

        return norlysNowCases;
    }

    public Map<Id, FeedItem> getFeedItemMap(Set<Id> recordIds ) {
        Logger.logInfo(String.format('getNorlysNowFeedItemMap( {0} )', new List<Object>{ recordIds }));
        Map<Id, FeedItem> feedItemMap = new Map<Id, FeedItem>(
            (List<FeedItem>) new Query('FeedItem')
                .selectFields(new List<String>{
                    'Id',
                    'Body',
                    'ParentId'
                })
                .byId(recordIds)
                .run()
        );

        return feedItemMap;
    }

    public List<ContentVersion> getContentVersions(Set<Id> fileIds) {
        Logger.logInfo(String.format('getContentVersions( {0} )', new List<Object>{ fileIds }));
        List<ContentVersion> cvList = (List<ContentVersion>) new Query('ContentVersion')
        .selectFields(new List<String>{
            'Id',
            'ContentDocumentId',
            'PathOnClient',
            'VersionData'
        })
        .addConditionEq('IsLatest', true)
        .addConditionIn('ContentDocumentId', fileIds)
        .run();

        return cvList;
    }

    public List<ContentDocumentLink> getContentDocumentLinks(Set<Id> recordIds) {
        Logger.logInfo(String.format('getContentDocumentLinks( {0} )', new List<Object>{ recordIds }));
        List<ContentDocumentLink> cdList = (List<ContentDocumentLink>) new Query('ContentDocumentLink')
        .selectFields(new List<String>{
            'ContentDocumentId',
            'LinkedEntityId'
        })
        .addConditionIn('ContentDocumentId', recordIds)
        .run();

        return cdList;
    }

    public CustomNotificationType getCustomNotificationType(String customNotifyTypeName) {
        Logger.logInfo(String.format('getCustomNotificationType( {0} )', new List<Object>{ customNotifyTypeName }));
        CustomNotificationType notifyType = (CustomNotificationType) new Query('CustomNotificationType')
        .selectField('Id')
        .addConditionEq('DeveloperName', customNotifyTypeName)
        .setLimit(1)
        .fetch();

        return notifyType;
    }

    public List<User> getUsers(Set<Id> ownerIds) {
        Logger.logInfo(String.format('getUsers( {0} )', new List<Object>{ ownerIds }));
        List<User> users = (List<User>) new Query('User')
        .selectFields(new List<String>{
            'Id',
            'Name',
            'Email'
        })
        .addConditionIn('Id', ownerIds)
        .run();

        return users;
    }

    public Map<Id, Case> getCasesByIds(Set<Id> parentCaseIds) {
        Map<Id, Case> closedParentCases = new Map<Id, Case>(
        (List<Case>) new Query('Case')
        .selectFields(new List<String>{
            'Id',
            'Status'
        })
        .addConditionIn('Id', parentCaseIds)
        .addConditionEq('Status', 'Closed')
        .run()
        );
       
        return closedParentCases;
    }

    public OrgWideEmailAddress getOrgWideEmailAddress(String address) {
        Logger.logInfo(String.format('getOrgWideEmailAddress( {0} )', new List<Object>{ address }));
        OrgWideEmailAddress orgWideEmailAddress = (OrgWideEmailAddress) new Query('OrgWideEmailAddress')
        .selectFields(new List<String>{
            'Id',
            'Address'
        })
        .addConditionEq('Address', address)
        .setLimit(1)
        .fetch();   
        return orgWideEmailAddress;
    }
}