force-app/main/default/objects/Account_Phone_Number_Series__c/Account_Phone_Number_Series__c.object-meta.xml
<CustomObject>
    <description>Represents a series of phone numbers attached to a CVR account. (DKT-45211)</description>
    <label>Account Phone Number Series</label>
    <nameField>
        <displayFormat>APNS-{000000000}</displayFormat>
        <label>Account Phone Number Series Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Series</relationshipLabel>
    <relationshipName>Account_Phone_Number_Series</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/batchUpdatePhoneNumberReservations.cls
/**
 * @description This batch job is used to update the phone number reservations for all accounts.
 * It iterates through all Account_Phone_Number_Series__c records and calls the NumberSyncService to synchronize the assignments.
 * @author Kenneth Houkjær
 */
public class batchUpdatePhoneNumberReservations extends BatchJob {
    private static final String QUERY = 'SELECT Id, Account__c FROM Account_Phone_Number_Series__c';
    @TestVisible
    private NumberSyncService numberSyncService;

    /**
     * @description The constructor for the batchUpdatePhoneNumberReservations class.
     * It initializes the numberSyncService.
     * @author Kenneth Houkjær
     */
    public batchUpdatePhoneNumberReservations() {
        this.numberSyncService = new NumberSyncService();
    }

    /**
     * @description This method is called at the beginning of the batch job.
     * It returns a Database.QueryLocator that retrieves the records to be processed.
     * @param bc The batchable context.
     * @return A Database.QueryLocator.
     * @author Kenneth Houkjær
     */
    public override Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(QUERY);
    }

    /**
     * @description This method is called for each batch of records.
     * It iterates through the records and calls the NumberSyncService to synchronize the assignments.
     * @param bc The batchable context.
     * @param scope The list of records to process.
     * @author Kenneth Houkjær
     */
    public override void execute(Database.BatchableContext bc, List<SObject> scope) {
        for (SObject s : scope) {
            Account_Phone_Number_Series__c series = (Account_Phone_Number_Series__c) s;
            try {
                Account acc = new Account(Id = series.Account__c);
                this.numberSyncService.synchronizeAssignmentsForAccount(acc);
            } catch (Exception e) {
                Logger.logError(this.getJobName(), 'Error processing Account_Phone_Number_Series__c ' + series.Id + ': ' + e.getMessage());
            }
        }
    }

    /**
     * @description This method is called at the end of the batch job.
     * It logs a message and emits the logs.
     * @param bc The batchable context.
     * @author Kenneth Houkjær
     */
    public override void finish(Database.BatchableContext bc) {
        Logger.logInfo(this.getJobName() + ' finished.');
        Logger.emit();
    }

    /**
     * @description This method returns the cron expression for the job.
     * It returns a cron expression that runs the job every day at 1am.
     * @return The cron expression for the job.
     * @author Kenneth Houkjær
     */
    public override String getCronExpression() {
        return '0 0 1 * * ?'; // Every day at 1am
    }
}