force-app/main/default/objects/Account_Phone_Number_Series__c/Account_Phone_Number_Series__c.object-meta.xml
<CustomObject>
    <description>Represents a series of phone numbers attached to a CVR account. (DKT-45211)</description>
    <label>Account Phone Number Series</label>
    <nameField>
        <displayFormat>APNS-{000000000}</displayFormat>
        <label>Account Phone Number Series Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Group__c.field-meta.xml
<CustomField>
    <fullName>Number_Group__c</fullName>
    <label>Number Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Location__c.field-meta.xml
<CustomField>
    <fullName>Number_Location__c</fullName>
    <label>Number Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BRZ</fullName>
            </value>
            <value>
                <fullName>BUS</fullName>
            </value>
            <value>
                <fullName>EKC</fullName>
            </value>
            <value>
                <fullName>GOL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FIX</fullName>
                <isActive>false</isActive>
                <label>FIX</label>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
                <isActive>false</isActive>
                <label>MSC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NumberLoadNumberAction.cls
/**
 * The NumberLoadNumberAction class is responsible for loading phone numbers from the Number API.
 * It is an invocable action that can be called from a flow.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         27/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 27/07/2025
 */
public with sharing class NumberLoadNumberAction {
    @TestVisible
    private static NumberClient numberClient;
    
    static {
        SingletonFactory factory = SingletonFactory.getFactory();
        
        numberClient = (NumberClient) factory.getOrRegisterSingleton(NumberClient.class);
    }

    /**
     * @description This method is called from a flow to load phone numbers from the Number API.
     * @param inputVariables A list of input variables from the flow.
     * @return A list of output variables containing the loaded phone numbers.
     */
    @InvocableMethod(category='Number' label='Get numbers for serie' description='Fetch numbers with numberclient with data request information provided by the number serie.')
    public static List<OutputVariables> loadPhoneNumbers(List<InputVariables> inputVariables) {        
        OutputVariables output = new OutputVariables();
        
        try{
			logger.logInfo('inputVariables ' + inputVariables);
            logger.logInfo('inputVariables size ' + inputVariables.size());

            NumberClientRequestDTO.NumberDetails detailsRequest = getNumberDetailsRequest(inputVariables.get(0));
            
            //get a number of possible numbers from the number api to present to the user for choosing
        	NumberClientResponseDTO.NumberDetails numberDetailsResponse = numberClient.getNumberDetails(detailsRequest);
            
            logger.logInfo('numberDetailsResponse ' + numberDetailsResponse);
            logger.logInfo('numberDetailsResponse.data ' + numberDetailsResponse.data);

            for(NumberClientResponseDTO.NumberData data : numberDetailsResponse.data ){
                output.phoneNumbers.add(data.id);
            }
        }catch(HTTPException ex){
            Logger.logError(ex);
            Logger.emit();
            throw ex;
        }
        
        return new List<OutputVariables>{output};
	}
    
    /**
     * @description This method creates a NumberClientRequestDTO.NumberDetails object from the input variables.
     * @param inputVar The input variables from the flow.
     * @return A NumberClientRequestDTO.NumberDetails object.
     */
    private static NumberClientRequestDTO.NumberDetails getNumberDetailsRequest(InputVariables inputVar){
        NumberClientRequestDTO.NumberDetails detailsRequest = new NumberClientRequestDTO.NumberDetails();
        
        detailsRequest.numberStatus = SFConstants.ASSIGNED_AVAILABLE;
        detailsRequest.product_type = inputVar.serie.Product_Type__c;
        detailsRequest.numberGroup = inputVar.serie.Number_Group__c;
        detailsRequest.numberLocation = inputVar.serie.Number_Location__c;

        if(inputVar.amountOfNumbers == null){
            detailsRequest.amountOfNumbers = 1;
        }
        else{
            detailsRequest.amountOfNumbers = inputVar.amountOfNumbers;
        }

        return detailsRequest;
    }
    
	public class InputVariables {
		@InvocableVariable
		public Account_Phone_Number_Series__c serie;
		@InvocableVariable
        public Integer amountOfNumbers;
	}

	public class OutputVariables {
        @InvocableVariable
        public List<String> phoneNumbers = new List<String>();
	}
}