force-app/main/default/objects/Address_line__c/Address_line__c.object-meta.xml
<CustomObject>
    <description>Object for collecting address information for an activation</description>
    <label>Address line</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Active_Blocking_Line_Present__c.field-meta.xml
<CustomField>
    <fullName>Active_Blocking_Line_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value comes from POQ Item record</description>
    <label>Active Blocking Line Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK( Street_Name__c ), &apos;&apos;, (Street_Name__c + &apos; &apos; + Number__c)) +
IF(ISBLANK( Floor__c ), &apos;&apos;, (&apos;, &apos; + Floor__c)) +
IF(ISBLANK( Door__c ), &apos;&apos;, IF((FIND(&apos;.&apos;, Floor__c)) &gt; 0, (&apos; &apos; + Door__c), (&apos;. &apos; + Door__c))) +
IF(ISBLANK( ZIP_Code__c ), &apos;&apos;, (&apos;, &apos; + ZIP_Code__c)) +
IF(ISBLANK( City__c ), &apos;&apos;, (&apos; &apos; + City__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address_Wash_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Wash_Status__c</fullName>
    <label>Address Wash Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Not Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Door__c.field-meta.xml
<CustomField>
    <fullName>Door__c</fullName>
    <label>Door</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Municipality_Code__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Code__c</fullName>
    <label>Municipality Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Plug_Technician_Required__c.field-meta.xml
<CustomField>
    <fullName>Plug_Technician_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plug Technician Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/plugPresentPositiveValidation__c.field-meta.xml
<CustomField>
    <fullName>plugPresentPositiveValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>plugPresentPositiveValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The QuoteLine that resulted from this LocationLine.</description>
    <inlineHelpText>The QuoteLine that resulted from this LocationLine.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Code__c.field-meta.xml
<CustomField>
    <fullName>Street_Code__c</fullName>
    <label>Street Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VAS_product__c.field-meta.xml
<CustomField>
    <fullName>VAS_product__c</fullName>
    <label>VAS product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_VAS_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VendorProductCatalogId__c.field-meta.xml
<CustomField>
    <fullName>VendorProductCatalogId__c</fullName>
    <label>VendorProductCatalogId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VendorProductCode__c.field-meta.xml
<CustomField>
    <fullName>VendorProductCode__c</fullName>
    <label>VendorProductCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LocationLineSelector.cls
public without sharing class LocationLineSelector {
	private static final String ERROR_ORIGIN = 'Apex';
	private static final String ERROR_ADDITIONAL_INFO = 'LocationLineSelector';
	public static final String ADDRESS_WASH_STATUS_VALID = 'Valid';
	public static final String ADDRESS_WASH_STATUS_NOT_VALID = 'Not Valid';

	private static ErrorLogging errorLogging = new ErrorLogging(ERROR_ORIGIN);

	@AuraEnabled(cacheable=true)
	public static List<Location_Line__c> getLocationLinesByAccountId() {
		return [
			SELECT Name, Id, Employee_ID__c, Street_Name__c, Number__c, Floor__c, Door__c, City__c, ZIP_Code__c
			FROM Location_Line__c
			// WHERE  Address_Line__c.Case__c =:accountId AND Not_to_Activation__c = false
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Location_Line__c> getLocationLinesByOpportunityId(String oppId) {
		return [
			SELECT
				Name,
				Id,
				Employee_ID__c,
				Street_Name__c,
				Number__c,
				Floor__c,
				Door__c,
				City__c,
				ZIP_Code__c,
				Address__c,
				OTC_product__c,
				Subscription_product__c,
				plugPresentPositiveValidation__c,
				Plug_Technician_Required__c,
				Active_Blocking_Line_Present__c
			FROM Location_Line__c
			WHERE Opportunity__c = :oppId
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Location_Line__c> getValidLocationLinesByOpportunityId(String oppId) {
		return [
			SELECT Name, Id, Employee_ID__c, Street_Name__c, Number__c, Floor__c, Door__c, City__c, ZIP_Code__c, Address__c
			FROM Location_Line__c
			WHERE Opportunity__c = :oppId AND Address_Wash_Status__c = 'Valid'
		];
	}

	/**
	 * Get all valid location lines by opportunity ids
	 * @param oppIdList
	 * @return List<Location_Line__c>
	 */
	public static List<Location_Line__c> getValidLocationLinesByOpportunityIds(List<Id> oppIdList) {
		return [
			SELECT 
				Id,
				Name,
				Active_Blocking_Line_Present__c,
				Address__c,
				Address_Wash_Status__c,
				City__c,
				Door__c,
				Employee_ID__c,
				Floor__c,
				Municipality_Code__c,
				Number__c,
				Opportunity__c,
				OTC_product__c,
				Plug_Technician_Required__c,
				plugPresentPositiveValidation__c,
				Quote_Line__c,
				Street_Code__c,
				Street_Name__c,
				Subscription_product__c,
				VAS_product__c,
				ZIP_Code__c
			FROM Location_Line__c
			WHERE Opportunity__c IN :oppIdList 
			AND Address_Wash_Status__c = :ADDRESS_WASH_STATUS_VALID
		];
	}

	@AuraEnabled(cacheable=true)
	public static Map<Id, Location_Line__c> getLocationLinesByIds(List<Id> locationLineIds) {
		return new Map<Id, Location_Line__c>(
			[
				SELECT
					Name,
					Id,
					Employee_ID__c,
					Street_Name__c,
					Number__c,
					Floor__c,
					Door__c,
					City__c,
					ZIP_Code__c,
					Address__c,
					VAS_product__c,
					Subscription_product__c,
					OTC_product__c,
					AddressRefId__c,
					SiteId__c,
					lineConnectionStatus__c,
					lineProvider__c,
					VendorProductCode__c,
					VendorProductCatalogId__c
				FROM Location_Line__c
				WHERE Id IN :locationLineIds
			]
		);
	}
}