force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/Subscription_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Detail</label>
    <nameField>
        <displayFormat>SLD-{000000}</displayFormat>
        <label>Subscription Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscription Line Details (Manual Product)</relationshipLabel>
    <relationshipName>Subscription_Line_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Subscription Line Details</relationshipLabel>
    <relationshipName>Subscription_Line_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Details</relationshipLabel>
    <relationshipName>Subscription_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Activation_lineCreateAmendment.cls
public class Activation_lineCreateAmendment {
@InvocableMethod(label='Create activation lines for amendments' description='Updating activation lines for a Quote from subscription details')
   public static void Activation_line_Create(list <id> recordId)
        {
            Activation_lineCreateAmendment_Iterable ProcessBatch = new Activation_lineCreateAmendment_Iterable();
            
              
            String columnNames = 'Id';
            Schema.DescribeSObjectResult subscriptionLineDetail_desc = Subscription_Line_Detail__c.sObjectType.getDescribe(); 
            Map<String, Schema.SObjectField> subscriptionLineDetail_fields = subscriptionLineDetail_desc.fields.getMap();
                    
              for(Schema.sObjectField fld:subscriptionLineDetail_fields.values())
              {     
                 columnNames = columnNames + ',' +  fld.getDescribe().getName();  
              } 
            
            columnNames = columnNames.removeStart('Id,');
 
            String batchQuery = 'SELECT '+ columnNames + 
            ',Subscription__r.SBQQ__Quantity__c,' +
            'Manual_Product__r.ProductAPI_Telia_Product_Id__c, ' +
            'Manual_Product__r.activate_with_other_products__c, '+
            ' Subscription__r.SBQQ__Account__r.Name from Subscription_Line_Detail__c  ' +
            ' where Subscription__c  in ( select SBQQ__UpgradedSubscription__c from SBQQ__QuoteLine__c '+
            ' where SBQQ__Quote__c =\'' + recordId.get(0) + 
            '\' and SBQQ__Product__r.Activation_Record_Type__c = \'Voice\'' +
            ') order by Quote_Line__c, Quote_line__r.SBQQ__UpgradedSubscription__c, '+
            ' Manual_Product__r.activate_with_other_products__c';
            ProcessBatch.query = batchQuery; 
            ProcessBatch.recordId = String.valueOf(recordId.get(0));
            ID batchprocessid = Database.executeBatch(ProcessBatch);   
        }

}