force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Requires_Activation_Check__c.field-meta.xml
<CustomField>
    <fullName>Requires_Activation_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field is used to include/exclude the product from the activation check calculations</description>
    <inlineHelpText>The field is used to include/exclude the product from the activation check calculations</inlineHelpText>
    <label>Requires Activation Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductSelector.cls
public with sharing class ProductSelector {
	@AuraEnabled(cacheable=true)
	public static List<Product2> getBusinessInternetProducts() {
		return new Query('Product2')
			.selectFields('Name, Id')
			.addConditionEq('IsActive', true)
			.addConditionIn('ProductCode', new List<String>{ '37000', '37001' })
			.orderBy('Name')
			.run();
	}

	public static List<Product2> getAllActiveProductsOrderByName() {
		return new Query('Product2')
			.selectFields('Name, Id, ProductAPI_Telia_Product_Id__c')
			.addConditionEq('IsActive', true)
			.orderBy('Name')
			.run();
	}

	public static List<Product2> getValueAddedServiceProducts() {
		// Only used in Activation_check_details ?
		return new Query('Product2')
			.selectFields('Name, Id, ProductAPI_Telia_Product_Id__c')
			.addConditionEq('IsActive', true)
			.addConditionEq('activate_with_other_products__c', true)
			.addConditionEq('Requires_Activation_Check__c', true)
			.run();
	}

	public static List<Product2> getProductByPriceplanCode(String priceplanCode) {
		return new Query('Product2')
			.selectFields('Name, Id, ProductAPI_Telia_Product_Id__c')
			.addConditionEq('IsActive', true)
			.addConditionEq('ProductAPI_Telia_Product_Id__c', priceplanCode)
			.setLimit(1)
			.run();
	}

	/**
	 * Get all products with the ProductAPI_Telia_Product_Id__c field populated
	 * @return list of products
	 */
	public static List<Product2> getAllProductsHavingTeliaProductId() {
		return new Query('Product2')
			.selectFields('Id, Name, ProductAPI_Telia_Product_Id__c')
			.addConditionNotNull('ProductAPI_Telia_Product_Id__c')
			.orderBy('IsActive', 'DESC')
			.orderBy('ProductAPI_Telia_Product_Id__c')
			.run();
	}

	public static List<Product2> getProductsWithActivationInfoByIds(List<Id> listOfProductIds) {
		return (List<Product2>) new Query('Product2')
			.selectFields(new List<String>{ 'Id', 'Activate_with_other_products__c', 'Activation_Record_Type__c' })
			.addConditionIn('Id', listOfProductIds)
			.run();
	}
}