force-app/main/default/objects/Account/fields/Billing_Door_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Door_Number__c</fullName>
    <description>Hidden from the user interface, to double check the full address fields</description>
    <label>Billing Door Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Floor_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Floor_Number__c</fullName>
    <label>Billing Floor Number</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Name__c</fullName>
    <label>Billing_Street_Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_Number__c</fullName>
    <label>Billing_Street_Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Play_Vesting_Reason__c.field-meta.xml
<CustomField>
    <fullName>Sales_Play_Vesting_Reason__c</fullName>
    <description>Used in Apex class SalesPlayManagementGetAccountsAction and Flow Sales_Play_Management to show the user the reason for an Account being filtered from the standard table. Values are populated temporarily by Apex and never saved.</description>
    <label>Sales Play Vesting Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountSelector.cls
/**
 * Selector class for Account
 */
public with sharing class AccountSelector {
	public static Account getByCVR(String cvr) {
		return [
			SELECT
				Id,
				Name,
				BillingPostalCode,
				Billing_Street_Name__c,
				Billing_Street_Number__c,
				Billing_Floor_Number__c,
				Billing_Door_Number__c,
				Billing_Street_Number_Suffix__c,
				BillingCity,
				BillingCountry,
				CVR__c,
				Phone,
				OwnerId,
				Sales_Play_Vesting_Reason__c
			FROM Account
			WHERE CVR__c = :cvr
			LIMIT 1
		];
	}

	public static List<Account> getAccountsByIds(List<Id> accountIds) {
		return [
	            SELECT Id, CVR__c
	            FROM Account
	            WHERE Id IN :accountIds
	        ];
	}
    
	@AuraEnabled(cacheable=true)
	public static Account getAccountByCaseId(String caseId) {
		List<Account> accounts = [SELECT Id FROM Account WHERE Id IN (SELECT AccountId FROM Case WHERE Id = :caseId)];
		if(!accounts.isEmpty()) {
			return accounts[0];
		}
		
		return null;
	}
}