force-app/main/default/objects/Account/fields/Customer_has_Touchpoint__c.field-meta.xml
<CustomField>
    <fullName>Customer_has_Touchpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical field used to indicate customer that have Touchpoint activated.</description>
    <label>Customer has Touchpoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Needs to have the exact same values with the ProductGroup picklist on the Case so that the EmailToCase setup can set the ProductGroup on the case based on this value.</description>
    <inlineHelpText>Used to help EmailtoCase to set the ProductGroup value on the Case the same.</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Hosting</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>Telia Home Office</fullName>
            </value>
            <value>
                <fullName>Not applicable</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
                <isActive>false</isActive>
                <label>Mobile</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/UC_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>UC_Activation_Date__c</fullName>
    <label>UC Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Funktionsnr__c.field-meta.xml
<CustomField>
    <fullName>Funktionsnr__c</fullName>
    <inlineHelpText>Indicate the type of UC function number</inlineHelpText>
    <label>Numbertype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Funktionsnummer</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Manual_Product__c.field-meta.xml
<CustomField>
    <fullName>Manual_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Add relevant product for the manual activation</inlineHelpText>
    <label>Manual Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Activations lines (Manual Product)</relationshipLabel>
    <relationshipName>Activations_lines7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Number_Porting_End_of_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Number_Porting_End_of_Commitment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if number porting should be by end of the customers existing commitment</inlineHelpText>
    <label>Number Porting End of Commitment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_no_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_no_Status__c</fullName>
    <inlineHelpText>Chose what needs to be done with number</inlineHelpText>
    <label>Phone no Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Phone_no_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Power_of_Attorney_record__c.field-meta.xml
<CustomField>
    <fullName>Power_of_Attorney_record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Power of Attorney record</label>
    <referenceTo>Porting__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activation_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Telia_INSIGHT_e_mail_contact__c.field-meta.xml
<CustomField>
    <fullName>Telia_INSIGHT_e_mail_contact__c</fullName>
    <inlineHelpText>This field must always be filled in with the Telia INSIGHT contact person.</inlineHelpText>
    <label>Telia INSIGHT e-mail contact</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Bruger__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Bruger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether Touchpoint Bruger is a active SOC or a future SOC.</inlineHelpText>
    <label>Touchpoint Bruger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Receptionist__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Receptionist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Receptionist is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Receptionist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Softphone__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Softphone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Softphone is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Softphone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Touchpoint_Statistik__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Statistik__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used for data gathering reports and data loader script.</description>
    <inlineHelpText>Select whether the Touchpoint Statistik is a active SOC or a future SOC</inlineHelpText>
    <label>Touchpoint Statistik</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBTB11__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBTB11__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra SIM-kort BtB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBTB2__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBTB2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra SIM-kort BtB OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX2__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 2 kort OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX3__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 3 kort OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX4__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX4__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 4 kort OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX5__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX5__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 2 kort</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX6__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX6__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 3 kort</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_SIMBX7__c.field-meta.xml
<CustomField>
    <fullName>VAS_SIMBX7__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used by Order API and will need to have naming convention as specified in Field Name</description>
    <inlineHelpText>Check this field to add this add-on</inlineHelpText>
    <label>Ekstra datakort – nummer 4 kort</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Activation_Check_Result__c.field-meta.xml
<CustomField>
    <fullName>Case_Activation_Check_Result__c</fullName>
    <label>Activation Check Result</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Activation_Check_Time__c.field-meta.xml
<CustomField>
    <fullName>Case_Activation_Check_Time__c</fullName>
    <label>Activation Check Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for linking an order to a case. Usewd in the activation process where the case object is used to run the process</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Used in Quote templates to evaluate if specific addendums should be added to Quote/Contract or not. Used by Onboarding portal to filter certain things. 

NOTE: It&apos;s best to be careful when changing any of the existing values here. Values Assigned automatically by Process Builder.</description>
    <label>Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Activation_check_details.cls
/**
 * Modified by Mujahid 
 * on 27/10/2022
 */
public with sharing class Activation_check_details {
    public String resultText{get;set;} 
    public String recordId; 
    String quoteId;         
    
    public Activation_check_details(ApexPages.StandardController controller) {
        System.debug('controller = ' + controller);
        recordId = controller.getRecord().Id;
        resultText = '';
    }   

    /**
     * This method will be invoked by Activation Updates and Notifications Flow
     */
    @InvocableMethod
    public static void Activation(List<Id> recordId) {  
        activationCheck(recordId.get(0));
    }
    
    /** 
     * This method will be invoked by the visual force page which is called by Activation Check button in the Case Layout 
     */      
    public void Activation_Check() {
        activationCheck(recordId);
    }

    @TestVisible
    private static void activationCheck(Id recordId) {
        String resultText = '';
        Activation__c activationRecord;
        String quoteId;

        try{            
            List<Activation__c> activationsByCaseId = ActivationSelector.getActivationsByCaseId(recordId);    
            System.debug('activationsByCaseId = ' + activationsByCaseId);
            if(activationsByCaseId.size() <=0) {
                resultText = 'Activation details can not be found with the Id value from:' + recordId;
                return;
            }else{
                activationRecord = activationsByCaseId[0];
            }
            
            quoteId = activationRecord.Case__r.Quote__c;
            
            List<Product2> productInfoList = ProductSelector.getAllActiveProductsOrderByName();  
            
            Map<String,String> allProducts= new Map<String, String>();
            //productId,Name  
            Map<String,String> allProductNames= new Map<String, String>();
            //Name,productId         
            for(Product2 pr : productInfoList) {
                allProducts.put(pr.Id,pr.Name);
                allProductNames.put(pr.Name,pr.Id);
            }
            
            List<Product2> vasProductInfoList = ProductSelector.getValueAddedServiceProducts();

            Map<String,String> vasProducts= new Map<String, String>();
            //TeliaProductId,Id
            
            for(Product2 prVas : vasProductInfoList) {
                vasProducts.put(prVas.ProductAPI_Telia_Product_Id__c,prVas.Id);    
            }

            //Select only the VAS products inside the Quote ONLY VAS
            List<SBQQ__QuoteLine__c> quoteLineInfoList = QuoteLineSelector.getValueAddedServiceProductByQuote(quoteId);
            
            Map<String,integer> quoteProducts= new Map<String, integer>();
            //productId, Quantity
            
            for(SBQQ__QuoteLine__c ql : quoteLineInfoList) {
                quoteProducts.put(ql.SBQQ__Product__c,Integer.valueOf(ql.SBQQ__Quantity__c));    
            }
            
            //Query the VAS services list
            Schema.DescribeSObjectResult activationlineDesc = Activation_line__c.sObjectType.getDescribe(); 
            
            Map<String, Schema.SObjectField> activationlineFields = activationlineDesc.fields.getMap();
            Map<String,String> vasfields= new Map<String, String>();
            String columnNames='Id';
            
    
            for(Schema.sObjectField fld:activationlineFields.values()) {     
                if(String.valueof(fld).indexOf('VAS_')==0) {
                    columnNames = columnNames + ',' +  fld.getDescribe().getName();
                    vasfields.put(fld.getDescribe().getName(),fld.getDescribe().getType().name().toupperCase());
                }
            }

            String productId;
            String vasName;
            
            //Query the ActivationLines
            List<Activation_line__c>  activationLinesByCase = ActivationLineSelector.getActivationLinesByCaseId(recordId, columnNames);
                        
            //Loop through the activation lines
            Map<String,integer> activationLineProducts= new Map<String, integer>();
            Integer quantity; 
            Boolean added= false;
            for (Activation_line__c activationLineData : activationLinesByCase) {
                //START OF LOOPING ACTIVATION LINES
                
                //First loop gets the orderproduct related count
                productId = activationLineData.Manual_Product__c; 
                added= false;

                for (String key : activationLineProducts.keySet())  { 
                    if(key==productId && String.isNotBlank(activationLineData.Manual_Product__r.ProductAPI_Telia_Product_Id__c)) { 
                        quantity = activationLineProducts.get(productId) + 1;
                        activationLineProducts.remove(productId);
                        activationLineProducts.put(productId,quantity); 
                        added = true;
                        break;
                    }                    
                }

                if(added==false && String.isNotBlank(activationLineData.Manual_Product__r.ProductAPI_Telia_Product_Id__c)) { 
                    activationLineProducts.put(productId,1);         
                } 
                
                added=false;
                
                //Touchpoint section
                if(activationLineData.Touchpoint_Bruger__c ) { 
                    productId = allProductNames.get('Touchpoint Bruger');
                    if(activationLineProducts.get(productId) >0) {
                        quantity = activationLineProducts.get(productId)+ 1;
                        activationLineProducts.remove(productId);  
                        activationLineProducts.put(productId,quantity ); 
                    } else {
                        activationLineProducts.put(productId,1); 
                    }    
                } 

                if(activationLineData.Touchpoint_Receptionist__c ) { 
                    productId = allProductNames.get('Touchpoint Receptionist');
                    if(activationLineProducts.get(productId) >0) {
                        quantity = activationLineProducts.get(productId)+ 1;
                        activationLineProducts.remove(productId);  
                        activationLineProducts.put(productId,quantity ); 
                    } else {
                        activationLineProducts.put(productId,1); 
                    }    
                }

                if(activationLineData.Touchpoint_Statistik__c ) { 
                    productId = allProductNames.get('Touchpoint Statistik');
                    if(activationLineProducts.get(productId) >0){
                        quantity = activationLineProducts.get(productId)+ 1;
                        activationLineProducts.remove(productId);  
                        activationLineProducts.put(productId,quantity ); 
                    } else {
                        activationLineProducts.put(productId,1); 
                    }    
                }

                if(activationLineData.Touchpoint_Softphone__c ) { 
                    productId = allProductNames.get('Touchpoint Softphone');
                    if(activationLineProducts.get(productId) >0){
                            quantity = activationLineProducts.get(productId)+ 1;
                            activationLineProducts.remove(productId);  
                            activationLineProducts.put(productId,quantity ); 
                        }
                    else {
                        activationLineProducts.put(productId,1); 
                    }    
                }

                //VAS services section    
                added = false;      
                for (String key : vasfields.keySet()){
                    productId = null;
                    if (vasfields.get(key) == 'BOOLEAN'  && activationLineData.get(key) == true){ 
                        vasName = key.remove('VAS_').remove('__c'); 
                        for (String vasTeliaProductId : vasProducts.keySet()){  
                            if(vasName == vasTeliaProductId) { 
                                productId = vasProducts.get(vasTeliaProductId);
                                break;
                            }     
                        } 
                        if(productId != null){ //Found a VAS that is not in the activation check list
                        
                            for (String vaskey : activationLineProducts.keySet()) { 
                                if(productId == vaskey && productId!=null) {  
                                    quantity = activationLineProducts.get(productId)+ 1;
                                    activationLineProducts.remove(productId);  
                                    activationLineProducts.put(productId,quantity );
                                    added = true;
                                    break;
                                }      
                            }  

                            if(added == false && productId!=null) {
                                activationLineProducts.put(productId,1);              
                            }
                            
                        }//if (vasfields.get(key) == 'BOOLEAN'
                    } else {    
                        if (vasfields.get(key) == 'INTEGER' && integer.valueof(activationLineData.get(key)) >0) {
                            System.debug('integer VAS to be added (not implemented) ' + vasName);     
                        }

                        if ((vasfields.get(key) == 'PICKLIST' || vasfields.get(key) == 'STRING') && activationLineData.get(key) != null) {
                            vasName = String.Valueof(activationLineData.get(key));
                            
                            for (String vasTeliaProductId : vasProducts.keySet()) {  
                                if(vasName == vasTeliaProductId ) { 
                                    productId = vasProducts.get(vasTeliaProductId);
                                    break;
                                }     
                            } 

                            if(productId != null) { 
                                for (String vasPickkey : activationLineProducts.keySet()) { 
                                    if(productId == vasPickkey && productId!=null) {  
                                        quantity = activationLineProducts.get(productId) +1;
                                        activationLineProducts.remove(productId);  
                                        activationLineProducts.put(productId,quantity);
                                        added = true;
                                        break;
                                    }
                                }

                                if(added == false && productId!=null) {
                                    activationLineProducts.put(productId,1); 
                                } 
                            }
                        }
                        added = false;   
                    }
                }
                
            }//END OF LOOPING ACTIVATION LINES 
            
            Integer i;
            
            for(String keyId: quoteProducts.Keyset()){
                
                //if Activation lines does not have that key
                if(!activationLineProducts.keyset().contains(keyId)){
                    //resultText = resultText + allProducts.get(keyId) + ' is in the Quote with quantity:'+ String.valueOf(quoteProducts.get(keyId)) +' but not in the Activation Lines' + ' <br/>' ;
                    resultText = resultText + '<font style="color:green;">Available ' + allProducts.get(keyId) + ':' + String.valueOf(quoteProducts.get(keyId)) + '</font> <br/>' ;
                } else  {
                    if (quoteProducts.get(keyId) > activationLineProducts.get(keyId)) {
                        i = Integer.valueOf(quoteProducts.get(keyId)) - Integer.valueOf(activationLineProducts.get(keyId));
                        resultText = resultText + '<font style="color:green;">Available ' + allProducts.get(keyId) + ':' + String.valueof(i) + '</font> <br/>' ;                      
                    }

                    if (quoteProducts.get(keyId) < activationLineProducts.get(keyId)) {    
                        i = Integer.valueOf(quoteProducts.get(keyId)) - Integer.valueOf(activationLineProducts.get(keyId));
                        resultText = resultText + '<font style="color:red;">Available ' + allProducts.get(keyId) + ':' + String.valueof(i) + '</font> <br/>' ;
                    }     
                } 
            } 
            for(String keyId2: activationLineProducts.Keyset()){
                //if Quote lines does not have that key
                if(!quoteProducts.keyset().contains(keyId2)){
                    resultText = resultText + '<font style="color:blue;">Available ' + allProducts.get(keyId2) + ':';
                    resultText = resultText + '-' + activationLineProducts.get(keyId2) + '</font> <br/>' ;                          
                }
            } 
            
            if(String.isBlank(resultText)) {
                resultText = 'There are no discrepancies';
            }
            validateActivation(activationRecord, resultText);
        }catch(Exception e){
            System.debug('### Error Occured : ' + e.getMessage());
            resultText = String.valueOf(e) + '\n\n' + e.getStackTraceString(); 
        }
    }

    @TestVisible
    private static void validateActivation(Activation__c activationRecordToValidate, String activationResultText) {  
        String resultText = activationResultText;
        String recordId = activationRecordToValidate.Case__c;
        
        if(String.isEmpty(String.valueOf(activationRecordToValidate.UC_Activation_Date__c)) && (activationRecordToValidate.Case__r.Account.Customer_has_Touchpoint__c )) {
           resultText =  resultText + 'UC Activation Date can not be blank<br>' ;  
        }

        //Query the ActivationLines
        List<Activation_line__c>  activationLinesByCaseId = ActivationLineSelector.getActivationLinesByCaseId(recordId);
        for (Activation_line__c activationLine : activationLinesByCaseId) { 
            if((!String.isBlank(activationLine.Manual_Product__r.Product_Group__c) && (activationLine.Manual_Product__r.Product_Group__c.IndexOf('Touchpoint') >= 0) && String.isEmpty(activationLine.Funktionsnr__c)) || 
               ((activationLine.Manual_Product__r.Name =='Touchpoint Fastnetnummer') && (activationLine.Funktionsnr__c) =='Mobile')) {
                resultText =  resultText + 'Please select the correct value for Funktionsnr on ' + activationLine.Name + '<br>';  
            } 

            if((!(activationLine.VAS_SIMBTB2__c) && (activationLine.VAS_SIMBX2__c || activationLine.VAS_SIMBX3__c || activationLine.VAS_SIMBX4__c )) ||
               (!(activationLine.VAS_SIMBX2__c) && (activationLine.VAS_SIMBX3__c || activationLine.VAS_SIMBX4__c )) ||
               (!(activationLine.VAS_SIMBX3__c) && (activationLine.VAS_SIMBX4__c ))) {   
                resultText =  resultText + 'Please select extra sim card services in an order from 1 to 4 on' + activationLine.Name + '<br>';   
            }

            if((!(activationLine.VAS_SIMBTB11__c) && (activationLine.VAS_SIMBX5__c || activationLine.VAS_SIMBX6__c || activationLine.VAS_SIMBX7__c )) ||
               (!(activationLine.VAS_SIMBX5__c) && (activationLine.VAS_SIMBX6__c || activationLine.VAS_SIMBX7__c )) ||
               (!(activationLine.VAS_SIMBX6__c) && (activationLine.VAS_SIMBX7__c ))) {   
                resultText =  resultText + 'Please select extra sim card services in an order from 1 to 4 on' + activationLine.Name + '<br>';   
            }

            if(activationLine.Phone_no_Status__c == 'Nummer skal porteres' && String.isBlank(activationLine.Power_of_Attorney_record__c)) {
               resultText =  resultText + 'Required field missing on Activation Line: POA on ' + activationLine.Name + '<br>';   
            }
            
            if(activationLine.Phone_no_Status__c == 'Nummer skal porteres' && (activationRecordToValidate.Case__r.Account.Customer_has_Touchpoint__c ) && (activationLine.Number_Porting_End_of_Commitment__c)) {
               resultText =  resultText + 'End Of Commitment can not be selected on ' + activationLine.Name + '<br>';  
            }
            
            // validation of TELIAINSIGHT email address
            if(activationLine.Manual_Product__r.ProductAPI_Telia_Product_Id__c == 'TINSIGH' && String.isEmpty(activationLine.Telia_INSIGHT_e_mail_contact__c)) {
               resultText =  resultText + '<br>Required field missing on Activation Line: Telia INSIGHT e-mail contact on ' + activationLine.Name + '<br>';  
            }
       }  
       updateCaseActivationStatus(recordId, resultText);
    } 

    @Testvisible
    private static void updateCaseActivationStatus(String recordId, String resultText) {
        Case activationCase = CaseSelector.getById(recordId);
        activationCase.Case_Activation_Check_Result__c = resultText;
        activationCase.Case_Activation_Check_Time__c = System.now();
        update activationCase;
    }
}