force-app/main/default/objects/Account/fields/Customer_has_Touchpoint__c.field-meta.xml
<CustomField>
    <fullName>Customer_has_Touchpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical field used to indicate customer that have Touchpoint activated.</description>
    <label>Customer has Touchpoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Bill_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Name__c</fullName>
    <formula>Case__r.Quote__r.SBQQ__BillingName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT( Case__r.Quote__r.SBQQ__BillingFrequency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/No_of_Location_Lines__c.field-meta.xml
<CustomField>
    <fullName>No_of_Location_Lines__c</fullName>
    <description>No of Location Lines when the Opportunity was closed and data was moved from Location Line to Activation Line.</description>
    <inlineHelpText>Summary of number of valid Location Lines when the Opportunity was closed.</inlineHelpText>
    <label>No. of Location Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Sort_by__c.field-meta.xml
<CustomField>
    <fullName>Sort_by__c</fullName>
    <description>The printet SIM cards will be sorted by this value when delivered by the print shop.
Numerical sorts by mobilenumber. Alphabetical sorts by name. Department sort by department.</description>
    <inlineHelpText>The printet SIM cards will be sorted by this value when delivered by the print shop.
Numerical sorts by mobilenumber. Alphabetical sorts by name. Department sort by department.</inlineHelpText>
    <label>Sort by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Numerical</fullName>
                <default>true</default>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>Alphabetical</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Sort_order__c.field-meta.xml
<CustomField>
    <fullName>Sort_order__c</fullName>
    <description>Set the sort order of the printet SIM cards to either Ascending (A-Z or 0-9) or Descending (Z-A or 9-0).</description>
    <inlineHelpText>Set the sort order of the printet SIM cards to either Ascending (A-Z or 0-9) or Descending (Z-A or 9-0).</inlineHelpText>
    <label>Sort order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ascending</fullName>
                <default>true</default>
                <label>Ascending</label>
            </value>
            <value>
                <fullName>Descending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/fields/UC_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>UC_Activation_Date__c</fullName>
    <label>UC Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activation__c/recordTypes/Home_office_activation.recordType-meta.xml
<RecordType>
    <fullName>Home_office_activation</fullName>
    <active>true</active>
    <label>Home office activation</label>
</RecordType>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Root_BAN__c.field-meta.xml
<CustomField>
    <fullName>Root_BAN__c</fullName>
    <description>The root billing account number for the account related to this activation case.</description>
    <inlineHelpText>The root billing account number for the account related to this activation case.</inlineHelpText>
    <label>Root BAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActivationSelector.cls
public with sharing class ActivationSelector {
	public static final String RECORD_TYPE_HOME_OFFICE_ACTIVATION = 'Home_office_activation';

	public static List<Activation__c> getActivationsByCaseId(String caseId) {
		return [
			SELECT Id, Case__r.Root_BAN__c, Case__r.Quote__c, Case__r.Account.Customer_has_Touchpoint__c, UC_Activation_Date__c
			FROM Activation__c
			WHERE Case__c = :caseId
		];
	}

	public static List<Activation__c> getActivationsByCases(List<Case> cases) {
		return [
			SELECT Id, Sort_by__c, Sort_order__c
			FROM Activation__c
			WHERE Case__c IN :cases
		];
	}

	public static Activation__c getActivationById(Id id) {
		Activation__c[] activations = [SELECT Bill_To_Name__c, Billing_Frequency__c, Case__c FROM Activation__c WHERE Id = :id];
		if (activations.size() > 0) {
			return activations.get(0);
		}
		return null;
	}
	
	@AuraEnabled(cacheable=true)
	public static Activation__c getActivationByCaseId(String caseId) {
		return [
			SELECT Id, Case__c
			FROM Activation__c
			WHERE Case__c =: caseId
			LIMIT 1
		];
	}

	/**
	 * Get Activation by Id of record type Home_Office_Activation
	 * 
	 * @param Set<Id> activationIdSet
	 * @return List<Activation__c>
	 */
	public static List<Activation__c> getHomeOfficeActivationByIds(Set<Id> activationIdSet) {
		return [
			SELECT Id, Name, No_of_Location_Lines__c
			FROM Activation__c
			WHERE RecordType.DeveloperName = :RECORD_TYPE_HOME_OFFICE_ACTIVATION
			AND Id IN :activationIdSet
		];
	}

}