force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Update_to_Contract_API__c.field-meta.xml
<CustomField>
    <fullName>Send_Update_to_Contract_API__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When set to true a Platform Event will be created containing Quote and Quote Line (Product) information which the Contract API subscribes to.</description>
    <label>Send Update to Contract API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountService.cls
public class AccountService {

    public Set<Id> CompanyAPIDataFetch(List<Account> accounts) {
        Logger.logInfo(String.format('CompanyAPIDataFetch( {0} )', new List<Object>{ accounts }));

        Set<Id> accountIdsForCompanyApiUpdate = new Set<Id>();
        for(Account acc : accounts) {
            if(acc.CVR__c != null) {
                accountIdsForCompanyApiUpdate.add(acc.Id);
            }
        }

        if(!accountIdsForCompanyApiUpdate.isEmpty()) {
            // TODO: CALLOUT needs to be refactored to use a service class
            Company_API_DataFetch.FetchData(accountIdsForCompanyApiUpdate);
        }

        return accountIdsForCompanyApiUpdate;
    }

    public List<Id> ContractAPIDataFetch(List<Account> accounts) {
        Logger.logInfo(String.format('ContractAPIDataFetch( {0} )', new List<Object>{ accounts }));

        List<Id> accountIdsForContractApiUpdate = new List<Id>();
        for(Account acc : accounts) {
            if(acc.Send_Update_to_Contract_API__c) {
                acc.Send_Update_to_Contract_API__c = false;
                accountIdsForContractApiUpdate.add(acc.Id);
            }
        }

        if(!accountIdsForContractApiUpdate.isEmpty()) {
            ContractApiEventService.createEvents(accountIdsForContractApiUpdate);
        }

        return accountIdsForContractApiUpdate;
    }
}