force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Revenue_Actual__c/Service_Revenue_Actual__c.object-meta.xml
<CustomObject>
    <description>User Story ID: 80 and 284
This object is populated via integration to the billing system. Each record contains the service revenue numbers for the following product categories per month:
Voice
Other
Call Guide
M2M
MBB and Dual SIM
Internet and MPLS</description>
    <label>Service Revenue Actual</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>Sales Actual</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Revenue Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Revenue_Actual__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>User story ID: 80 
The account generating the revenue</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Actuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/dlrs_Service_Revenue_ActualTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Service_Revenue_ActualTest
{
    @IsTest
    private static void testTrigger()
    {
        Account acct = new Account(Name='TestAccount', BillingCity='CP',BillingPostalCode = '2000',BillingCountry = 'DK'
                                           ,BillingStreet = 'Holmbladsgade 133', Phone = '111', CVR__c ='12345678');
        insert acct;
               
        // Force the dlrs_Service_Revenue_ActualTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Service_Revenue_Actual__c(Account__c = acct.Id));
    }
}