force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/Account_Phone_Number_Assignment__c.object-meta.xml
<CustomObject>
    <description>Represents individual phone numbers within a series (DKT-45211).</description>
    <label>Account Phone Number Assignment</label>
    <nameField>
        <displayFormat>APNA-{000000000}</displayFormat>
        <label>Account Phone Number Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account_Phone_Number_Series__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number_Series__c</fullName>
    <label>Account Phone Number Series</label>
    <referenceTo>Account_Phone_Number_Series__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Activation_line__c.field-meta.xml
<CustomField>
    <fullName>Activation_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for the Activation Line Phone Number assignment</description>
    <label>Activation line</label>
    <referenceTo>Activation_line__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/CTN_Number_Status__c.field-meta.xml
<CustomField>
    <fullName>CTN_Number_Status__c</fullName>
    <description>CTN numbers as per given status. Status Description: 
AA - Assigned Available
AR - Assigned Reserved
AI - Assigned In Use
AS - Assigned Suspended</description>
    <label>CTN Number Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Error__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Error__c</fullName>
    <label>Phone Number Reservation Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_User__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_User__c</fullName>
    <label>Phone Number User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/Account_Phone_Number_Series__c.object-meta.xml
<CustomObject>
    <description>Represents a series of phone numbers attached to a CVR account. (DKT-45211)</description>
    <label>Account Phone Number Series</label>
    <nameField>
        <displayFormat>APNS-{000000000}</displayFormat>
        <label>Account Phone Number Series Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Series</relationshipLabel>
    <relationshipName>Account_Phone_Number_Series</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Group__c.field-meta.xml
<CustomField>
    <fullName>Number_Group__c</fullName>
    <label>Number Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Location__c.field-meta.xml
<CustomField>
    <fullName>Number_Location__c</fullName>
    <label>Number Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BRZ</fullName>
            </value>
            <value>
                <fullName>BUS</fullName>
            </value>
            <value>
                <fullName>EKC</fullName>
            </value>
            <value>
                <fullName>GOL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FIX</fullName>
                <isActive>false</isActive>
                <label>FIX</label>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
                <isActive>false</isActive>
                <label>MSC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <formula>IF(
	RecordType.DeveloperName  &lt;&gt; &apos;Voice_activation&apos;, 
	&apos;&apos;, 
	IF( 
		AND(
			Count_Reservation_Status_INPROGRESS__c = 0, 
			Count_Reservation_Status_ERROR__c = 0, 
			Count_Reservation_Status_SUCCESS__c = 0
		), 
		&apos;&apos;,
		IF( 
			AND(
				Count_Reservation_Status_INPROGRESS__c = 0, 
				Count_Reservation_Status_ERROR__c = 0,
				Count_Reservation_Status_SUCCESS__c &gt; 0,
				Count_Empty_Mobile_Number__c = 0
			), 
			&apos;SUCCESS&apos;,
			IF(
				AND(
					Count_Reservation_Status_SUCCESS__c &gt; 0,
					Count_Empty_Mobile_Number__c &gt; 0
				),
				&apos;&apos;,
				IF( 
					Count_Reservation_Status_INPROGRESS__c &gt; 0, 
					&apos;INPROGRESS&apos;, 
					&apos;ERROR&apos;
				)
			)
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Number Reservation Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>Mobile_no__c</fullName>
    <description>Mobile number that can have max 8 digits</description>
    <inlineHelpText>Mobile number that can have max 8 digits</inlineHelpText>
    <label>Mobile no.</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_Number_Reservation_Error__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Error__c</fullName>
    <description>Will contain the error from the platform event number reservation execution</description>
    <label>Phone Number Reservation Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventExecutor__e/EventExecutor__e.object-meta.xml
<CustomObject>
    <label>EventExecutor</label>
    <pluralLabel>EventExecutors</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventExecutor__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>A JSON string that contains parameters that is used in the execute functions</description>
    <inlineHelpText>A JSON string that contains parameters that is used in the execute functions</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The counter with number of times executed has failed before</description>
    <inlineHelpText>The counter with number of times executed has failed before</inlineHelpText>
    <label>RetryCount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NumberActivationLinesExecutorHandlerTest.cls
/**
 * The NumberActivationLinesExecutorHandlerTest class is responsible for testing the NumberActivationLinesExecutorHandler class.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         28/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 27/07/2025
 */
@isTest
public class NumberActivationLinesExecutorHandlerTest {
  
    /**
     * @description Tests that the execute method sets the status to success and
     * that the activationLine gets a phonenumber and that the assignment gets a relation to the activationline.
     * For and Open Series Assignment
     */
    @IsTest
    public static void execute_openSeriesNumber_assignsNumberToActivationLineAndRelationOnAssignment() {
        
        Mock numberClientMock = Mock.forType(NumberClient.class);
        MethodSpy reserveNumberDetailByMsisdnAndCVR = numberClientMock.spyOn('reserveNumberDetailByMsisdnAndCVR');
        NumberClientResponseDTO.NumberDetail responseWithNumber = new NumberClientResponseDTO.NumberDetail();
        responseWithNumber.data = new NumberClientResponseDTO.NumberData();
        responseWithNumber.data.id = '12345678';
        reserveNumberDetailByMsisdnAndCvr.whenCalledWith(Argument.any(), Argument.any(), Argument.any()).thenReturn(responseWithNumber);

        NumberClient numberClient = (NumberClient) numberClientMock.stub;
        DatabaseService dbMock = new DatabaseService().mockDMLs();

        NumberActivationLinesExecutorHandler handler = new NumberActivationLinesExecutorHandler(numberClient, dbMock);

        List<NumberActivationLinesExecutorAction.InputVariables> inputVariables = new List<NumberActivationLinesExecutorAction.InputVariables>();
        NumberActivationLinesExecutorAction.InputVariables vars = new NumberActivationLinesExecutorAction.InputVariables();
        vars.chunkSize = 3;
        vars.activationLineIdToAssignementId = new List<IdToString>();
       
        // Create mock data
        Account acc = new Account(Name = 'Test Account', CVR__c = '12345678');
        insert acc;

        Case c = new Case(AccountId = acc.Id);
        insert c;

        Activation__c activation = new Activation__c(Case__c = c.Id);
        insert activation;

        Account_Phone_Number_Series__c series = new Account_Phone_Number_Series__c(
            Account__c = acc.Id,
            Number_Group__c = 'P',
            Number_Location__c = 'EKC',
            Product_Type__c = 'GSM'
        );
        insert series;

        List<Account_Phone_Number_Assignment__c> phoneAssignments = new List<Account_Phone_Number_Assignment__c>();
        for (Integer i = 0; i < 10; i++) {
            phoneAssignments.add(
                new Account_Phone_Number_Assignment__c(
                    Account__c = acc.Id, 
                    Account_Phone_Number_Series__c = series.Id,             
                    CTN_Number_Status__c = 'AR',
                    Phone_Number_Reservation_Status__c = '',
                    Phone_Number_Reservation_Error__c = null,
                    Activation_line__c = null,
                    Phone_Number__c = '4522222221' + i
                    ));
        }
        insert phoneAssignments;

        List<Activation_line__c> activationLines = new List<Activation_line__c>();
        for (Integer i = 0; i < 10; i++) {
            activationLines.add(
                new Activation_line__c(
                    Case__c = c.Id, 
                    Activation__c = activation.Id,
                    Phone_Number_Reservation_Status__c = '',
                    Phone_Number_Reservation_Error__c = null,
                    First_Name__c = 'Peter',
                    Last_Name__c = 'Griffin' + i,
                    Email__c = 'pg' + i + '@test.com',
                    Mobile_No__c = null                    
                    ));
        }
        insert activationLines;

        Map<Id, String> tmpMap = new  Map<Id, String>();
        tmpMap.put(activationLines.get(0).Id, phoneAssignments.get(0).Id);

        String parameters = JSON.serialize(new Map<String, Object>{'activationLineIdToAssignementId' => tmpMap});

        EventExecutor__e event = new EventExecutor__e(Parameters__c = parameters, RetryCount__c = 5);

        //ACT
        handler.execute(event);

        //ASSERT
        Account_Phone_Number_Assignment__c  updatedAssignment = (Account_Phone_Number_Assignment__c) dbMock.register.updated.get(1);
        Activation_Line__c updatedActivationLine = (Activation_Line__c) dbMock.register.updated.get(0);

        Assert.areEqual(2, dbMock.register.updated.size(), 'We update both activationline and assignment');
        Assert.areEqual(updatedAssignment.Activation_Line__c, updatedActivationLine.Id, 'Assignment and ActivationLine got related');
        Assert.areEqual(updatedAssignment.Phone_Number__c, updatedActivationLine.Mobile_No__c, 'ActivationLine got the number from the assignment');
        Assert.areEqual(
            updatedAssignment.Phone_Number_User__c, updatedActivationLine.First_Name__c + ' ' + updatedActivationLine.last_Name__c + ', ' + updatedActivationLine.email__c, 
            'Assignment phonenumberuser is correctly set');
    
        
    }

    /**
     * @description Tests that the execute method sets the status to success and
     * that the activationLine gets a phonenumber and that the assignment gets a relation to the activationline.
     * For and Open Series Assignment
     */
    @IsTest
    public static void execute_fixedSeriesNumber_assignsNumberToActivationLineAndRelationOnAssignment() {
        
        Mock numberClientMock = Mock.forType(NumberClient.class);
        MethodSpy reserveNumberDetailByMsisdnAndCVR = numberClientMock.spyOn('reserveNumberDetailByMsisdnAndCVR');
        NumberClientResponseDTO.NumberDetail responseWithNumber = new NumberClientResponseDTO.NumberDetail();
        responseWithNumber.data = new NumberClientResponseDTO.NumberData();
        responseWithNumber.data.id = '4522222222';
        reserveNumberDetailByMsisdnAndCvr.whenCalledWith(Argument.any(), Argument.any(), Argument.any()).thenReturn(responseWithNumber);

        NumberClient numberClient = (NumberClient) numberClientMock.stub;
        DatabaseService dbMock = new DatabaseService().mockDMLs();

        NumberActivationLinesExecutorHandler handler = new NumberActivationLinesExecutorHandler(numberClient, dbMock);

        List<NumberActivationLinesExecutorAction.InputVariables> inputVariables = new List<NumberActivationLinesExecutorAction.InputVariables>();
        NumberActivationLinesExecutorAction.InputVariables vars = new NumberActivationLinesExecutorAction.InputVariables();
        vars.chunkSize = 3;
        vars.activationLineIdToAssignementId = new List<IdToString>();
       
        // Create mock data
        Account acc = new Account(Name = 'Test Account', CVR__c = '12345678');
        insert acc;

        Case c = new Case(AccountId = acc.Id);
        insert c;

        Activation__c activation = new Activation__c(Case__c = c.Id);
        insert activation;

        Account_Phone_Number_Series__c series = new Account_Phone_Number_Series__c(
            Account__c = acc.Id,
            Number_Group__c = 'P',
            Number_Location__c = 'EKC',
            Product_Type__c = 'GSM'
        );
        insert series;

        List<Account_Phone_Number_Assignment__c> phoneAssignments = new List<Account_Phone_Number_Assignment__c>();
        for (Integer i = 0; i < 10; i++) {
            phoneAssignments.add(
                new Account_Phone_Number_Assignment__c(
                    Account__c = acc.Id, 
                    Account_Phone_Number_Series__c = series.Id,             
                    CTN_Number_Status__c = 'AA',
                    Phone_Number_Reservation_Status__c = '',
                    Phone_Number_Reservation_Error__c = null,
                    Activation_line__c = null,
                    Phone_Number__c = '4522222221' + i
                    ));
        }
        insert phoneAssignments;

        List<Activation_line__c> activationLines = new List<Activation_line__c>();
        for (Integer i = 0; i < 10; i++) {
            activationLines.add(
                new Activation_line__c(
                    Case__c = c.Id, 
                    Activation__c = activation.Id,
                    Phone_Number_Reservation_Status__c = '',
                    Phone_Number_Reservation_Error__c = null,
                    First_Name__c = 'Peter',
                    Last_Name__c = 'Griffin' + i,
                    Email__c = 'pg' + i + '@test.com',
                    Mobile_No__c = null                    
                    ));
        }
        insert activationLines;

        Map<Id, String> tmpMap = new  Map<Id, String>();
        tmpMap.put(activationLines.get(0).Id, phoneAssignments.get(0).Id);

        String parameters = JSON.serialize(new Map<String, Object>{'activationLineIdToAssignementId' => tmpMap});

        EventExecutor__e event = new EventExecutor__e(Parameters__c = parameters, RetryCount__c = 5);

        //ACT
        handler.execute(event);

        //ASSERT
        Assert.areEqual(2, dbMock.register.updated.size(), 'We update both activationline and assignment');

        Account_Phone_Number_Assignment__c  updatedAssignment = (Account_Phone_Number_Assignment__c) dbMock.register.updated.get(1);
        Activation_Line__c updatedActivationLine = (Activation_Line__c) dbMock.register.updated.get(0);

        Assert.areEqual(2, dbMock.register.updated.size(), 'We update both activationline and assignment');
        Assert.areEqual(updatedAssignment.Activation_Line__c, updatedActivationLine.Id, 'Assignment and ActivationLine got related');
         Assert.areEqual(
            updatedAssignment.Phone_Number_User__c, updatedActivationLine.First_Name__c + ' ' + updatedActivationLine.last_Name__c + ', ' + updatedActivationLine.email__c, 
            'Assignment phonenumberuser is correctly set');
    } 
}