force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/Account_Phone_Number_Assignment__c.object-meta.xml
<CustomObject>
    <description>Represents individual phone numbers within a series (DKT-45211).</description>
    <label>Account Phone Number Assignment</label>
    <nameField>
        <displayFormat>APNA-{000000000}</displayFormat>
        <label>Account Phone Number Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account_Phone_Number_Series__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number_Series__c</fullName>
    <label>Account Phone Number Series</label>
    <referenceTo>Account_Phone_Number_Series__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/CTN_Number_Status__c.field-meta.xml
<CustomField>
    <fullName>CTN_Number_Status__c</fullName>
    <description>CTN numbers as per given status. Status Description: 
AA - Assigned Available
AR - Assigned Reserved
AI - Assigned In Use
AS - Assigned Suspended</description>
    <label>CTN Number Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Error__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Error__c</fullName>
    <label>Phone Number Reservation Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/Account_Phone_Number_Series__c.object-meta.xml
<CustomObject>
    <description>Represents a series of phone numbers attached to a CVR account. (DKT-45211)</description>
    <label>Account Phone Number Series</label>
    <nameField>
        <displayFormat>APNS-{000000000}</displayFormat>
        <label>Account Phone Number Series Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Series</relationshipLabel>
    <relationshipName>Account_Phone_Number_Series</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FIX</fullName>
                <isActive>false</isActive>
                <label>FIX</label>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
                <isActive>false</isActive>
                <label>MSC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventExecutor__e/EventExecutor__e.object-meta.xml
<CustomObject>
    <label>EventExecutor</label>
    <pluralLabel>EventExecutors</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventExecutor__e/fields/Executor__c.field-meta.xml
<CustomField>
    <fullName>Executor__c</fullName>
    <description>A class name that implements IEventExecutable</description>
    <inlineHelpText>A class name that implements IEventExecutable</inlineHelpText>
    <label>Executor</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorException__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorException__c</fullName>
    <label>LastEventExecutorException</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorReplayId__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorReplayId__c</fullName>
    <label>LastEventExecutorReplayId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorUuid__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorUuid__c</fullName>
    <label>LastEventExecutorUuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>A JSON string that contains parameters that is used in the execute functions</description>
    <inlineHelpText>A JSON string that contains parameters that is used in the execute functions</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The counter with number of times executed has failed before</description>
    <inlineHelpText>The counter with number of times executed has failed before</inlineHelpText>
    <label>RetryCount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NumberReservationExecutorHandler.cls
/**
 * The NumberReservationExecutorHandler class is responsible for handling the reservation of phone numbers.
 * It implements the IEventExecutableHandler interface and is triggered by an EventExecutor__e event.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         27/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 27/07/2025
 */
public with sharing class NumberReservationExecutorHandler implements IEventExecutableHandler {
    private final NumberClient numberClient;
    private final DatabaseService databaseService;

    /**
     * Default constructor that initializes the NumberClient and DatabaseService using the SingletonFactory.
     */
    public NumberReservationExecutorHandler() {
        this(SingletonFactory.getFactory());
    }

    /**
     * Private constructor for dependency injection.
     * @param singletonFactory The SingletonFactory instance to use for creating dependencies.
     */
    private NumberReservationExecutorHandler(SingletonFactory singletonFactory) {
        this.numberClient = (NumberClient) singletonFactory.getOrRegisterSingleton(NumberClient.class);
        this.databaseService = (DatabaseService) singletonFactory.getOrRegisterSingleton(DatabaseService.class);
    }

    /**
     * Test-visible constructor for dependency injection during testing.
     * @param numberClient The NumberClient instance to use.
     * @param databaseService The DatabaseService instance to use.
     */
    @TestVisible
    private NumberReservationExecutorHandler(NumberClient numberClient, DatabaseService databaseService) {
        this.numberClient = numberClient;
        this.databaseService = databaseService;
    }

    /**
     * Executes the event handling logic. This method is called when an EventExecutor__e event is received.
     * It processes the phone number assignments, reserves them using the NumberClient, and updates their status.
     * @param event The EventExecutor__e event that triggered the handler.
     */
    public void execute(EventExecutor__e event) {
        // Log the execution start
        Logger.logInfo(String.format('execute( {0} )', new List<Object>{ event }));

        // Get the parameters from the event
        Parameters params = getParameters(event.Parameters__c);

        Map<Id, Account_Phone_Number_Assignment__c>  assignmentsMap;

        try {
            // Retrieve the phone number assignments from the database
            assignmentsMap = getAssignmentsMap(params.assignmentIds);
        } catch (QueryException ex) {
            // Log and throw an exception if there's an error querying the assignments
            Logger.logError('SOQL Error: ' + ex.getMessage());
            throw new NumberReservationExecutorHandlerException('SQOL Error finding assignment: ' + ex.getMessage());
        }

        // Iterate over each assignment and attempt to reserve the phone number
        for(String assignmentId : assignmentsMap.keySet()){
            Account_Phone_Number_Assignment__c assignment = assignmentsMap.get(assignmentId);
            
            try {
                // Call the NumberClient to reserve the phone number
                NumberClientResponseDTO.NumberDetail numberReservationResponse = numberClient.reserveNumberDetailByMsisdnAndCVR(
                    assignment.Phone_Number__c, 
                    assignment.Account__r.Cvr__c, 
                    assignment.Account_Phone_Number_Series__r?.Product_Type__c);

                // Check the response and update the assignment status accordingly
                if (numberReservationResponse.data != null &&
                    numberReservationResponse.data.id != null) {
                        assignment = setSuccessOnAssignment(assignment);
                } 
                else {
                    // Handle unexpected response
                    String errorMessage = String.format(
                        'numberReservationResponse( {0} , {1} ) response was not expected.' +
                        (assignmentsMap == null ? ' assignmentsMap is NULL.' : ''),
                        new List<Object>{ numberReservationResponse, assignmentsMap }
                    );

                    Logger.logInfo(errorMessage);

                    assignment = setErrorOnAssignment(assignment, errorMessage);
                }

                // Remove the assignment from the list of pending assignments
                params.assignmentIds.remove(assignmentId);
            } catch (HTTPException ex) {
                // Handle HTTP exceptions
                switch on ex.getStatusCode() {
                    when 500 {
                        Logger.logError(ex);
                    }when else{
                        params.assignmentIds.remove(assignmentId);
                    }
                }
                assignment = setErrorOnAssignment(assignment, ex.getMessage());
            } catch (System.CalloutException e) {
                // Handle callout exceptions
                Logger.logError(e);

                params.assignmentIds.remove(assignmentId);
                
                assignment = setErrorOnAssignment(assignment, e.getMessage());
            }
        }

        // Update the assignments in the database
        try {
            databaseService.updateRecords(assignmentsMap.values());
        } catch (DmlException ex) {
            Logger.logError('DML error updating assignmentToUpdate: ' + ex.getMessage());
            throw new NumberReservationExecutorHandlerException(
                'Error when updating assignmentToUpdate: ' + ex.getMessage()
            );
        }
        
        // If there are any remaining assignments, retry the process
        if(!params.assignmentIds.isEmpty() ){
            EventExecutor__e retryEventExecutor = new EventExecutor__e();
            retryEventExecutor.Parameters__c = JSON.serialize(params);
            retryEventExecutor.Executor__c = event.Executor__c;
            retryEventExecutor.RetryCount__c = event.RetryCount__c+1;
            retryEventExecutor.LastEventExecutorException__c = 'Events failed try to rerun!';
            retryEventExecutor.LastEventExecutorUuid__c = event.EventUuid;
            retryEventExecutor.LastEventExecutorReplayId__c = event.ReplayId;
            
        	EventBus.publish(retryEventExecutor);
        }
    }

    /**
     * Parses the JSON parameters from the event into a Parameters object.
     * @param parameters The JSON string containing the parameters.
     * @return A Parameters object.
     * @throws NumberReservationExecutorHandlerException if the parameters are invalid.
     */
    @testvisible
    private Parameters getParameters(String parameters) {
        Logger.logInfo(String.format('parseParameters( {0} )', new List<Object>{ parameters }));

        if (parameters == null) {
            throw new NumberReservationExecutorHandlerException('parameters cannot be null.');
        }

        Parameters params;
        
        try {
            // Attempt to deserialize the parameters into the Parameters class
            params = (Parameters) System.JSON.deserialize(parameters, Parameters.class);
        } catch (System.JSONException ex) {
            // Handle JSONException by throwing a custom handler exception
            Logger.logError('NumberReservationExecutorHandler', 'Failed to parse JSON parameters.' + ex);
            throw new NumberReservationExecutorHandlerException('Failed to parse JSON parameters.', ex);
        }

        // Validate that assignmentIds list is filled properly
        for (String assignId : params.assignmentIds) {
            if (String.isBlank(assignId)) {
                throw new NumberReservationExecutorHandlerException(
                    'assignmentIds is a required parameter and cannot be blank, empty, or null'
                );
            }
        }

        return params;
    }


    /**
     * Sets the assignment status to 'Success'.
     * @param assignment The assignment to update.
     * @return The updated assignment.
     */
    @TestVisible
    private Account_Phone_Number_Assignment__c setSuccessOnAssignment(Account_Phone_Number_Assignment__c assignment) {
        Logger.logInfo(String.format('setSuccessOnAssignment( {0} )', new List<Object>{ assignment }));
        if (assignment == null) {
            Logger.logError('Assignment is null.');
            return null;
        }

        assignment.Phone_Number_Reservation_Status__c = SFConstants.SUCCESS;
        assignment.Phone_Number_Reservation_Error__c = null;
        assignment.CTN_Number_Status__c = SFConstants.ASSIGNED_RESERVED;
        
        return assignment;
    }

    /**
     * Sets the assignment status to 'Error' and records the error message.
     * @param assignment The assignment to update.
     * @param errorMessage The error message to record.
     * @return The updated assignment.
     */
    @TestVisible
    private Account_Phone_Number_Assignment__c setErrorOnAssignment(Account_Phone_Number_Assignment__c assignment, String errorMessage) {
        if (assignment == null) {
            Logger.logError('Assignment is null. Cannot set error: ' + errorMessage);
            return null;
        }
        Logger.logInfo(
            String.format(
                'setErrorOnAssignment( {0}, {1} )',
                new List<Object>{ assignment, errorMessage }
            )
        );

        assignment.Phone_Number_Reservation_Status__c = SFConstants.ERROR;
        assignment.Phone_Number_Reservation_Error__c = errorMessage;
        
        return assignment;
    }

    /**
     * Retrieves a map of phone number assignments from the database.
     * @param assignmentIds A set of assignment IDs to retrieve.
     * @return A map of assignment IDs to Account_Phone_Number_Assignment__c objects.
     */
    private Map<Id, Account_Phone_Number_Assignment__c> getAssignmentsMap(Set<String> assignmentIds) {
        Logger.logInfo(String.format('getAssignmentsMap( {0} )', new List<Object>{ assignmentIds }));

        Map<Id, Account_Phone_Number_Assignment__c> assignmentsMap = new Map<Id, Account_Phone_Number_Assignment__c> ([
            SELECT
                Id,
                Account__c,
                Account_Phone_Number_Series__c,
                Phone_Number__c,
                Phone_Number_Reservation_Status__c,
                Phone_Number_Reservation_Error__c,
            	CTN_Number_Status__c,
            	Account__r.cvr__c,
                Account_Phone_Number_Series__r.Product_Type__c
            FROM Account_Phone_Number_Assignment__c
            WHERE Id  IN : assignmentIds
        ]);

        return assignmentsMap;
    }

    public class NumberReservationExecutorHandlerException extends Exception {}
    
    public class Parameters {
        public Set<String> assignmentIds;
    }
}