force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Rationale__c.field-meta.xml
<CustomField>
    <fullName>Rationale__c</fullName>
    <description>User story ID: 14
Used to describe why an Account without as CVR should be created</description>
    <inlineHelpText>Describe why this account is needed even though it does not have a CVR number. Please provide P-number or SE number if available</inlineHelpText>
    <label>Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Awaiting_user__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_user__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set automatically whenever an email is received related to the case. The flag can also be set manually by the user. Flag is used to make it possible to show an image on listviews, in order for the case to stick out.</description>
    <label>Awaiting user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerTestClass.cls
@IsTest
Public class ContentDocumentLinkTriggerTestClass {
    
    static testmethod void testmethod1(){
        Test.startTest();
        Account accA =new Account(Name='Test', Rationale__c = 'Test Account', CVR__c = '12345678');
        insert accA ; 

        Case cs = New Case(AccountId = AccA.Id, Awaiting_user__c = true,Priority = 'Medium',
                    Status = 'New', Origin = 'Internal Support', subject = 'Test Case');
        insert cs;
        
        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=cs.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;
        Test.stopTest();
        
    }
}