force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TDF_AccountUtils.cls
@IsTest
public with sharing class TDF_AccountUtils {
    public static Account createAccountWithCVR(String cvr) {
		Account account = new Account();
		account.Name = StringUtils.makeRandomStringNoNumerics(20);
		account.BillingCity = 'CP';
		account.BillingPostalCode = '2000';
		account.NumberOfEmployees = 10;
		account.BillingCountry = 'DK';
		account.BillingStreet = 'Holmbladsgade 133';
		account.Phone = '111';
		account.CVR__c = cvr;
		return account;
	}

	public static Account creatActiveAccountWithCVRAndOwner(){
		return creatActiveAccountWithCVRAndOwner('12345678');
	}

	public static Account creatActiveAccountWithCVRAndOwner(String cvr) {
		Profile prof = ProfileSelector.getProfileByProfileName(ProfileConstants.SYSTEM_ADMINISTRATOR);
        User usr = testDataFactory.createUser('standt', prof.Id);

		Account account = new Account();
		account.Name = StringUtils.makeRandomStringNoNumerics(20);
		account.BillingCity = 'CP';
		account.BillingPostalCode = '2000';
		account.BillingCountry = 'DK';
		account.BillingStreet = 'Holmbladsgade 133';
		account.Phone = '111';
		account.NumberOfEmployees = 10;
		account.CVR__c = cvr;
		account.Status__c = 'Active';
		account.OwnerId = usr.Id;
		return account;
	}

	public static List<Account> createListOfAccountsWithCVRAndOwner(Integer numberOfAccountsInList){
		List<Account> listOfAccounts = new List<Account>();

		Integer testCvr = 12345100;

		for(Integer i = 0; i < numberOfAccountsInList; i++){
			Account acc = createAccountWithCVR(testCvr + i + '');
			acc.Name = 'TEST ' + i;
			listOfAccounts.add(acc);
		}
		return listOfAccounts;
	}
}