force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Update_to_Contract_API__c.field-meta.xml
<CustomField>
    <fullName>Send_Update_to_Contract_API__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When set to true a Platform Event will be created containing Quote and Quote Line (Product) information which the Contract API subscribes to.</description>
    <label>Send Update to Contract API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@IsTest
private with sharing class AccountTriggerTest {

    private static final String TEST_CVR = '11223344';

    @IsTest
    private static void companyApiUpdateSuccess() {
        Account acc = TDF_AccountUtils.createAccountWithCVR(TEST_CVR);
      
        Test.startTest();
            insert acc;
        Test.stopTest();
        
        List<Account> insertedAccounts = [SELECT Id, CVR__c FROM Account WHERE Id = :acc.Id];
        Assert.isTrue(!insertedAccounts.isEmpty(), 'Account should be sent to Company API update');
    }   

    @IsTest
    private static void contractApiUpdateSuccess() {
        Account acc = TDF_AccountUtils.createAccountWithCVR(TEST_CVR);
        insert acc;
        
        Test.startTest();
            acc.Send_Update_to_Contract_API__c = true;
            update acc;
        Test.stopTest();
        
        List<Account> updatedAccounts = [SELECT Id, CVR__c FROM Account WHERE Id = :acc.Id];

        Assert.isTrue(!updatedAccounts.isEmpty(), 'Account should be sent to Contract API update');
    }
}