force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NumberSeriesRefreshActionTest.cls
/**
 * The NumberSeriesRefreshActionTest class is responsible for testing the NumberSeriesRefreshAction class.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         27/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 27/07/2025
 */
@IsTest
private with sharing class NumberSeriesRefreshActionTest {
    private static final List<String> CVR_LIST = new List<String>{
        '12345678',
        '87654321'
    };

    /**
     * @description Sets up the test data.
     */
    @TestSetup
    static void makeData() {
        // create the Accounts
        List<Account> testAccounts = new List<Account>();
        for (String cvr : CVR_LIST) {
            // create the Account
            Account testAccount = TDF_AccountUtils.createAccountWithCVR(cvr);
            testAccount.Status__c = 'Active';
            testAccounts.add(testAccount);
        }
        insert testAccounts;
        
        // TODO we need phone number series 
        // TODO we need phone number assignments
    }

    /**
     * @description Tests the refreshPhoneNumberSeries method.
     */
    @IsTest  
    private static void testRefreshPhoneNumberSeries() {
        // ARRANGE
        // re-query the accounts
        List<Account> testAccounts = [SELECT Id FROM Account WHERE CVR__c IN :CVR_LIST];        

        List<NumberSeriesRefreshAction.InputVariables> inputVariablesList = new List<NumberSeriesRefreshAction.InputVariables>();
        List<NumberSeriesRefreshAction.OutputVariables> outputVariables = new List<NumberSeriesRefreshAction.OutputVariables>();

        // for each account we create phone number series refresh action input variables
        for (Account testAccount : testAccounts) {
            NumberSeriesRefreshAction.InputVariables inputVariables = new NumberSeriesRefreshAction.InputVariables();
            inputVariables.inputAccount = testAccount;
            inputVariablesList.add(inputVariables);
        }

        // ACT
        Test.startTest();

        List<NumberSeriesRefreshAction.OutputVariables> outputVariablesListResult = NumberSeriesRefreshAction.refreshPhoneNumberSeries(inputVariablesList);

        Test.stopTest();

        // ASSERT
        Assert.areEqual(
            CVR_LIST.size(), 
            outputVariablesListResult.size(), 
            'We expected ' + CVR_LIST.size() + ' output variables to be returned'
        );

    }
}