force-app/main/default/objects/Account/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <description>User story ID: 10
User story: Create new CVR Account</description>
    <externalId>true</externalId>
    <inlineHelpText>An 8 digit unique code used to identify a company</inlineHelpText>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/Account_Phone_Number_Assignment__c.object-meta.xml
<CustomObject>
    <description>Represents individual phone numbers within a series (DKT-45211).</description>
    <label>Account Phone Number Assignment</label>
    <nameField>
        <displayFormat>APNA-{000000000}</displayFormat>
        <label>Account Phone Number Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Account_Phone_Number_Series__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number_Series__c</fullName>
    <label>Account Phone Number Series</label>
    <referenceTo>Account_Phone_Number_Series__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Activation_line__c.field-meta.xml
<CustomField>
    <fullName>Activation_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for the Activation Line Phone Number assignment</description>
    <label>Activation line</label>
    <referenceTo>Activation_line__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/CTN_Number_Status__c.field-meta.xml
<CustomField>
    <fullName>CTN_Number_Status__c</fullName>
    <description>CTN numbers as per given status. Status Description: 
AA - Assigned Available
AR - Assigned Reserved
AI - Assigned In Use
AS - Assigned Suspended</description>
    <label>CTN Number Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Error__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Error__c</fullName>
    <label>Phone Number Reservation Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_User__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_User__c</fullName>
    <label>Phone Number User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/Account_Phone_Number_Series__c.object-meta.xml
<CustomObject>
    <description>Represents a series of phone numbers attached to a CVR account. (DKT-45211)</description>
    <label>Account Phone Number Series</label>
    <nameField>
        <displayFormat>APNS-{000000000}</displayFormat>
        <label>Account Phone Number Series Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Phone Number Series</relationshipLabel>
    <relationshipName>Account_Phone_Number_Series</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/CVR__c.field-meta.xml
<CustomField>
    <fullName>CVR__c</fullName>
    <label>CVR</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Group__c.field-meta.xml
<CustomField>
    <fullName>Number_Group__c</fullName>
    <label>Number Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Number_Location__c.field-meta.xml
<CustomField>
    <fullName>Number_Location__c</fullName>
    <label>Number Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BRZ</fullName>
            </value>
            <value>
                <fullName>BUS</fullName>
            </value>
            <value>
                <fullName>EKC</fullName>
            </value>
            <value>
                <fullName>GOL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Series__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FIX</fullName>
                <isActive>false</isActive>
                <label>FIX</label>
            </value>
            <value>
                <fullName>GSM</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
                <isActive>false</isActive>
                <label>MSC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Phone_Number_Reservation_Error__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Error__c</fullName>
    <description>Will contain the error from the platform event number reservation execution</description>
    <label>Phone Number Reservation Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventExecutor__e/EventExecutor__e.object-meta.xml
<CustomObject>
    <label>EventExecutor</label>
    <pluralLabel>EventExecutors</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventExecutor__e/fields/Executor__c.field-meta.xml
<CustomField>
    <fullName>Executor__c</fullName>
    <description>A class name that implements IEventExecutable</description>
    <inlineHelpText>A class name that implements IEventExecutable</inlineHelpText>
    <label>Executor</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorException__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorException__c</fullName>
    <label>LastEventExecutorException</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorReplayId__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorReplayId__c</fullName>
    <label>LastEventExecutorReplayId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/LastEventExecutorUuid__c.field-meta.xml
<CustomField>
    <fullName>LastEventExecutorUuid__c</fullName>
    <label>LastEventExecutorUuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>A JSON string that contains parameters that is used in the execute functions</description>
    <inlineHelpText>A JSON string that contains parameters that is used in the execute functions</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventExecutor__e/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The counter with number of times executed has failed before</description>
    <inlineHelpText>The counter with number of times executed has failed before</inlineHelpText>
    <label>RetryCount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NumberAssignmentResetExecutorHandler.cls
/**
 * The NumberAssignmentResetExecutorHandler class is responsible resetting and unreserving numbers.
 * It is triggered by an activationline delete event and processes the assignments in batches.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         29/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 29/07/2025
 */
public with sharing class NumberAssignmentResetExecutorHandler implements IEventExecutableHandler {
    private final NumberClient numberClient;
    private final DatabaseService databaseService;

    /**
     * @description Default constructor that initializes the NumberClient and DatabaseService using the SingletonFactory.
     */
    public NumberAssignmentResetExecutorHandler() {
        this(SingletonFactory.getFactory());
    }

    /**
     * @description Private constructor for dependency injection.
     * @param singletonFactory The SingletonFactory instance to use for creating dependencies.
     */
    private NumberAssignmentResetExecutorHandler(SingletonFactory singletonFactory) {
        this.numberClient = (NumberClient) singletonFactory.getOrRegisterSingleton(NumberClient.class);
        this.databaseService = (DatabaseService) singletonFactory.getOrRegisterSingleton(DatabaseService.class);
    }

    /**
     * @description Test-visible constructor for dependency injection during testing.
     * @param numberClient The NumberClient instance to use.
     * @param databaseService The DatabaseService instance to use.
     */
    @TestVisible
    private NumberAssignmentResetExecutorHandler(NumberClient numberClient, DatabaseService databaseService) {
        this.numberClient = numberClient;
        this.databaseService = databaseService;
    }

    /**
     * @description This method is called when an event is received. It processes the phone number assignments
     * @param event The event that triggered the handler.
     */
    public void execute(EventExecutor__e event) {
        Logger.logInfo(String.format('execute( {0} )', new List<Object>{ event }));

        Parameters params = new Parameters();

        //This caused lot of debug time, always remember to initiated the collection, its very hard to see what causes the error if not.
        params.activationLineIdToNumber = new Map<Id, String>();       

        params = getParameters(event.Parameters__c);

        Map<String, Account_Phone_Number_Assignment__c>  assignmentsFromPhoneMap;
        Map<String, Account_Phone_Number_Assignment__c>  assignmentsFromActivationLineMap;

        try {
            Logger.logInfo(params.activationLineIdToNumber);
            assignmentsFromPhoneMap = getAssignmentsPhoneMap(params.activationLineIdToNumber);
            assignmentsFromActivationLineMap = getAssignmentsActivationLineMap(params.activationLineIdToNumber);
        } 
        catch (QueryException ex) {
            Logger.logError('SOQL Error: ' + ex.getMessage());
            throw new NumberAssignmentResetExecutorHandlerException('SQOL Error finding assignment: ' + ex.getMessage());
        }
        
        List<Account_Phone_Number_Assignment__c> assignmentsToUpdate = new List<Account_Phone_Number_Assignment__c>();
        
        Map<Id, String> retryResetActivationLineIdToNumber = new Map<Id, String>();
        
        for(Id activationLineId : params.activationLineIdToNumber.keySet()){
            String phoneNumber = params.activationLineIdToNumber.get(activationLineId);
            
            Account_Phone_Number_Assignment__c assignment = null;
            Account_Phone_Number_Assignment__c phoneAssignment = assignmentsFromPhoneMap.get(phoneNumber);
            Account_Phone_Number_Assignment__c activationLineAssignment = assignmentsFromActivationLineMap.get(activationLineId);
  
            try{
                if(phoneAssignment != null)
                    assignment = phoneAssignment;
                else if (activationLineAssignment != null)
                    assignment = activationLineAssignment;
                else {
                    Logger.logInfo('No assignment found for activation line id ' + activationLineId);
                    continue;
                }  

                //we only need to unreserve numbers in the fixed series
                //TODO: look in custom metadata to find the open series
                String defaultOpenSeriesLocation = SFConstants.DEFAULT_OPENSERIES_NUMBERLOCATION;
                String defaultOpenSeriesGroup = SFConstants.DEFAULT_OPENSERIES_PRODUCTGROUP;
                Boolean isOpenSeries = assignment.Account_Phone_Number_Series__r.Number_Group__c == defaultOpenSeriesGroup 
                    && assignment.Account_Phone_Number_Series__r.Number_Location__c == defaultOpenSeriesLocation;

                if(assignment.CTN_Number_Status__c == 'AR' && !isOpenSeries) {
                    NumberClientResponseDTO.NumberDetail numberUnreserveResponse = numberClient.unreserveNumberDetailByMsisdn(
                    addCountryCodeToPhoneNumber(assignment.Phone_Number__c));
               
                    if (numberUnreserveResponse.data != null && numberUnreserveResponse.data.id != null) {
                        assignment = resetAssignment(assignment);
                        assignment.CTN_Number_Status__c = numberUnreserveResponse.data.numberStatus;
                    } else {
                        String errorMessage = String.format(
                            'numberUnreserveResponse( {0} ) response was not expected.',
                            new List<Object>{ numberUnreserveResponse }
                        );
                        //If we end up here something is really off! Better log it
                        Logger.logInfo(errorMessage);

                        assignment = setNumberUnreserveErrorOnAssignment(assignment, errorMessage);
                    }
                } 
                //if its an open series we just need to reset, the status is already AR
                else if (assignment.CTN_Number_Status__c == 'AR' && isOpenSeries) { 
                    assignment = resetAssignment(assignment);
                    Logger.logInfo('assignment ' + assignment);
                }
            }catch (HTTPException ex) {
                switch on ex.getStatusCode() {
                    when 500 {
                        if (event.RetryCount__c < EventExecutorFinalizer.MAX_RETRY_COUNT) {
                            //We add it to retry! 
                            retryResetActivationLineIdToNumber.put( activationLineId, assignment.Id);
                        } else {
                            Logger.logInfo(
                                String.format(
                                    'We reached a maximum of retry. Halt execution for {0}',
                                    new List<Object>{ event }
                                )
                            );
                            Logger.logError(ex);
                        }
                    }
                }
                
                assignment = setNumberUnreserveErrorOnAssignment(assignment, ex.getMessage());
            }

            assignmentsToUpdate.add(assignment);
        }
        
        databaseService.updateRecords(assignmentsToUpdate);
        
                
        if( !retryResetActivationLineIdToNumber.isEmpty() ){
            EventExecutor__e retryEventExecutor = new EventExecutor__e();
            Parameters retryParams = new Parameters();
            retryParams.activationLineIdToNumber = retryResetActivationLineIdToNumber;
            retryEventExecutor.Parameters__c = JSON.serialize(retryParams);
            retryEventExecutor.Executor__c = event.Executor__c;
            retryEventExecutor.RetryCount__c = event.RetryCount__c+1;
            retryEventExecutor.LastEventExecutorException__c = 'Events failed try to rerun!';
            retryEventExecutor.LastEventExecutorUuid__c = event.EventUuid;
            retryEventExecutor.LastEventExecutorReplayId__c = event.ReplayId;
            
        	EventBus.publish(retryEventExecutor);
        }
    }

    private String addCountryCodeToPhoneNumber(string phoneNumber){
        if(phoneNumber.length() == 8){
            return '45' + phoneNumber;
        }
        return phoneNumber;  
    } 
 
    private Account_Phone_Number_Assignment__c setNumberUnreserveErrorOnAssignment(Account_Phone_Number_Assignment__c assignment, String errorMessage) {
        Logger.logInfo(
            String.format(
                'setNumberUnreserveErrorOnAssignment( {0}, {1} )',
                new List<Object>{ assignment, errorMessage }
            )
        );
        
        return assignment;
    }  

    /**
     * @description This method resets various values on the assignment.
     * @param assignment The assignment to reset.
     * @return The reset assignment.
     */
    @TestVisible
    private Account_Phone_Number_Assignment__c resetAssignment(Account_Phone_Number_Assignment__c assignment) {
        Logger.logInfo(String.format('resetAssignment( {0} )', new List<Object>{ assignment }));
        if (assignment == null) {
            Logger.logError('Assignment is null.');
            return null;
        }

        assignment.Phone_Number_Reservation_Status__c = '';
        assignment.Phone_Number_Reservation_Error__c = null;
        assignment.Activation_line__c = null;
        assignment.Phone_Number_User__c = null;

        return assignment;
    }
    
    /**
     * @description Parses the provided JSON Parameters 
     */
    @testvisible
    public Parameters getParameters(String parameters) {
        Logger.logInfo(String.format('parseParameters( {0} )', new List<Object>{ parameters }));

        if (parameters == null) {
            throw new NumberAssignmentResetExecutorHandlerException('parameters cannot be null.');
        }
        
        try{
            Parameters params = (Parameters) System.JSON.deserialize(parameters, NumberAssignmentResetExecutorHandler.Parameters.class);

            if (params.activationLineIdToNumber.isEmpty())  {
                throw new NumberAssignmentResetExecutorHandlerException(
                    String.format('Both activationLineId and number cannot be blank, empty or null', new List<Object>{ params })
                );
            }
            
            if( params.activationLineIdToNumber.containsKey(null) ){
                throw new NumberAssignmentResetExecutorHandlerException(
                    String.format('activationLineId cannot null', new List<Object>{ params })
                );
            }
  
        	return params;
        }catch(Exception ex){
            Logger.logError('NumberAssignmentResetExecutorHandler', new List<Object>{ ex });
            throw ex;
        }
    }

    /**
     * @description This method gets a map of assignments from a map of activation line IDs to assignment IDs.
     * @param mapOfactivationLineIdToNumber A map of activation line IDs to assignment IDs.
     * @return A map of assignment IDs to assignments.
     */
    private Map<String, Account_Phone_Number_Assignment__c> getAssignmentsPhoneMap(Map<Id, String> mapOfactivationLineIdToNumber) {
 
        Map<String, Account_Phone_Number_Assignment__c> assignmentsMap = new Map<String, Account_Phone_Number_Assignment__c>();
        
        List<Account_Phone_Number_Assignment__c> listOfAssignments = [
            SELECT
                Phone_Number__c,
                Account__c,
                Account_Phone_Number_Series__c,
                Id,
                Phone_Number_Reservation_Status__c,
                Phone_Number_Reservation_Error__c,
                CTN_Number_Status__c,
                Account__r.cvr__c,
                Account_Phone_Number_Series__r.Product_Type__c,
                Account_Phone_Number_Series__r.Number_Group__c, 
                Account_Phone_Number_Series__r.Number_Location__c, 
                Activation_Line__c
            FROM Account_Phone_Number_Assignment__c
            WHERE Phone_Number__c IN :mapOfactivationLineIdToNumber.values()];

        for(Account_Phone_Number_Assignment__c assignment : listOfAssignments){
            assignmentsMap.put(assignment.Phone_Number__c, assignment);  
        }

        return assignmentsMap;
    }

    private Map<String, Account_Phone_Number_Assignment__c> getAssignmentsActivationLineMap(Map<Id, String> mapOfactivationLineIdToNumber) {
 
        Map<String, Account_Phone_Number_Assignment__c> assignmentsMap = new Map<String, Account_Phone_Number_Assignment__c>();
        
        List<Account_Phone_Number_Assignment__c> listOfAssignments = [
            SELECT
                Activation_line__c,
                Phone_Number__c,
                Account__c,
                Account_Phone_Number_Series__c,
                Id,
                Phone_Number_Reservation_Status__c,
                Phone_Number_Reservation_Error__c,
                CTN_Number_Status__c,
                Account__r.cvr__c,
                Account_Phone_Number_Series__r.Product_Type__c,
                Account_Phone_Number_Series__r.Number_Group__c, 
                Account_Phone_Number_Series__r.Number_Location__c    
            FROM Account_Phone_Number_Assignment__c
            WHERE Activation_line__c IN :mapOfactivationLineIdToNumber.keyset()];

        for(Account_Phone_Number_Assignment__c assignment :listOfAssignments){
            assignmentsMap.put(assignment.Activation_line__c, assignment);    
        }

        return assignmentsMap;
    }
  
    public class Parameters {
        public Map<Id, String> activationLineIdToNumber;
    }

     public class NumberAssignmentResetExecutorHandlerException extends Exception {
    }
}