force-app/main/default/objects/Account/fields/Home_Office_Product_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Home_Office_Product_Preferences__c</fullName>
    <label>Home Office Product Preferences</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Office_Product_Preferences__mdt/Home_Office_Product_Preferences__mdt.object-meta.xml
<CustomObject>
    <label>Home Office Product Preference Option</label>
    <pluralLabel>Home Office Product Preference Options</pluralLabel>
</CustomObject>

force-app/main/default/objects/Home_Office_Product_Preferences__mdt/fields/Customer_Option__c.field-meta.xml
<CustomField>
    <fullName>Customer_Option__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if this is a product option customer can select</description>
    <label>Customer Option</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Home_Office_Product_Preferences__mdt/fields/Product_Codes__c.field-meta.xml
<CustomField>
    <fullName>Product_Codes__c</fullName>
    <description>List of product codes for this specific product option</description>
    <label>Product Codes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Office_Product_Preferences__mdt/fields/Product_Da_Translation__c.field-meta.xml
<CustomField>
    <fullName>Product_Da_Translation__c</fullName>
    <description>For Danish Translation</description>
    <label>Product Da Translation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Home_Office_Product_Preferences__mdt/fields/Product_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Product_Sequence__c</fullName>
    <description>Field is used for sorting i default sequence and as an internal code, instead of using name</description>
    <label>Product Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HomeOfficeSelector.cls
public without sharing class HomeOfficeSelector {
       
    @AuraEnabled(cacheable=true)
    public static List<Home_Office_Product_Preferences__mdt> getHomeOfficeProductOptions() {
        return [
            SELECT Label, Product_Da_Translation__c, Product_Codes__c, Product_Sequence__c 
            FROM Home_Office_Product_Preferences__mdt 
            WHERE Customer_Option__c = TRUE
            // WITH SECURITY_ENFORCED
            ORDER BY Product_Sequence__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static string getHomeOfficeProductOptionsRanking() {
        User userRecord = [SELECT Contact.AccountId, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
    
        String accId = userRecord.ContactId != null ? userRecord.Contact.AccountId : 'ERROR: User not found!';
    
        Account accountRecord = [SELECT Home_Office_Product_Preferences__c FROM Account WHERE Id = :accId];
    
        return accountRecord.Home_Office_Product_Preferences__c;
    }

    @AuraEnabled(cacheable=true)
    public static string getAccount() {
      // AccountWrapper retValue = new AccountWrapper();
      Id currUserId = UserInfo.getUserId();
  
      String accId = 'THIS IS A TEST';
      User userRecord = [
        SELECT Id, ContactId, Contact.AccountId
        FROM User
        WHERE Id = :currUserId
      ];
      if (userRecord.ContactId != null) {
        accId = userRecord.Contact.AccountId;
      } else {
        System.debug('ERROR: User not found!');
      }
      return accId;
    }
  
    @AuraEnabled(cacheable=true)
    public static string getOpportunity() {
      
      Id currUserId = UserInfo.getUserId();
      String oppId = 'Not found';

      User userRecord = [
        SELECT Id, ContactId, Contact.AccountId
        FROM User
        WHERE Id = :currUserId
      ];

      if (userRecord.ContactId != null) {
        
        List<OpportunityContactRole> oppContactRoleRecord = [
            SELECT Id, OpportunityId
            FROM OpportunityContactRole
            WHERE ContactId =:userRecord.ContactId AND Role = 'Sales Contact' 
        ];

        oppId = oppContactRoleRecord[0].OpportunityId;

      } else {
        System.debug('ERROR: User not found!');
      }
      
      return oppId;
    }


}