force-app/main/default/objects/Account/fields/Max_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Quote_Amount__c</fullName>
    <description>Amount set by Sergel. Sergel receive mail once Opportunity is in Proposal stage and will set Amount</description>
    <inlineHelpText>Amount set by Sergel - valid for 3 month - if a new evaluation of max amount to be quoted is necessary this can be done by ticking &apos;Request Credit Re-evaluation&apos;</inlineHelpText>
    <label>Max Quote Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <description>User story ID: 94</description>
    <inlineHelpText>Specify here which products are included in this opportunity</inlineHelpText>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteExtControllerTests.cls
@IsTest
private class QuoteExtControllerTests {
    private static final String TEST_CVR = '12345678';

    @TestSetup
    private static void makeData() {
        Account acc = TestDataFactory.createAccountWithCVR(TEST_CVR);
        acc.Status__c = 'Active';
        acc.Max_Quote_Amount__c = 100000;
        insert acc;

        Opportunity opp = TestDataFactory.createOpportunitiesForAccounts(1, new List<Account>{acc})[0];
        opp.Product_s_in_scope__c = '';
        update opp;

        SBQQ__Quote__c quote = TestDataFactory.createSingleQuote(acc.Id, opp.Id);
        quote.SBQQ__StartDate__c = System.today().addDays(10);
        insert quote;
    }
    
    @IsTest
    private static void testSubmit() {
        // get quote from makeDate;
        SBQQ__Quote__c quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];
        
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        con.onSubmit();
        Test.stopTest();

        quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];

        // assert that status is approved
        Assert.areEqual('Approved', quote.ApprovalStatus__c, 'Approval Status on Quote should be Approved');
    }    
    
    @IsTest
    private static void testSubmitExceptionStartDateInThePast() {        
        // get quote from makeDate and update the start date to be in the past
        SBQQ__Quote__c quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];
        quote.SBQQ__StartDate__c = System.today().addDays(-10);
        update quote;
        
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        con.onSubmit();
        Test.stopTest();
        
        quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];

        // assert that status is not approved
        Assert.areNotEqual('Approved', quote.ApprovalStatus__c, 'Approval Status on Quote should not be Approved');
    }

    
    @IsTest
    private static void testRecall() {
        // get quote from makeDate
        SBQQ__Quote__c quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];
        
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        con.onRecall();
        Test.stopTest();
        
        quote = QuoteSelector.getQuotesByAccountCVRs(new List<String> {TEST_CVR})[0];
        
        Assert.areEqual('Recalled', quote.ApprovalStatus__c, 'Approval Status on Quote should be Recalled');
    }
}