force-app/main/default/objects/Account/fields/Rationale__c.field-meta.xml
<CustomField>
    <fullName>Rationale__c</fullName>
    <description>User story ID: 14
Used to describe why an Account without as CVR should be created</description>
    <inlineHelpText>Describe why this account is needed even though it does not have a CVR number. Please provide P-number or SE number if available</inlineHelpText>
    <label>Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the specific activation line to a BAN (Billing Account).</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ActivationLinesAssignBANTest.cls
@IsTest
public with sharing class ActivationLinesAssignBANTest {

    @TestSetup
	static void createTestData() {
        Account acc = new Account(Name='Test Account',Rationale__c='Test');
        insert acc;

        Billing_Account__c ban = new Billing_Account__c(Account__c=acc.Id);
        insert ban;

        Case theCase = new Case();
        insert theCase;

        Activation__c activation = new Activation__c(Case__c=theCase.Id);
        insert activation;

        List<Activation_Line__c> testActivationLines = new List<Activation_Line__c>();
        for (Integer i = 0; i < 5; i++) {
            Activation_Line__c activationLine = new Activation_Line__c();
            activationLine.Activation__c = activation.Id;
            testActivationLines.add(activationLine);
        }
        insert testActivationLines;
    }

    @IsTest
    static void testAssignBAN() {
        // Get test data
        List<Activation_line__c> testActivationLines = [SELECT Id FROM Activation_line__c];
        Billing_Account__c ban = [SELECT Id FROM Billing_Account__c];

        // Call the assignBAN method
        ActivationLinesAssignBAN.InputClass input = new ActivationLinesAssignBAN.InputClass();
        input.activationLines = testActivationLines;
        input.ban = ban.Id;
        ActivationLinesAssignBAN.assignBAN(new List<ActivationLinesAssignBAN.InputClass>{input});

        // Verify that Billing_Account__c is correctly updated
        List<Activation_Line__c> updatedActivationLines = [SELECT Id, Billing_Account__c FROM Activation_Line__c WHERE Id IN :testActivationLines];
        for (Activation_Line__c activationLine : updatedActivationLines) {
            System.assertEquals(ban.Id  , activationLine.Billing_Account__c);
        }
    }
}