force-app/main/default/objects/Account/fields/Rationale__c.field-meta.xml
<CustomField>
    <fullName>Rationale__c</fullName>
    <description>User story ID: 14
Used to describe why an Account without as CVR should be created</description>
    <inlineHelpText>Describe why this account is needed even though it does not have a CVR number. Please provide P-number or SE number if available</inlineHelpText>
    <label>Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Billing_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Type__c</fullName>
    <defaultValue>&quot;General&quot;</defaultValue>
    <description>To determine if it&apos;s a home office or any other type of record</description>
    <label>Billing Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Home Office</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Default_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this Billing Account is the default Billing Account for the Account. Used in new Home Office flow where it is assigned as default on Activation Lines.</description>
    <label>Default Billing Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BillingAccountSelectorTest.cls
@IsTest
private class BillingAccountSelectorTest {

    @testSetup
    static void setup() {
        
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Rationale__c = 'Testing'
        );
        insert testAccount;
        
        Billing_Account__c testBillingAccount = new Billing_Account__c(
            Account__c = testAccount.Id,
            Billing_Account_Type__c = 'Home Office',
            Default_Billing_Account__c = true
        );
        insert testBillingAccount;
        
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            AccountId = testAccount.Id
        );
        insert testCase;

    }

    @IsTest
    static void testGetDefaultBanByAccountAndType() {
        // Retrieve test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Test.startTest();
        Billing_Account__c resultBillingAccount = BillingAccountSelector.getDefaultBanByAccountAndType(testAccount.Id, 'Home Office');
        Test.stopTest();
        System.assertEquals(true, resultBillingAccount!= null, 'Billing Account should be retrieved');
    }

    @IsTest
    static void testGetBansByAccountAndType() {
        // Retrieve test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Test.startTest();
        List<Billing_Account__c> result = BillingAccountSelector.getBansByAccountAndType(testAccount.Id, 'Home Office');
        Test.stopTest();
        System.assertEquals(1, result.size(), 'Expected only one billing account');
    }

    @IsTest
    static void testGetBansByCaseAndType() {
        // Retrieve test data
        Case testCase = [SELECT Id FROM Case WHERE Subject = 'Test Case'];
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Test.startTest();
        List<Billing_Account__c> result = BillingAccountSelector.getBansByCaseAndType(testCase.Id, 'Home Office');
        Test.stopTest();
        System.assertEquals(1, result.size(), 'Expected only one billing account');
    }
}