force-app/main/default/objects/Account/fields/Sales_Note_1__c.field-meta.xml
<CustomField>
    <fullName>Sales_Note_1__c</fullName>
    <description>Requested by Anders Yde, for Sales Play solution</description>
    <label>Sales Note 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Note_2__c.field-meta.xml
<CustomField>
    <fullName>Sales_Note_2__c</fullName>
    <description>Requested by Anders Yde, for Sales Play solution</description>
    <label>Sales Note 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Note_3__c.field-meta.xml
<CustomField>
    <fullName>Sales_Note_3__c</fullName>
    <description>Requested by Anders Yde, for Sales Play solution</description>
    <label>Sales Note 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_account_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_account_contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User Story ID: 15</description>
    <inlineHelpText>Check this box if the contact is Telia&apos;s primary contact with this account</inlineHelpText>
    <label>Primary account contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to keep contact details (name, phone, mobile, email) in sync across Leads and Contact.</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact must be related to the Existing Account</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Note_3__c.field-meta.xml
<CustomField>
    <fullName>Sales_Note_3__c</fullName>
    <label>Sales Note 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Play_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Play_Campaign_Name__c</fullName>
    <description>Populated by &apos;SalesPlayLeadCreator&apos; when using the &apos;Sales Play - Management&apos; flow</description>
    <label>Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Sales_Play.recordType-meta.xml
<RecordType>
    <fullName>Sales_Play</fullName>
    <active>true</active>
    <businessProcess>SalesPlay</businessProcess>
    <description>Used only for Sales Play Campaigns</description>
    <label>Sales Play</label>
</RecordType>

force-app/main/default/classes/SalesPlayLeadCreator.cls
public with sharing class SalesPlayLeadCreator {
    @TestVisible
    private static final String LEAD_STATUS = 'New';
    @TestVisible
    private static final String LEAD_SOURCE = 'Sales Play';

    @InvocableMethod(label='Create Leads' description='Returns leads for Sales Play!')
    public static List<List<Lead>> createLeads(List<InputClass> theList) {
        List<Lead> leads = new List<Lead>();       
        List<Lead> recalcedLeads = new List<Lead>();
        List<SObject> accounts = theList[0].accounts;
        String userId = theList[0].user;
        Id salesPlayRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Sales_Play').getRecordTypeId();

        for (SObject sObj : accounts) {
            Account account = (Account)sObj;
            Lead lead = new Lead();
            lead.Account__c = account.Id;
            lead.Sales_Note_1__c = account.Sales_Note_1__c;
            lead.Sales_Note_2__c = account.Sales_Note_2__c;
            lead.Sales_Note_3__c = account.Sales_Note_3__c;
            lead.Status = LEAD_STATUS;
            lead.Company = account.Name;
            lead.LeadSource = LEAD_SOURCE;
            lead.RecordTypeId = salesPlayRecordTypeId;
            lead.City = account.BillingCity;
            lead.Country = account.BillingCountry;
            lead.PostalCode = account.BillingPostalCode;
            lead.State = account.BillingState;
            lead.Street = account.BillingStreet;
            lead.Priority__c = theList[0].priority;
            lead.Sales_Play_Campaign_Name__c = theList[0].campaignName;
            
            lead.OwnerId = (userId == 'AccountOwner') ? account.OwnerId : userId;

            Contact contact = getContact(account.id);
            if (contact != null) {
                lead.FirstName = contact.FirstName;
                lead.LastName = contact.LastName;
                lead.Email = contact.Email;
                lead.Phone = contact.Phone;
                lead.MobilePhone = contact.MobilePhone;
                lead.Title = contact.Title;
                lead.Contact__c = contact.Id;
            } else {
                lead.LastName = 'Unknown';
            }
            
            leads.add(lead);
        }

        List<FormulaRecalcResult> results = Formula.recalculateFormulas(leads);

        for(FormulaRecalcResult result : results) {
            if(result.isSuccess()) {
                recalcedLeads.add((Lead)result.getSObject());
            }
        }

        List<List<Lead>> returnValue = new List<List<Lead>>();

        returnValue.add(recalcedLeads);

        return returnValue;
    }

    public static Contact getContact(String accountId) {
        Contact contact;
        try {
            contact = [SELECT id, FirstName, LastName, Email, Phone, MobilePhone, Title FROM Contact WHERE AccountId =: accountId WITH SECURITY_ENFORCED ORDER BY Primary_account_contact__c DESC, LastModifiedDate DESC LIMIT 1];
        } catch(Exception e) {
            contact = null;
        }
        return contact; 
    }

    public class InputClass {
        @InvocableVariable(required=true)
        public List<SObject> accounts;
        @InvocableVariable(required=true)
        public String user;
        @InvocableVariable(required=true)
        public String priority;
        @InvocableVariable(required=true)
        public String campaignName;
    }

}