force-app/main/default/objects/Account/fields/Sales_Play_Vesting_Reason__c.field-meta.xml
<CustomField>
    <fullName>Sales_Play_Vesting_Reason__c</fullName>
    <description>Used in Apex class SalesPlayManagementGetAccountsAction and Flow Sales_Play_Management to show the user the reason for an Account being filtered from the standard table. Values are populated temporarily by Apex and never saved.</description>
    <label>Sales Play Vesting Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Unqualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unqualified_Reason__c</fullName>
    <description>Field used for entering an Unqualified Reason, Used in Validation Rule</description>
    <inlineHelpText>If a Lead is Unqualified you are required to enter a reason</inlineHelpText>
    <label>Unqualified Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Time – Timing</fullName>
            </value>
            <value>
                <fullName>No need</fullName>
            </value>
            <value>
                <fullName>Missing product</fullName>
            </value>
            <value>
                <fullName>In binding with another provider</fullName>
            </value>
            <value>
                <fullName>Bad experience with Telia</fullName>
            </value>
            <value>
                <fullName>No interest - other</fullName>
            </value>
            <value>
                <fullName>Poor lead quality</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Bad experience with Norlys</fullName>
                <isActive>false</isActive>
                <label>Bad experience with Norlys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <description>User Story ID: 45</description>
    <inlineHelpText>The reason we lost the business</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Our relation to the customer</fullName>
                <label>Manglende relationer</label>
            </value>
            <value>
                <fullName>Our Products are missing features</fullName>
                <label>Manglende produkter (beskriv i Other Loss Reason)</label>
            </value>
            <value>
                <fullName>Onboarding was not strong enough</fullName>
                <label>Mangelfuld implementering</label>
            </value>
            <value>
                <fullName>Customer Service was not good enough</fullName>
                <label>Mangelfuld kundeservice</label>
            </value>
            <value>
                <fullName>Our prices are too high</fullName>
                <label>Pris</label>
            </value>
            <value>
                <fullName>Mangelfuld subsidie</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <label>Opgivet</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Andet/Ved ikke (beskriv i Other Loss Reason)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesPlayManagementGetAccountsActionTest.cls
@IsTest
private with sharing class SalesPlayManagementGetAccountsActionTest {
	private static final String TEST_CVR = '12345678';
	private static final Integer AMOUNT_OF_MONTHS_DATE_FILTER = 6;
	private static final List<String> FORMATTING_ARGUMENTS = new List<String>{String.valueOf(AMOUNT_OF_MONTHS_DATE_FILTER)};

	//@TestSetup
	private static void makeData() {
		Account acc = TestDataFactory.createAccountWithCVR(TEST_CVR);
		acc.Status__c = 'Active';
		insert acc;
	}

	@IsTest
	private static void testAccountWithNoOpportunityOrLead() {
		makeData();

		Account acc = AccountSelector.getByCVR(TEST_CVR);
		
		SalesPlayManagementGetAccountsAction.Request request = new SalesPlayManagementGetAccountsAction.Request();
		request.amountOfMonthsForDateFilter = AMOUNT_OF_MONTHS_DATE_FILTER;
		request.accounts = new List<Account>{acc};

		Test.startTest();
		List<SalesPlayManagementGetAccountsAction.Response> responses = SalesPlayManagementGetAccountsAction.getAccountCollections(
			new List<SalesPlayManagementGetAccountsAction.Request>{request}
		);
		Test.stopTest();

		Assert.areEqual(1, responses.size(), 'One response should be returned');

		SalesPlayManagementGetAccountsAction.Response response = responses[0];
		Assert.areEqual(1, response.accountsNotInVestingPeriod.size(), 'One Account not in vesting period should be returned');
		Assert.isTrue(response.accountsInVestingPeriod.isEmpty(), 'No Accounts in vesting period should be returned');
	}

	@IsTest
	private static void testOneAccountNotInVestingPeriodAndTwoInVestingPeriod() {
		makeData();

		Account accNotInVestingPeriod = AccountSelector.getByCVR(TEST_CVR);

		Account accWithLead = TestDataFactory.createAccountWithCVR('12348765');
		insert accWithLead;
		TestDataFactory.createSalesPlayLeadsForAccounts(1, new List<Account>{accWithLead});

		Account accWithOpportunity = TestDataFactory.createAccountWithCVR('43215678');
		insert accWithOpportunity;
		TestDataFactory.createOpportunitiesForAccounts(1, new List<Account>{accWithOpportunity});

		SalesPlayManagementGetAccountsAction.Request request = new SalesPlayManagementGetAccountsAction.Request();
		request.amountOfMonthsForDateFilter = AMOUNT_OF_MONTHS_DATE_FILTER;
		request.accounts = new List<Account>{accNotInVestingPeriod, accWithLead, accWithOpportunity};

		Test.startTest();
		List<SalesPlayManagementGetAccountsAction.Response> responses = SalesPlayManagementGetAccountsAction.getAccountCollections(
			new List<SalesPlayManagementGetAccountsAction.Request>{request}
		);
		Test.stopTest();

		Assert.areEqual(1, responses.size(), 'One response should be returned');

		SalesPlayManagementGetAccountsAction.Response response = responses[0];
		Assert.areEqual(1, response.accountsNotInVestingPeriod.size(), 'One Account not in vesting period should be returned');
		Assert.areEqual(2, response.accountsInVestingPeriod.size(), 'Two Accounts in vesting period should be returned');
	}

	@IsTest
	private static void testAccountWithOpenAndClosedLostOpportunities() {
		makeData();

		Account acc = AccountSelector.getByCVR(TEST_CVR);
		List<Opportunity> opportunities = TestDataFactory.createOpportunitiesForAccounts(2, new List<Account>{acc});
		opportunities[0].StageName = 'Closed Lost';
		opportunities[0].Loss_Reason__c = 'Opgivet';
		update opportunities[0];

		SalesPlayManagementGetAccountsAction.Request request = new SalesPlayManagementGetAccountsAction.Request();
		request.amountOfMonthsForDateFilter = AMOUNT_OF_MONTHS_DATE_FILTER;
		request.accounts = new List<Account>{acc};

		Test.startTest();
		List<SalesPlayManagementGetAccountsAction.Response> responses = SalesPlayManagementGetAccountsAction.getAccountCollections(
			new List<SalesPlayManagementGetAccountsAction.Request>{request}
		);
		Test.stopTest();

		Assert.areEqual(1, responses.size(), 'One response should be returned');

		SalesPlayManagementGetAccountsAction.Response response = responses[0];
		Assert.isTrue(response.accountsNotInVestingPeriod.isEmpty(), 'No Account not in vesting period should be returned');
		Assert.areEqual(1, response.accountsInVestingPeriod.size(), 'One Account in vesting period should be returned');
		
		String vestingReason = response.accountsInVestingPeriod[0].Sales_Play_Vesting_Reason__c;
		Assert.isTrue(
			vestingReason.contains(SalesPlayManagementGetAccountsAction.VESTING_REASON_ACTIVE_OPPORTUNITY),
			'Vesting reason should contain active Opportunity text'
		);
		Assert.isTrue(
			vestingReason.contains(String.format(SalesPlayManagementGetAccountsAction.VESTING_REASON_OPPORTUNITY_LOST_N_MONTHS, FORMATTING_ARGUMENTS)),
			'Vesting reason should contain closed lost Opportunity text'
		);
	}

	@IsTest
	private static void testAccountWithOpenAndUnqualifiedLeads() {
		makeData();

		Account acc = AccountSelector.getByCVR(TEST_CVR);
		List<Lead> leads = TestDataFactory.createSalesPlayLeadsForAccounts(2, new List<Account>{acc});
		leads[0].Status = SalesPlayManagementGetAccountsAction.LEAD_STATUS_UNQUALIFIED;
		leads[0].Unqualified_Reason__c = Lead.Unqualified_Reason__c.getDescribe().getPicklistValues()[0].getValue();
		update leads[0];

		SalesPlayManagementGetAccountsAction.Request request = new SalesPlayManagementGetAccountsAction.Request();
		request.amountOfMonthsForDateFilter = AMOUNT_OF_MONTHS_DATE_FILTER;
		request.accounts = new List<Account>{acc};

		Test.startTest();
		List<SalesPlayManagementGetAccountsAction.Response> responses = SalesPlayManagementGetAccountsAction.getAccountCollections(
			new List<SalesPlayManagementGetAccountsAction.Request>{request}
		);
		Test.stopTest();

		Assert.areEqual(1, responses.size(), 'One response should be returned');

		SalesPlayManagementGetAccountsAction.Response response = responses[0];
		Assert.isTrue(response.accountsNotInVestingPeriod.isEmpty(), 'No Account not in vesting period should be returned');
		Assert.areEqual(1, response.accountsInVestingPeriod.size(), 'One Account in vesting period should be returned');
		String vestingReason = response.accountsInVestingPeriod[0].Sales_Play_Vesting_Reason__c;
		Assert.isTrue(
			vestingReason.contains(SalesPlayManagementGetAccountsAction.VESTING_REASON_OPEN_LEAD),
			'Vesting reason should contain open Lead text'
		);
		Assert.isTrue(
			vestingReason.contains(String.format(SalesPlayManagementGetAccountsAction.VESTING_REASON_LEAD_UNQUALIFIED_N_MONTHS, FORMATTING_ARGUMENTS)),
			'Vesting reason should contain unqualified Lead text'
		);
	}

	//TODO: khp fix unittest IMPORTANT FLOW INVOLVED
	// @IsTest
	// private static void testAccountWithQualifiedLeadAndClosedWonOpportunity() {
	// 	makeData();

	// 	Account acc = AccountSelector.getByCVR(TEST_CVR);
	// 	Lead lead = TestDataFactory.createSalesPlayLeadsForAccounts(1, new List<Account>{acc})[0];
	// 	lead.Status = SalesPlayManagementGetAccountsAction.LEAD_STATUS_QUALIFIED;
	// 	update lead;

	// 	Opportunity opp = TestDataFactory.createOpportunitiesForAccounts(1, new List<Account>{acc})[0];

	// 	SBQQ__Quote__c quote = TestDataFactory.createSingleQuote(acc.Id, opp.Id);
	// 	quote.SBQQ__StartDate__c = System.today().addDays(10);
	// 	insert quote;

	// 	TestDataFactory.createQuoteLineRecordsForQuote(1, new List<SBQQ__Quote__c>{quote}, 1, 1, false);

	// 	opp.SBQQ__PrimaryQuote__c = quote.Id;
	// 	opp.StageName = 'Closed Won';
	// 	update opp;

	// 	SalesPlayManagementGetAccountsAction.Request request = new SalesPlayManagementGetAccountsAction.Request();
	// 	request.amountOfMonthsForDateFilter = AMOUNT_OF_MONTHS_DATE_FILTER;
	// 	request.accounts = new List<Account>{acc};

	// 	Test.startTest();
	// 	List<SalesPlayManagementGetAccountsAction.Response> responses = SalesPlayManagementGetAccountsAction.getAccountCollections(
	// 		new List<SalesPlayManagementGetAccountsAction.Request>{request}
	// 	);
	// 	Test.stopTest();

	// 	Assert.areEqual(1, responses.size(), 'One response should be returned');

	// 	SalesPlayManagementGetAccountsAction.Response response = responses[0];
	// 	Assert.isTrue(response.accountsNotInVestingPeriod.isEmpty(), 'No Account not in vesting period should be returned');
	// 	Assert.areEqual(1, response.accountsInVestingPeriod.size(), 'One Account in vesting period should be returned');
	// 	String vestingReason = response.accountsInVestingPeriod[0].Sales_Play_Vesting_Reason__c;
	// 	Assert.isTrue(
	// 		vestingReason.contains(String.format(SalesPlayManagementGetAccountsAction.VESTING_REASON_LEAD_QUALIFIED_N_MONTHS, FORMATTING_ARGUMENTS)),
	// 		'Vesting reason should contain qualified Lead text'
	// 	);
	// 	Assert.isTrue(
	// 		vestingReason.contains(String.format(SalesPlayManagementGetAccountsAction.VESTING_REASON_OPPORTUNITY_WON_N_MONTHS, FORMATTING_ARGUMENTS)),
	// 		'Vesting reason should contain closed won Opportunity text'
	// 	);
	// }
}