force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>IF( Mobile_Part_of_Contract__c ,&quot;Mobile&quot;, IF( Fastnet_Part_of_Contract__c ,&quot;Fastnet&quot;, IF(Data_Part_of_Contract__c, &quot;Data&quot; ,&quot;&quot;)))</formula>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Opportunity_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity_Creation_Date__c</fullName>
    <description>Date when a renewal Opportunity should be created automatically. Set by a Flow on Contract creation.</description>
    <label>Renewal Opportunity Creation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <description>Added for Home Office</description>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Framework Agreement</fullName>
            </value>
            <value>
                <fullName>Summary Contract Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>These field has been created to hold 255 signs of additional information that might be useful in problem solving of this error.</description>
    <inlineHelpText>Additional helpful information like name of class/flow ect.</inlineHelpText>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Contract_RenewalOpportunity.cls
public class Contract_RenewalOpportunity implements Database.Batchable<sObject>{
    public List<Id> recordsId; 
   @InvocableMethod(label='Create renewal opportunity from Contracts' description='Create renewal opportunity from Contracts')
   public static list<id> Contract_RenewalOpportunity_Batch(list <id> recordId)
        {
            Contract_RenewalOpportunity ProcessBatch = new Contract_RenewalOpportunity();
            //ID batchprocessid = Database.executeBatch(ProcessBatch);
            String cronID = System.scheduleBatch(ProcessBatch, 'Creating renewal opportunity '+ System.now(), 1,100); 
            return recordId;
        }
      
   public Database.querylocator start(Database.BatchableContext BC){
   
         String squery = 'select id from Contract where Renewal_Opportunity_Creation_Date__c <= TODAY and SBQQ__RenewalForecast__c = false and ' + 
         				 ' EndDate != null and EndDate <= NEXT_N_DAYS:365 and StartDate!= null and AccountId != null and ContractTerm != null and ' +
                         ' Status = \'Activated\' and Account.Status__c = \'Active\' and Contract_Type__c = \'Mobile\' ' ;

        return Database.getQueryLocator(squery);
    }
    
    
    public void execute(Database.BatchableContext BC, List<Contract> scope){
    List<Contract> ContractUpdateList = new List<Contract>();    
      try
        {
  
        for(Contract c : scope)
          { 
              c.SBQQ__RenewalForecast__c = true;
              ContractUpdateList.add(c);
           }        
          if(ContractUpdateList.size()>0)
              { 
               	update ContractUpdateList;
              } 
        }
        catch(Exception e){
            System_Log__c  logerror = new System_Log__c (Origin__c  = 'Apex',Error_Body__c = e.getMessage() + 'Line:' + e.getLineNumber(),Additional_Information__c = 'Contract_RenewalOpportunity');
            insert logerror; 
        }  
    }
    
        
    public void finish(Database.BatchableContext BC){

    } 
    
       
}