force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK( Street_Name__c ), &apos;&apos;, (Street_Name__c + &apos; &apos; + Number__c)) +
IF(ISBLANK( Floor__c ), &apos;&apos;, (&apos;, &apos; + Floor__c)) +
IF(ISBLANK( Door__c ), &apos;&apos;, IF((FIND(&apos;.&apos;, Floor__c)) &gt; 0, (&apos; &apos; + Door__c), (&apos;. &apos; + Door__c))) +
IF(ISBLANK( ZIP_Code__c ), &apos;&apos;, (&apos;, &apos; + ZIP_Code__c)) +
IF(ISBLANK( City__c ), &apos;&apos;, (&apos; &apos; + City__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address_Wash_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Wash_Status__c</fullName>
    <label>Address Wash Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Not Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/addressWash_Category__c.field-meta.xml
<CustomField>
    <fullName>addressWash_Category__c</fullName>
    <label>Address Wash Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LineInquiryTest.cls
/**
 * 
 * @author keh
 * @since 10032025
 */
@isTest
private class LineInquiryTest {

    private static final String TEST_CVR = '12345678';

    /**
     * setup
     */
    @testSetup
    static void setup(){
        Profile prof = ProfileSelector.getProfileByProfileName(ProfileConstants.SYSTEM_ADMINISTRATOR);
		User usr = testDataFactory.createUser('standt', prof.Id);

		Account acc = TDF_AccountUtils.createAccountWithCVR(TEST_CVR);
        acc.Status__c = 'Active';
		acc.OwnerId = usr.Id;
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.StageName = 'Qualification';
        opp.CloseDate = Date.newInstance(2024, 12, 31);
        opp.AccountId = acc.Id;
        insert opp;
        
        Location_Line__c ll = new Location_Line__c();
        ll.Opportunity__c = opp.Id;
        ll.Street_Name__c = 'Risbystræde';
        ll.Number__c = '19';
        ll.ZIP_Code__c = '2620';
        ll.City__c = 'Albertslund';
        
        insert ll;
    }

    /**
     * 
     */
    @isTest
    static void theCall_correctWashCategory_returnsCorrectLocationLine() { 
        //ARRANGE
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='Test Opportunity' LIMIT 1];
        Location_Line__c line = [SELECT Address__c FROM Location_Line__c WHERE Opportunity__c =: opp.Id limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new LineInquiryCalloutMock());
        
        //ACT
        Location_Line__c res = LineInquiry.theCall(line);
        Test.stopTest();

        //ASSERT
        System.assertEquals('A', res.addressWash_Category__c, 'Address Wash Category does not match');        
    }

    /**
    * static void callDawa_setWash_onAllLines() { 
     */
    @isTest
    static void callDawa_setWash_onAllLines() { 
        //ARRANGE
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='Test Opportunity' LIMIT 1];
        Location_Line__c line = [SELECT Address__c FROM Location_Line__c WHERE Opportunity__c =: opp.Id limit 1];
        List<Location_Line__c> innerList = new List<Location_Line__c>();
        innerList.add(line);
        List<List<Location_Line__c>> outerList = new List<List<Location_Line__c>>();
        outerList.add(innerList);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new LineInquiryCalloutMock());
        
        //ACT
        LineInquiry.callDawa(outerList);
        Test.stopTest();

        //ASSERT
        line = [SELECT Address__c, Address_Wash_Status__c FROM Location_Line__c WHERE Opportunity__c =: opp.Id limit 1];
        System.assertEquals('Valid', line.Address_Wash_Status__c);        
    }






}