force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeletePOQItemsTest.cls
/**
 * 
 * @author keh
 * @since 13032025
 */
@isTest
private class DeletePOQItemsTest {
    private static final String TEST_CVR = '12345678';

    /**
     * setup method
     *  - create user
     *  - create account
     *  - create opportunity
     *  - create location line
     */
    @testSetup
    static void setup(){
        Profile prof = ProfileSelector.getProfileByProfileName(ProfileConstants.SYSTEM_ADMINISTRATOR);
        User usr = testDataFactory.createUser('standt', prof.Id);

        Account acc = TDF_AccountUtils.createAccountWithCVR(TEST_CVR);
        acc.Status__c = 'Active';
		acc.OwnerId = usr.Id;
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.StageName = 'Qualification';
        opp.CloseDate = Date.newInstance(2024, 12, 31);
        opp.AccountId = acc.Id;
        insert opp;

        Location_Line__c ll = new Location_Line__c();
        ll.Street_Name__c = 'Risbystræde';
        ll.Number__c = '19';
        ll.ZIP_Code__c = '2620';
        ll.City__c = 'Albertslund';
        ll.Opportunity__c = opp.Id;
        insert ll;
        

        POQ_Item__c pi = new POQ_Item__c();
        pi.Name = 'Test POQ Item';
        pi.Location_Line__c = ll.Id;
        insert pi;
    }

    /**
     * deleteItems_locationWithItems_deletesAllItems
     */
    @isTest 
    static void deleteItems_locationWithItems_deletesAllItems() {
        //ARRANGE
        Location_Line__c ll = [SELECT Id, Street_Name__c, Number__c, ZIP_Code__c, City__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde'];
        List<Location_Line__c> list1 = new List<Location_Line__c>();
        list1.add(ll);
        List<List<Location_Line__c>> list2 = new List<List<Location_Line__c>>();
        list2.add(list1);

        //ACT
        DeletePOQItems.deleteItems(list2);

        //ASSERT
        ll = [SELECT Id, Street_Name__c, Number__c, ZIP_Code__c, City__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde'];
        List<POQ_Item__c> POQ_Items = [SELECT Id FROM POQ_Item__c WHERE Location_Line__c = :ll.Id];
        
        System.Assert(POQ_Items.size() == 0);
    }
}