force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Case_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Account_ID__c</fullName>
    <formula>CASESAFEID(Case__r.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Installation_address__c.field-meta.xml
<CustomField>
    <fullName>Installation_address__c</fullName>
    <inlineHelpText>Customer address where site will be documented in SmallWorld</inlineHelpText>
    <label>Installation address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <formula>CASESAFEID(Activation__r.Case__r.Opportunity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>How far along the activation of this line item has progressed</description>
    <inlineHelpText>How far along the activation of this line item has progressed</inlineHelpText>
    <label>Activation progress</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activation_line_progress</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installation_Address__c/Installation_Address__c.object-meta.xml
<CustomObject>
    <description>Installation address for Wholesale orders</description>
    <label>Installation Address</label>
    <nameField>
        <displayFormat>IA-{00000000}</displayFormat>
        <label>Installation Address No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Address__c/fields/Installation_Address__c.field-meta.xml
<CustomField>
    <fullName>Installation_Address__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Installation_Address__c/&quot;&amp;Id&amp;&quot;/view&quot;,
IF(ISBLANK(Secondary_Street__c), 
    IF(ISBLANK(Primary_Street__c), Name ,Primary_Street__c &amp; &quot; &quot; &amp;  Primary_Street_Number__c ),
     Primary_Street__c &amp;&quot; to &quot;&amp; Secondary_Street__c),&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The QuoteLine that resulted from this LocationLine.</description>
    <inlineHelpText>The QuoteLine that resulted from this LocationLine.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VAS_product__c.field-meta.xml
<CustomField>
    <fullName>VAS_product__c</fullName>
    <label>VAS product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_VAS_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates to which case is the opportunity related. Case will be created by a flow when the Opportunity is closed won and this field will be populated with the same flow.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Activation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Activation_Record_Type__c</fullName>
    <description>The type of activation, if any, that is required for this product</description>
    <inlineHelpText>Do activation agents need to do anything in order to activate this product? If yes, which category does the product fit into? If no, set to &quot;No activation needed&quot;.</inlineHelpText>
    <label>Activation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No activation needed</fullName>
            </value>
            <value>
                <fullName>DSL/Coax</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
            <value>
                <fullName>Home office</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>UC</fullName>
            </value>
            <value>
                <fullName>SMS manager</fullName>
            </value>
            <value>
                <fullName>4G</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Service packages</fullName>
            </value>
            <value>
                <fullName>Firewall</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>DDoS</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
            <value>
                <fullName>Erhvervsinternet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDF_HomeOfficeUtils.cls
/** 
 * Test Data Factory class used for generating test data for Home Office related scenario.
 * 
 * @author  Kirstine Nielsen
 * @since   07-05-2025
 * @see     https://jira.atlassian.teliacompany.net/browse/DKT-44508
 */
public with sharing class TDF_HomeOfficeUtils {
    
    /**
     * will create account(s). Will create one per account of:
     * - Opportunity
     * - Quote
     * - Quote Line
     * - Activation
     * - Activation Line
     * - Location Line
     * - Case
     * 
     * @param list of cvr
     */
    public static void makeDataFramework(List<String> cvrList) {

        List<Account> testAccounts = new List<Account>();
        for (String cvr : cvrList) {
            // create the Account
            Account testAccount = TDF_AccountUtils.createAccountWithCVR(cvr);
            testAccount.Status__c = 'Active';
            testAccounts.add(testAccount);
        }
        insert testAccounts;

        // we create 1 Opportunity per Account
        List<Opportunity> testOpportunities = TDF_OpportunityUtils.createHomeOfficeOpportunityForAccounts(
            testAccounts, 
            HomeOfficeConstants.AGREEMENT_TYPE_FRAMEWORK
        );
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>(testOpportunities);

        Map<Id, List<Opportunity>> accountIdToOpportunitiesMap = new Map<Id, List<Opportunity>>();
        for (Opportunity testOpportunity : testOpportunities) {
            if (!accountIdToOpportunitiesMap.containsKey(testOpportunity.AccountId)) {
                List<Opportunity> opportunitiesPerAccount = new List<Opportunity>();
                opportunitiesPerAccount.add(testOpportunity);
                accountIdToOpportunitiesMap.put(testOpportunity.AccountId, opportunitiesPerAccount);
            } else {
                // key exists
                accountIdToOpportunitiesMap.get(testOpportunity.AccountId).add(testOpportunity);
            }
        }

        // create 1 Quote per opp
        List<SBQQ__Quote__c> testQuotes = new List<SBQQ__Quote__c>();        
        for (Account testAccount : testAccounts) {
            for (Opportunity opp : accountIdToOpportunitiesMap.get(testAccount.Id)) {
                SBQQ__Quote__c testQuote = TDF_QuoteUtils.createSingleQuote(testAccount.Id, opp.Id);
                testQuotes.add(testQuote);
            }
        }
        insert testQuotes;
        
        Map<Id, SBQQ__Quote__c> opportunityIdToQuoteMap = new Map<Id, SBQQ__Quote__c>();
        for (SBQQ__Quote__c testQuote : testQuotes) {
            if (!opportunityIdToQuoteMap.containsKey(testQuote.SBQQ__Opportunity2__c)) {
                opportunityIdToQuoteMap.put(testQuote.SBQQ__Opportunity2__c, testQuote);
            }
        }

        // set the primary quote field on the opp
        testOpportunities = [
            SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c 
            FROM Opportunity
        ];
        for (Opportunity testOpportunity : testOpportunities) {
            if (opportunityIdToQuoteMap.containsKey(testOpportunity.Id)) {
                testOpportunity.SBQQ__PrimaryQuote__c = opportunityIdToQuoteMap.get(testOpportunity.Id).Id;
            }
        }
        update testOpportunities;

        // we need Home Office Products, insert and return
        Integer numberOfDifferentProducts = 1;
        List<Product2> listOfProductsToUse = TDF_ProductUtils.createHomeOfficeProducts(numberOfDifferentProducts);
        // we need to set the ProductAPI_Telia_Product_Id__c to HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03
        listOfProductsToUse[0].ProductAPI_Telia_Product_Id__c = HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03;
        update listOfProductsToUse;

        List<PricebookEntry> listOfPricebookEntries = TDF_ProductUtils.createStandardPricebookEntriesForProducts(
            listOfProductsToUse
        );
        Map<Id, PricebookEntry> mapOfProductToPricebookEntries = TDF_ProductUtils.createProductIdToPricebookEntryMap(
            listOfPricebookEntries, 
            listOfProductsToUse
        );

        // create Quote Lines for the Quotes
        List<SBQQ__QuoteLine__c> testQuoteLines = TDF_QuoteLineUtils.createQuoteLinesForQuote(
            testQuotes, 
            false, 
            listOfProductsToUse, 
            mapOfProductToPricebookEntries
        );
        // need to requery to have the fields
        testQuoteLines = [
            SELECT 
                Id, 
                Activation__c, 
                Activation_Created__c,
                Activation_Record_Type__c, 
                SBQQ__Product__c,
                SBQQ__Product__r.Name,
                SBQQ__Quote__c,
                SBQQ__Quote__r.Name,
                SBQQ__Quote__r.SBQQ__BillingCity__c 
            FROM SBQQ__QuoteLine__c
        ];

        // create Case that looks up to same Account as the Quote does, and looks up to the same Opportunity as the Quote does
        List<Case> testCases = TDF_CaseUtils.createCasesForOpportunitiesAndAssignThem(testOpportunities);

        // create activation on case and account
        List<Activation__c> activationHeadersList = TDF_ActivationUtils.createActivationHeadersForQuoteLines(
            testQuoteLines, 
            testOpportunities
        );
        activationHeadersList = [
            SELECT Id, Name, Case_Account_ID__c, Case__r.Opportunity__r.Id, Recordtype.Developername 
            FROM Activation__c
        ];

        // create Location Line for each opp, then insert
        List<Location_Line__c> testLocationLines = new List<Location_Line__c>();
        for (Opportunity testOpportunity : testOpportunities) {
            Location_Line__c testLocationLine = TDF_LocationLineUtils.createLocationLineForOpportunity(
                testOpportunity, 
                HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03,
                null
            );
            testLocationLine.OTC_product__c = HomeOfficeConstants.LOCATION_LINE_OTC_PRODUCT_CHXT02;
            testLocationLine.VAS_product__c = HomeOfficeConstants.LOCATION_LINE_VAS_PRODUCT_FASTIP;
            testLocationLines.add(testLocationLine);
        }
        insert testLocationLines;

        Map<Id, List<Location_Line__c>> opportunityIdToLocationLinesMap = new Map<Id, List<Location_Line__c>>();
        testLocationLines = [SELECT Id, Name, Quote_Line__c, Opportunity__r.Id, OTC_product__c FROM Location_Line__c];
        for (Location_Line__c locationLine : testLocationLines) {
            if (!opportunityIdToLocationLinesMap.containsKey(locationLine.Opportunity__r.Id)) {

                List<Location_Line__c> locationLines = new List<Location_Line__c>();
                locationLines.add(locationLine);
                opportunityIdToLocationLinesMap.put(locationLine.Opportunity__r.Id, locationLines);
            } else {
                opportunityIdToLocationLinesMap.get(locationLine.Opportunity__r.Id).add(locationLine);
            }
        }

        // create and insert Activation Lines, then re-query
        List<Activation_Line__c> activationLinesList = TDF_ActivationLineUtils.createActivationLines(testQuoteLines);
        activationLinesList = [
            SELECT 
                Id, 
                Installation_address__c, 
                Location_Line__c, 
                Location_Line__r.Name, 
                Opportunity_ID__c,
                Quote_Line__c, 
                Quote_Line__r.SBQQ__Quote__c 
            FROM Activation_Line__c
        ];

        // opportunityIdToLocationLinesMap
        Set<Id> locationLineIdsUsed = new Set<Id>();

        // we need to populate activationLine.Location_Line__c, then update
        for (Activation_Line__c activationLine : activationLinesList) {
            for (Location_Line__c locationLine : opportunityIdToLocationLinesMap.get(activationLine.Opportunity_ID__c)) {
                if (!locationLineIdsUsed.contains(locationLine.Id)) {
                    activationLine.Location_Line__c = locationLine.Id;
                    locationLineIdsUsed.add(locationLine.Id);
                }
            }            
        }
        update activationLinesList;
    }
    
    /**
     * will create account(s). Will create one per account of:
     * - Opportunity
     * - Quote
     * - Quote Line
     * - Activation
     * - Activation Line
     * - Location Line
     * - Case
     * 
     * @param list of cvr
     */
    public static void makeDataSpecified(List<String> cvrList) {
        
        // create the Accounts
        List<Account> testAccounts = new List<Account>();
        for (String cvr : cvrList) {
            // create the Account
            Account testAccount = TDF_AccountUtils.createAccountWithCVR(cvr);
            testAccount.Status__c = 'Active';
            testAccounts.add(testAccount);
        }
        insert testAccounts;

        // we create 1 Opportunity per Account
        List<Opportunity> testOpportunities = TDF_OpportunityUtils.createHomeOfficeOpportunityForAccounts(
            testAccounts, 
            HomeOfficeConstants.AGREEMENT_TYPE_SPECIFIED
        );
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>(testOpportunities);

        Map<Id, List<Opportunity>> accountIdToOpportunitiesMap = new Map<Id, List<Opportunity>>();
        for (Opportunity testOpportunity : testOpportunities) {
            if (!accountIdToOpportunitiesMap.containsKey(testOpportunity.AccountId)) {
                List<Opportunity> opportunitiesPerAccount = new List<Opportunity>();
                opportunitiesPerAccount.add(testOpportunity);
                accountIdToOpportunitiesMap.put(testOpportunity.AccountId, opportunitiesPerAccount);
            } else {
                // key exists
                accountIdToOpportunitiesMap.get(testOpportunity.AccountId).add(testOpportunity);
            }
        }

        // create 1 Quote per opp
        List<SBQQ__Quote__c> testQuotes = new List<SBQQ__Quote__c>();        
        for (Account testAccount : testAccounts) {
            for (Opportunity opp : accountIdToOpportunitiesMap.get(testAccount.Id)) {
                SBQQ__Quote__c testQuote = TDF_QuoteUtils.createSingleQuote(testAccount.Id, opp.Id);
                testQuotes.add(testQuote);
            }
        }
        insert testQuotes;
        
        Map<Id, SBQQ__Quote__c> opportunityIdToQuoteMap = new Map<Id, SBQQ__Quote__c>();
        for (SBQQ__Quote__c testQuote : testQuotes) {
            if (!opportunityIdToQuoteMap.containsKey(testQuote.SBQQ__Opportunity2__c)) {
                opportunityIdToQuoteMap.put(testQuote.SBQQ__Opportunity2__c, testQuote);
            }
        }

        // re-query opportunities because we need to set the SBQQ__PrimaryQuote__c
        testOpportunities = [
            SELECT Id, AccountId, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.SBQQ__StartDate__c, Case__c 
            FROM Opportunity
        ];
        // loop through opportunities and set the primary quote
        for(Opportunity opp : testOpportunities) {
            opp.SBQQ__PrimaryQuote__c = opportunityIdToQuoteMap.get(opp.Id).Id;
        }
        update testOpportunities;

        // we need Home Office Products, insert and return
        Integer numberOfDifferentProducts = 1;
        List<Product2> listOfProductsToUse = TDF_ProductUtils.createHomeOfficeProducts(numberOfDifferentProducts);        
        // we need to set the ProductAPI_Telia_Product_Id__c to HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03
        listOfProductsToUse[0].ProductAPI_Telia_Product_Id__c = HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03;
        update listOfProductsToUse;

        List<PricebookEntry> listOfPricebookEntries = TDF_ProductUtils.createStandardPricebookEntriesForProducts(listOfProductsToUse);
        Map<Id, PricebookEntry> mapOfProductToPricebookEntries = TDF_ProductUtils.createProductIdToPricebookEntryMap(
            listOfPricebookEntries, 
            listOfProductsToUse
        );

        // create Quote Lines for the Quotes (we will only get one quote line per quote, because numberOfDifferentProducts = 1)
        List<SBQQ__QuoteLine__c> testQuoteLines = TDF_QuoteLineUtils.createQuoteLinesForQuote(
            testQuotes, 
            false, 
            listOfProductsToUse, 
            mapOfProductToPricebookEntries
        );
        // requery to have the fields
        testQuoteLines = [
            SELECT 
                Id, 
                Activation__c, 
                Activation_Created__c,
                Activation_Record_Type__c, 
                SBQQ__Product__c,
                SBQQ__Product__r.Name,
                SBQQ__Quote__c,
                SBQQ__Quote__r.Name,
                SBQQ__Quote__r.SBQQ__Opportunity2__c,
                SBQQ__Quote__r.SBQQ__BillingCity__c 
            FROM SBQQ__QuoteLine__c
        ];
        // we want a map of Opportunity Id to Quote Line (we know that there are one quote line per quote (and opp), because numberOfDifferentProducts = 1)
        Map<Id, SBQQ__QuoteLine__c> opportunityIdToQuoteLineMap = new Map<Id, SBQQ__QuoteLine__c>();
        for (SBQQ__QuoteLine__c quoteLine : testQuoteLines) {
            if (!opportunityIdToQuoteLineMap.containsKey(quoteLine.SBQQ__Quote__r.SBQQ__Opportunity2__c)) {
                opportunityIdToQuoteLineMap.put(quoteLine.SBQQ__Quote__r.SBQQ__Opportunity2__c, quoteLine);
            }
        }
        
        // create Case that looks up to same Account as the Quote does, and looks up to the same Opportunity as the Quote does
        List<Case> testCases = TDF_CaseUtils.createCasesForOpportunitiesAndAssignThem(testOpportunities);

        // create activation on case and account
        List<Activation__c> activationHeadersList = TDF_ActivationUtils.createActivationHeadersForQuoteLines(
            testQuoteLines, 
            testOpportunities
        );
        activationHeadersList = [
            SELECT Id, Name, Case_Account_ID__c, Case__r.Opportunity__r.Id, Recordtype.Developername 
            FROM Activation__c
        ];
        
        // create Location Line for each opp, then insert
        List<Location_Line__c> testLocationLines = new List<Location_Line__c>();
        for (Opportunity testOpportunity : testOpportunities) {
            Location_Line__c testLocationLine = TDF_LocationLineUtils.createLocationLineForOpportunity(
                testOpportunity, 
                HomeOfficeConstants.LOCATION_LINE_SUBSCRIPTION_PRODUCT_FIBHOF03,
                opportunityIdToQuoteLineMap.get(testOpportunity.Id)
            );
            testLocationLine.OTC_product__c = 'CHXT02';
            testLocationLines.add(testLocationLine);
        }
        insert testLocationLines;

        // create and insert Activation Lines
        List<Activation_Line__c> activationLinesList = TDF_ActivationLineUtils.createActivationLines(testQuoteLines);         
    }
}