force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User Story ID: 10
User Story: Create new CVR Account</description>
    <inlineHelpText>Pending (new account that needs validation)
Prospect (new account with no closed business)
Active (existing customer)
Attrited (Once an active customer, but not anymore)
Closed (A prospect who who never converted)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Attrited</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VAS_product__c.field-meta.xml
<CustomField>
    <fullName>VAS_product__c</fullName>
    <label>VAS product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_VAS_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Framework</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <description>User story ID: 94</description>
    <inlineHelpText>Specify here which products are included in this opportunity</inlineHelpText>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/DIGGING_NEEDED__c.field-meta.xml
<CustomField>
    <fullName>DIGGING_NEEDED__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIGGING_NEEDED</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/priceplanCode__c.field-meta.xml
<CustomField>
    <fullName>priceplanCode__c</fullName>
    <label>priceplanCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HomeOfficeControllerTest.cls
/**
 * 
 * @author keh
 * @since 10032025
 */
@isTest
private class HomeOfficeControllerTest {

	private static final String TEST_CVR = '12345678';

	/**
	 * setup
	 */
	@testSetup
	static void setup() {
		Profile prof = ProfileSelector.getProfileByProfileName(ProfileConstants.SYSTEM_ADMINISTRATOR);
		User usr = testDataFactory.createUser('standt', prof.Id);

		Account acc = TDF_AccountUtils.createAccountWithCVR(TEST_CVR);
        acc.Status__c = 'Active';
		acc.OwnerId = usr.Id;
        insert acc;

		Opportunity opp = new Opportunity();
		opp.Name = 'Testclass Opportunity';
		opp.StageName = 'Needs Analysis';
		opp.Agreement_Type__c = 'Framework';
		opp.Product_s_in_scope__c = 'Home Office';
		opp.CloseDate = Date.newInstance(2024, 12, 31);
		opp.AccountId = acc.Id;
		insert opp;

		Location_Line__c ll = new Location_Line__c();
		ll.Opportunity__c = opp.Id;
		ll.Street_Name__c = 'Risbystræde';
		ll.Number__c = '19';
		ll.ZIP_Code__c = '2620';
		ll.City__c = 'Albertslund';
		ll.Subscription_product__c = 'FIBHOF03';
		insert ll;

		Location_Line__c ll1 = new Location_Line__c();
		ll1.Opportunity__c = opp.Id;
		ll1.Street_Name__c = 'Fiskefjæs';
		ll1.Number__c = '19';
		ll1.ZIP_Code__c = '2620';
		ll1.City__c = 'Albertslund';
		ll1.Subscription_product__c = 'FIBHOF09';
		insert ll1;

		Location_Line__c ll2 = new Location_Line__c();
		ll2.Opportunity__c = opp.Id;
		ll2.Street_Name__c = 'Berlingo';
		ll2.Number__c = '19';
		ll2.ZIP_Code__c = '2620';
		ll2.City__c = 'Albertslund';
		ll2.Subscription_product__c = 'FIBHOF06';
		insert ll2;

		POQ_item__c pi1 = new POQ_item__c();
		pi1.DIGGING_NEEDED__c = true;
		pi1.priceplanCode__c = 'FIBHOF03';
		pi1.Location_Line__c = ll.Id;
		insert pi1;

		POQ_item__c pi2 = new POQ_item__c();
		pi2.DIGGING_NEEDED__c = false;
		pi2.priceplanCode__c = 'FIBHOF06';
		pi2.Location_Line__c = ll.Id;
		insert pi2;

		POQ_item__c pi3 = new POQ_item__c();
		pi3.DIGGING_NEEDED__c = true;
		pi3.priceplanCode__c = 'FIBHOF09';
		pi3.Location_Line__c = ll.Id;
		insert pi3;

		POQ_item__c pi4 = new POQ_item__c();
		pi4.DIGGING_NEEDED__c = true;
		pi4.priceplanCode__c = 'FIBHOF09';
		pi4.Location_Line__c = ll1.Id;
		insert pi4;

		POQ_item__c pi5 = new POQ_item__c();
		pi5.DIGGING_NEEDED__c = true;
		pi5.priceplanCode__c = 'FIBHOF06';
		pi5.Location_Line__c = ll2.Id;
		insert pi5;
	}

	/**
	 * updateProduct_validInput_changesSubscriptionProduct
	 */
	@isTest
	static void updateProduct_validInput_changesSubscriptionProduct() {
		//ARRANGE
		List<Location_Line__c> ll = [SELECT Id, Subscription_product__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];

		//ACT
		HomeOfficeController.updateProduct(ll[0].Id, 'FIBHOF03');
		HomeOfficeController.updateProduct(ll[0].Id, 'FIBHOF06');
		HomeOfficeController.updateProduct(ll[0].Id, 'FIBHOF09');
		ll = [SELECT Id, Subscription_product__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];
		
		//ASSERT
		System.assertEquals('FIBHOF09', ll[0].Subscription_product__c);
	
	}

	/**
	 * updateVas_nonStaticIp_setsVasProductToNull
	 */
	@isTest
	static void updateVas_nonStaticIp_setsVasProductToNull() {
		//ARRANGE
		List<Location_Line__c> ll = [SELECT Id FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];

		//ACT
		HomeOfficeController.updateVAS(ll[0].Id, false);
		ll = [SELECT Id, VAS_product__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];

		//ASSERT
		System.Assert.areEqual(null, ll[0].VAS_Product__c);


	}

	/**
	 * updateVas_staticIp_setsVasProductToFASTIP
	 */
	@isTest
	static void updateVas_staticIp_setsVasProductToFASTIP() {
		//ARRANGE
		List<Location_Line__c> ll = [SELECT Id FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];

		//ACT
		HomeOfficeController.updateVAS(ll[0].Id, true);
		ll = [SELECT Id, VAS_product__c FROM Location_Line__c WHERE Street_Name__c = 'Risbystræde' LIMIT 1];

		//ASSERT
		System.Assert.areEqual('FASTIP', ll[0].VAS_Product__c);
	}
}