force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Billing_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Type__c</fullName>
    <defaultValue>&quot;General&quot;</defaultValue>
    <description>To determine if it&apos;s a home office or any other type of record</description>
    <label>Billing Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Home Office</fullName>
            </value>
            <value>
                <fullName>Business Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Default_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this Billing Account is the default Billing Account for the Account. Used in new Home Office flow where it is assigned as default on Activation Lines.</description>
    <label>Default Billing Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BillingAccountSelector.cls
public with sharing class BillingAccountSelector {
    
    @AuraEnabled(cacheable=true)
    public static Billing_Account__c getDefaultBanByAccountAndType(String accountId, String type) {
		return [
			SELECT Id, Name
			FROM Billing_Account__c
			WHERE Account__c =: accountId AND Billing_Account_Type__c =: type AND Default_Billing_Account__c = true
			LIMIT 1
		];
	}

	@AuraEnabled(cacheable=true)
    public static List<Billing_Account__c> getBansByAccountAndType(String accountId, String type) {
		return [
			SELECT Id, Name, Default_Billing_Account__c
			FROM Billing_Account__c
			WHERE Account__c =: accountId AND Billing_Account_Type__c =: type
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Billing_Account__c> getBansByCaseAndType(String caseId, String type) {
		return [
			SELECT Id, Name, Default_Billing_Account__c
			FROM Billing_Account__c
			WHERE Account__c IN (
				SELECT AccountId
				FROM Case
				WHERE Id = :caseId
			)
			AND Billing_Account_Type__c = :type
		];
	}

}