force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DMC_Channel_Id__c/DMC_Channel_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>the channels Id values that belong to the DMC setup</description>
    <label>Consent Channel Ids</label>
</CustomObject>

force-app/main/default/objects/DMC_Channel_Id__c/fields/E_Mail__c.field-meta.xml
<CustomField>
    <fullName>E_Mail__c</fullName>
    <label>E-Mail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMC_Channel_Id__c/fields/Notifications__c.field-meta.xml
<CustomField>
    <fullName>Notifications__c</fullName>
    <label>Notifications</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMC_Channel_Id__c/fields/Phone_call__c.field-meta.xml
<CustomField>
    <fullName>Phone_call__c</fullName>
    <label>Phone call</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMC_Channel_Id__c/fields/Social_media__c.field-meta.xml
<CustomField>
    <fullName>Social_media__c</fullName>
    <label>Social media</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DMC_Channel_Id__c/fields/Text_message__c.field-meta.xml
<CustomField>
    <fullName>Text_message__c</fullName>
    <label>Text message</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/Fokus_Subscription__c.object-meta.xml
<CustomObject>
    <label>Fokus Subscription</label>
    <nameField>
        <label>Fokus Subscription</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fokus Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fokus_Subscription__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Fokus Subscriptions</relationshipLabel>
    <relationshipName>Fokus_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/MOBILE_NO__c.field-meta.xml
<CustomField>
    <fullName>MOBILE_NO__c</fullName>
    <label>MOBILE_NO</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/SF_ACCOUNT_KEY__c.field-meta.xml
<CustomField>
    <fullName>SF_ACCOUNT_KEY__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF_ACCOUNT_KEY</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fokus Subscriptions</relationshipLabel>
    <relationshipName>Fokus_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fokus_Subscription__c/fields/SUBSCRIBER_ID__c.field-meta.xml
<CustomField>
    <fullName>SUBSCRIBER_ID__c</fullName>
    <externalId>true</externalId>
    <label>SUBSCRIBER_ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <label>Dealer Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Consent_APITest.cls
@isTest
public class Consent_APITest {
    @isTest 
    static void TestStatus()
    {
        //TODO: keh fix unittest
        //sandboxes are running as system email only under deliverability.
        //can we change this to make this and the other email test work, without  risk of sending out to customers?
         Profile prof = [Select Id from Profile where name = 'System Administrator'];
         User u = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', 
            ProfileId = prof.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='standard_user@testorg.com', 
            Dealer_Code__c = 1111);

            system.runAs(u) {            
                
                Account acct = TDF_AccountUtils.creatActiveAccountWithCVRAndOwner();
                insert acct;
                
                Contact cont = new Contact(FirstName='Test', LastName='Contact',MobilePhone='12345678', Phone='12345',AccountId = acct.Id);
                insert cont;
                
                Billing_Account__c bAcc = TDF_BillingAccountUtils.CreateBillingAccount(acct);
                
                Fokus_Subscription__c Fokussubs = new Fokus_Subscription__c(
                    SUBSCRIBER_ID__c= 123456,
                    MOBILE_NO__C = cont.Phone,
                    SF_ACCOUNT_KEY__c = acct.Id,
                    EndDate__c = null,
                    Billing_Account__c = bAcc.Id
                 );
                insert Fokussubs; 
                
                DMC_Channel_Id__c  Channel_Settings = new DMC_Channel_Id__c();
   				Channel_Settings.E_Mail__c = '1234';
                Channel_Settings.Phone_call__c = '1234';
                Channel_Settings.Social_media__c = '1234';
                Channel_Settings.Text_message__c = '1234';
                Channel_Settings.Notifications__c = '1234';
                insert Channel_Settings;
                
                Consent_API_class testclass = new Consent_API_class();
                //Consent_API_class.ConsentResponse = new Consent_API_class.ConsentResponse();
                Consent_API_class.ConsentResponse testresponse = new Consent_API_class.ConsentResponse();
                testresponse.state = 'given';
                testresponse.consentId = '111';
                //testclass.ConsentResponse = testresponse;

                Test.startTest();
                Test.setMock(HttpCalloutMock.class, new Consent_API_CalloutMock());
                Consent_API.retrieveConsent(cont.Id);
                map<string,string> SubscriberResult = Consent_API.SubscriptionAPICall('123455','124');
                string testvalue = Consent_API.updateConsent(cont.Id,'123455','test@test.com','given','Phone');
                Test.setMock(HttpCalloutMock.class, new Subscription_API_CalloutMock());
                Consent_API.SubscriptionAPICall('123455','124');
                Consent_API.authenticateSubscriptionAPI();
                
                Integer callouts = Limits.getCallouts();
                Test.stopTest();  
        }
    } 
}