force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/BAN_Number__c.field-meta.xml
<CustomField>
    <fullName>BAN_Number__c</fullName>
    <description>Technical field automatically filled in by a workflow.</description>
    <externalId>true</externalId>
    <label>BAN Number</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Billing_Account__c/fields/Billing_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Name__c</fullName>
    <label>Billing Company Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TDF_BillingAccountUtils.cls
@IsTest
public with sharing class TDF_BillingAccountUtils {

    public static Billing_Account__c CreateBillingAccount(Account acc) {

        Billing_Account__c billingAccount = new Billing_Account__c();
		billingAccount.BAN_Number__c = 123456789;
		billingAccount.Billing_Name__c = 'Test company';
		billingAccount.Name = 'Invoice Name';
		billingAccount.Account__c = acc.Id;

		insert billingAccount;
        
        return billingAccount;
    }
}