force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The order product that this line should activate.</description>
    <inlineHelpText>The order product that this line should activate.</inlineHelpText>
    <label>Order Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Case__c</field>
            <operation>equals</operation>
            <valueField>OrderItem.Order.Case__c</valueField>
        </filterItems>
        <infoMessage>Select a product from the order</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF( ISBLANK(Order_Product__r.PricebookEntry.Product2.Name) , Manual_Product__r.Name , Order_Product__r.PricebookEntry.Product2.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product name from Telia&apos;s B2B product portfolio</inlineHelpText>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ignore_Remove_Product__c/Ignore_Remove_Product__c.object-meta.xml
<CustomObject>
    <label>Ignore/Remove Product</label>
    <nameField>
        <label>Ignore/Remove Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ignore/Remove Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ignore_Remove_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <description>Fokus code for the product to Ignore/Remove</description>
    <label>Order Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/activate_with_other_products__c.field-meta.xml
<CustomField>
    <fullName>activate_with_other_products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this product should not have an activation line itself, but is connected to a specific activation line during activation.</description>
    <inlineHelpText>Does this product require activation, but is it linked to another activation line during activation rather than having a line by itself? Often for products such as VAS&apos; or SLA&apos;s. Requires &quot;Activation record type&quot; to be set.</inlineHelpText>
    <label>Activate with other products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Group__c.field-meta.xml
<CustomField>
    <fullName>Contract_Group__c</fullName>
    <description>This field is used to link the subscriptions to right contract</description>
    <label>Contract Group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <description>Telia specific informationof the product to be used in Fokus</description>
    <label>Telia Product Id</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Matching__c/Product_Matching__c.object-meta.xml
<CustomObject>
    <description>The custom table to map productIds with Fokus product code that need to be mapped to dummy products on SF when Datamall integration fetches them</description>
    <label>Product Matching</label>
    <nameField>
        <label>Product Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Matchings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Matching__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Matchings</relationshipLabel>
    <relationshipName>Product_Matchings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Matching__c/fields/ProductAPI_Telia_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>ProductAPI_Telia_Product_Id__c</fullName>
    <label>ProductAPI_Telia_Product_Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexUtils.cls
public class ApexUtils {
public string GetVASColumnNamesfromActivationLines()
{
    Schema.DescribeSObjectResult activationline_desc = Activation_line__c.sObjectType.getDescribe(); 
            
    Map<String, Schema.SObjectField> activationline_fields = activationline_desc.fields.getMap();
    String columnNames='Id';
            
      for(Schema.sObjectField fld:activationline_fields.values())
      {     
         if(string.valueof(fld).indexOf('VAS_')==0)
         {
             columnNames = columnNames + ',' +  fld.getDescribe().getName();  
              
         }
      } 
    return columnNames;
}
        
    public static void sendMail(String mailMessage, String mailSubject, String emailAddress){              
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {emailAddress};
        mail.setToAddresses(toAddresses);  
        mail.setSenderDisplayName('Salesforce Reminder');
        mail.setSubject(mailSubject);
        mail.setPlainTextBody(mailMessage);
        if(!Test.isRunningTest()){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
	}
    
    public List<String> CheckIgnoreProducts ()
    {
        List<String> IgnoreProducts = new List<String>();
        list<Ignore_Remove_Product__c> IgnoreProductList;
        IgnoreProductList =  [select Order_Product__c from Ignore_Remove_Product__c];
        
        if(IgnoreProductList.size()>0)
        {
            for (Ignore_Remove_Product__c OpsRec: IgnoreProductList)
          	{
         	    IgnoreProducts.add(OpsRec.Order_Product__c); 
          	}   
        }
        system.debug('Ignore products:' + IgnoreProducts);
        return IgnoreProducts;
    } 
    
    public List<String> CheckDSLProducts ()
    {
        List<String> DSLProductCodes = new List<String>();
        list<SBQQ__ProductOption__c>DSLProductList;
        DSLProductList =  [select SBQQ__ConfiguredSKU__r.ProductAPI_Telia_Product_Id__c from SBQQ__ProductOption__c 
                           where SBQQ__MaxQuantity__c = 1];
        
        if(DSLProductList.size()>0)
        {
            for (SBQQ__ProductOption__c OpsRec: DSLProductList)
          	{
             if(OpsRec.SBQQ__ConfiguredSKU__r.ProductAPI_Telia_Product_Id__c !=null)
              {   
            	  DSLProductCodes.add(OpsRec.SBQQ__ConfiguredSKU__r.ProductAPI_Telia_Product_Id__c); 
        	  } 
          	}   
        }
        system.debug('DSL products:' + DSLProductCodes);
        return DSLProductCodes;
    }
    
        public Map<String,String> LoadSubscriptionProductCodeList()
    {
           list<Product2> ProductInfoList = [SELECT Id,ProductAPI_Telia_Product_Id__c,Contract_Group__c  
                                              from Product2 where IsActive = true
                                              and activate_with_other_products__c = false
                                              and SBQQ__SubscriptionType__c <> 'One-Time'
                                              and ProductAPI_Telia_Product_Id__c != null];   
            Map<String,String> ALLProductCodes= new Map<String, String>();
            //Name,ProductId         
            for(Product2 pr : ProductInfoList)
            {
                ALLProductCodes.put(pr.Id,pr.ProductAPI_Telia_Product_Id__c);
            }
            
    	return ALLProductCodes;
    }
    
    public Map<String,String> LoadSubscriptionProductList()
    {
           list<Product2> ProductInfoList = [SELECT Id,ProductAPI_Telia_Product_Id__c,Contract_Group__c  
                                              from Product2 where IsActive = true
                                              and activate_with_other_products__c = false
                                              and SBQQ__SubscriptionType__c <> 'One-Time'
                                              and ProductAPI_Telia_Product_Id__c != null ];  
            Map<String,String> ALLProductNames= new Map<String, String>();
            //Name,ProductId         
            for(Product2 pr : ProductInfoList)
            {
                ALLProductNames.put(pr.ProductAPI_Telia_Product_Id__c,pr.Id);
            }
            
             //Add the Product Matching Table
            list<Product_Matching__c> ProductMatchInfoList = [SELECT Product__c ,ProductAPI_Telia_Product_Id__c   
                                              from Product_Matching__c];  
            for(Product_Matching__c pr : ProductMatchInfoList)
            {
                ALLProductNames.put(pr.ProductAPI_Telia_Product_Id__c,pr.Product__c);
            }

    	return ALLProductNames;
    }
    
    
    
    public Map<String,String> LoadProductList()
    {
           list<Product2> ProductInfoList = [SELECT Id,ProductAPI_Telia_Product_Id__c,Contract_Group__c  
                                              from Product2 where IsActive = true
                                              and SBQQ__SubscriptionType__c <> 'One-Time' 
                                              and ProductAPI_Telia_Product_Id__c != null  ];
            Map<String,String> ALLProductNames= new Map<String, String>();
            //Name,ProductId         
            for(Product2 pr : ProductInfoList)
            {
                ALLProductNames.put(pr.ProductAPI_Telia_Product_Id__c,pr.Id);
            }
            
             //Add the Product Matching Table
            list<Product_Matching__c> ProductMatchInfoList = [SELECT Product__c ,ProductAPI_Telia_Product_Id__c   
                                              from Product_Matching__c];  
            for(Product_Matching__c pr : ProductMatchInfoList)
            {
                ALLProductNames.put(pr.ProductAPI_Telia_Product_Id__c,pr.Product__c);
            }

    	return ALLProductNames;
    }
    
     public Map<String,String> LoadProductContractGroups()
    {
           list<Product2> ProductInfoList = [SELECT Id,ProductAPI_Telia_Product_Id__c,Contract_Group__c  
                                              from Product2 where IsActive = true];
                                              //and activate_with_other_products__c = false
                                              //and ProductAPI_Telia_Product_Id__c != null   
            Map<String,String> ALLProductContractTypes= new Map<String, String>();
            //Name,ProductId         
            for(Product2 pr : ProductInfoList)
            {
                ALLProductContractTypes.put(pr.Id, pr.Contract_Group__c != null ? pr.Contract_Group__c : 'Mobile');
            }

    	return ALLProductContractTypes;
    }
}