force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Fastnet_user__c.field-meta.xml
<CustomField>
    <fullName>Fastnet_user__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate in the Onboarding Portal if the user is a Fastnet user.</description>
    <label>Fastnet user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/TOP_Activation_Flow_Step__c.field-meta.xml
<CustomField>
    <fullName>TOP_Activation_Flow_Step__c</fullName>
    <description>Used to store current flow step during TOP activation process when clicked &quot;Save to continue later&quot;</description>
    <inlineHelpText>Used to store current flow step during TOP activation process when clicked &quot;Save to continue later&quot;</inlineHelpText>
    <label>TOP Activation Flow Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/TOP_Completed_Flows__c.field-meta.xml
<CustomField>
    <fullName>TOP_Completed_Flows__c</fullName>
    <description>Comma separated list of completed TOP activation flow ids</description>
    <inlineHelpText>Comma separated list of completed TOP activation flow ids</inlineHelpText>
    <label>TOP Completed Flows</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/VAS_UC_License__c.field-meta.xml
<CustomField>
    <fullName>VAS_UC_License__c</fullName>
    <inlineHelpText>Add the UC license relevant for the specific user if part of quote</inlineHelpText>
    <label>UC License</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UC_License</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActivationLineServiceTest.cls
@isTest
private class ActivationLineServiceTest {

    @isTest
    static void createActivationLineTest() {
 
        List<Activation_line__c> triggerNew = new List<Activation_line__c>{
            new Activation_line__c(
                TOP_Activation_Flow_Step__c = 'FINISHED',
                TOP_Completed_Flows__c = 'Voice_Flow',
                Fastnet_user__c = true,
                VAS_UC_License__c = '12345'
            )
        };
 
        DatabaseService db = new DatabaseService().mockDMLs();
 
        ActivationLineService activationLineService = new ActivationLineService(db);
 
        Test.startTest();
            activationLineService.createActivationLine(triggerNew);
        Test.stopTest();
 
        System.assertEquals('12345', triggerNew[0].VAS_UC_License__c, 'We call insert on the Voice flow activation line provided in the list');
    }

    @isTest
    static void handleAfterUpdateTest() {

        List<Activation_line__c > triggerNew = new List<Activation_line__c>{new Activation_line__c(
            TOP_Activation_Flow_Step__c = 'FINISHED', 
            TOP_Completed_Flows__c = 'Voice_Flow', 
            Fastnet_user__c = true, 
            VAS_UC_License__c = '12345')};

        List<Activation_line__c > triggerOld = new List<Activation_line__c>{new Activation_line__c(
            TOP_Activation_Flow_Step__c = 'STARTED', 
            TOP_Completed_Flows__c = 'None', 
            Fastnet_user__c = true, 
            VAS_UC_License__c = '12345')};
 
        ActivationLineService activationLineService = new ActivationLineService();

        Test.startTest();
            activationLineService.hasCompletedVoiceFlow(triggerNew, triggerOld);
        Test.stopTest();

        System.assertEquals('FINISHED', triggerNew[0].TOP_Activation_Flow_Step__c, 'We call insert on the Voice flow activation line provided in the list');
    }
}