force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the specific activation line to a BAN (Billing Account).</description>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Billing Account</label>
    <nameField>
        <label>Invoicing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ActivationLinesAssignBAN.cls
public with sharing class ActivationLinesAssignBAN {
    
    @InvocableMethod(label='Assign BAN to Activation Lines' description='Assign BAN to Activation Lines')
	public static void assignBAN(List<InputClass> input) {
        String ban = input[0].ban;

        List<Activation_Line__c> activationLines = new List<Activation_line__c>();

        for (SObject sObj : input[0].activationLines) {
            Activation_Line__c activationLine = (Activation_Line__c)sObj;
            activationLine.Billing_Account__c = ban;
            activationLines.add(activationLine);
        }

        update activationLines;
    }

    public class InputClass {
        @InvocableVariable(required=true)
        public List<SObject> activationLines;
        @InvocableVariable(required=true)
        public String ban;
    }

}