force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Quote_line__c.field-meta.xml
<CustomField>
    <fullName>Quote_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line that this activation is a result of</description>
    <inlineHelpText>The quote line that was sold to initiate activation of this line item.</inlineHelpText>
    <label>Quote line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Activations lines (Quote line)</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The QuoteLine that resulted from this LocationLine.</description>
    <inlineHelpText>The QuoteLine that resulted from this LocationLine.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HomeOfficeFlowGetActivationLine.cls
public with sharing class HomeOfficeFlowGetActivationLine {
	@InvocableMethod(label='Find Activation Line in a list' description='Find Activation Line in a list')
	public static List<OutputVariables> getActivationLine(List<InputVariables> inputVariables) {
		// Input
		List<Activation_Line__c> passedInActivationLines = inputVariables.get(0).activationLines;
		List<Id> passedInProcessedActivationLineIds = inputVariables.get(0).processedActivationLineIds;
		String passedInAgreementType = inputVariables.get(0).agreementType; // Specified or Framework
		Id passedInSelectionRecordId = inputVariables.get(0).selectionRecordId;

		System.debug('passedInActivationLines = ' + passedInActivationLines);

		// Logic
		Activation_Line__c selectedActivationLine = null;

		for (Activation_Line__c activationLine : passedInActivationLines) {
			System.debug('activationLine = ' + activationLine);
			if (passedInAgreementType.equalsIgnoreCase('Framework')) {
				if (
					activationLine.Location_Line__c == passedInSelectionRecordId &&
					(passedInProcessedActivationLineIds == null || !passedInProcessedActivationLineIds.contains(activationLine.Id))
				) {
					selectedActivationLine = activationLine;
					break;
				}
			} else if (passedInAgreementType.equalsIgnoreCase('Specified')) {
				if (
					activationLine.Quote_Line__c == passedInSelectionRecordId &&
					(passedInProcessedActivationLineIds == null || !passedInProcessedActivationLineIds.contains(activationLine.Id))
				) {
					selectedActivationLine = activationLine;
					break;
				}
			}
			System.debug('selectedActivationLine = ' + selectedActivationLine);
		}

		// Output
		List<OutputVariables> outputVarsList = new List<OutputVariables>();
		OutputVariables outputVars = new OutputVariables();
		outputVars.activationLine = selectedActivationLine;
		outputVarsList.add(outputVars);
		System.debug('outputVarsList = ' + outputVarsList);
		return outputVarsList;
	}

	public class InputVariables {
		@InvocableVariable
		public List<Activation_Line__c> activationLines;

		@InvocableVariable
		public List<Id> processedActivationLineIds;

		@InvocableVariable
		public String agreementType; // Specified or Framework

		@InvocableVariable
		public Id selectionRecordId;
	}

	public class OutputVariables {
		@InvocableVariable
		public Activation_Line__c activationLine;
	}
}