force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <label>Dealer Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Agent_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agent_Code__c</fullName>
    <description>Used when posting an order via Order API to ensure the right sales rep is compensated when the order is created in the billing systems</description>
    <label>Sales Agent Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDF_UserUtils.cls
@IsTest
public with sharing class TDF_UserUtils {
    public static User createUser(String alias, String profileId) {
		User user = new User();
		user.Alias = alias;
		user.Email = 'standarduser@testorg.com';
		user.EmailEncodingKey = 'UTF-8';
		user.LastName = 'Testing';
		user.LanguageLocaleKey = 'en_US';
		user.LocaleSidKey = 'en_US';
		user.ProfileId = profileId;
		user.TimeZoneSidKey = 'America/Los_Angeles';
		user.UserName = StringUtils.makeRandomStringNoNumerics(10) + '@' + StringUtils.makeRandomStringNoNumerics(5) + '.com';
		user.Dealer_Code__c = 1234;
		user.Sales_Agent_Code__c = '12345';
		user.FederationIdentifier = StringUtils.makeRandomStringNoNumerics(7);
		insert user;
		return user;
	}

	public static User createUserForContact(String contactId, String alias, String profileId) {
		User user = new User();
		user.Alias = alias;
		user.Email = 'standarduser@testorg.com';
		user.EmailEncodingKey = 'UTF-8';
		user.LastName = 'Testing';
		user.LanguageLocaleKey = 'en_US';
		user.LocaleSidKey = 'en_US';
		user.ProfileId = profileId;
		user.TimeZoneSidKey = 'America/Los_Angeles';
		user.UserName = StringUtils.makeRandomStringNoNumerics(10) + '@' + StringUtils.makeRandomStringNoNumerics(5) + '.com';
		user.Dealer_Code__c = 1234;
		user.Sales_Agent_Code__c = '12345';
		user.FederationIdentifier = StringUtils.makeRandomStringNoNumerics(7);
		user.ContactId = contactId;
		insert user;
		return user;
	}
}