force-app/main/default/objects/APISettings__mdt/APISettings__mdt.object-meta.xml
<CustomObject>
    <label>APISettings</label>
    <pluralLabel>APISettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/APISettings__mdt/fields/brand__c.field-meta.xml
<CustomField>
    <fullName>brand__c</fullName>
    <label>brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Identifier__mdt/Document_Identifier__mdt.object-meta.xml
<CustomObject>
    <label>Document Identifier</label>
    <pluralLabel>Document Identifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Document_Identifier__mdt/fields/Product_Document_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Product_Document_Identifier__c</fullName>
    <label>Product Document Identifier</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate APN</fullName>
                <default>true</default>
                <label>Corporate APN</label>
            </value>
            <value>
                <fullName>DDOS</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Operator Connect Fixed</fullName>
            </value>
            <value>
                <fullName>Operator Connect Mobile</fullName>
            </value>
            <value>
                <fullName>Data Type Products</fullName>
            </value>
            <value>
                <fullName>Mobile Type Products</fullName>
            </value>
            <value>
                <fullName>Fastnet Type Products</fullName>
            </value>
            <value>
                <fullName>IOT Type Products</fullName>
            </value>
            <value>
                <fullName>ACE Type Products</fullName>
            </value>
            <value>
                <fullName>ACE Cloud</fullName>
            </value>
            <value>
                <fullName>Mobile Pricesheet</fullName>
            </value>
            <value>
                <fullName>Internet Fiber</fullName>
            </value>
            <value>
                <fullName>Internet DSL</fullName>
            </value>
            <value>
                <fullName>Datanet Fiber</fullName>
            </value>
            <value>
                <fullName>Datanet DSL</fullName>
            </value>
            <value>
                <fullName>Datanet 4G</fullName>
            </value>
            <value>
                <fullName>Cloud Connect</fullName>
            </value>
            <value>
                <fullName>Fleet Complete</fullName>
            </value>
            <value>
                <fullName>Home Office New</fullName>
            </value>
            <value>
                <fullName>Home Office Old</fullName>
            </value>
            <value>
                <fullName>Telia Insight</fullName>
            </value>
            <value>
                <fullName>Roaming</fullName>
            </value>
            <value>
                <fullName>Trafik</fullName>
            </value>
            <value>
                <fullName>TPX</fullName>
            </value>
            <value>
                <fullName>M2M</fullName>
            </value>
            <value>
                <fullName>Touchpoint</fullName>
            </value>
            <value>
                <fullName>Telia Nummerdeling</fullName>
            </value>
            <value>
                <fullName>SIP Trunk</fullName>
            </value>
            <value>
                <fullName>PSTN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Environment_Credential_Mapping__mdt/Environment_Credential_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to dynamically get the right Named and External Credential based on Salesforce environment.</description>
    <label>Environment Credential Mapping</label>
    <pluralLabel>Environment Credential Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Environment_Credential_Mapping__mdt/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <inlineHelpText>Name of the sandbox (or prod) for which to use the specified Named Credential. Make a default/fall back record by setting this to &quot;default&quot;</inlineHelpText>
    <label>Environment Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Credential_Mapping__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <inlineHelpText>The API name of the Named Credential to be used for the specified environment.</inlineHelpText>
    <label>Named Credential</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataSelectorTest.cls
@IsTest
public with sharing class MetadataSelectorTest {
	@IsTest
	private static void testGetAPISettingsSuccess(){
		String metadataDeveloperName = 'MyTestSetting';
		String brand = 'CompanyName';

		APISettings__mdt mockedSetting = new APISettings__mdt();
		mockedSetting.DeveloperName = metadataDeveloperName;
		mockedSetting.brand__c = brand;

		MetadataSelector.setMock(new MetadataSelectorMock(mockedSetting));

		Test.startTest();
		APISettings__mdt mdt = MetadataSelector.getAPISettings(metadataDeveloperName);
		Test.stopTest();

		Assert.isNotNull(mdt, 'A metadata record should be returned');
		Assert.areEqual(brand, mdt.brand__c, 'The returned metadata brand should match');
	}

	@IsTest
	private static void testGetApiSettingsNotFound(){
		Test.startTest();
		APISettings__mdt noMdt = MetadataSelector.getAPISettings(StringUtils.makeRandomStringNoNumerics(20));
		Test.stopTest();

		Assert.isNull(noMdt, 'Random DeveloperName should not find any valid metadata records');
	}

	@IsTest
	private static void testGetEnvironmentCredentialMappingsSuccess(){
		String namedCredentialPrefix = 'MyTestCredential';
		String environmentName = NamedCredentialService.getEnvironmentName();

		List<Environment_Credential_Mapping__mdt> mockedMappings = new List<Environment_Credential_Mapping__mdt>();
		Environment_Credential_Mapping__mdt mockedMapping = new Environment_Credential_Mapping__mdt();
		mockedMapping.Environment_Name__c = environmentName;
		mockedMapping.Named_Credential__c = namedCredentialPrefix + environmentName;
		mockedMappings.add(mockedMapping);

		MetadataSelector.setMock(new MetadataSelectorMock(mockedMappings));

		Test.startTest();
		List<Environment_Credential_Mapping__mdt> mappings = MetadataSelector.getEnvironmentCredentialMappings();
		Test.stopTest();

		Assert.isNotNull(mappings, 'Mappings should be returned');
		Assert.areEqual(mockedMappings.size(), mappings.size(), 'Amount of mappings returned should match the amount of test mappings');
		Assert.areEqual(mockedMapping.Named_Credential__c, mappings[0].Named_Credential__c, 'Response should match the Named_Credential__c field from Custom Metadata');
	}

	@IsTest
	private static void testGetEnvironmentCredentialMappingsNoRecords(){
		String namedCredentialPrefix = 'MyTestCredential';
		String environmentName = NamedCredentialService.getEnvironmentName();

		List<Environment_Credential_Mapping__mdt> mockedMappings = new List<Environment_Credential_Mapping__mdt>();

		MetadataSelector.setMock(new MetadataSelectorMock(mockedMappings));

		Test.startTest();
		List<Environment_Credential_Mapping__mdt> mappings = MetadataSelector.getEnvironmentCredentialMappings();
		Test.stopTest();

		Assert.isTrue(mappings.isEmpty(), 'No mappings should be returned');
	}

	@IsTest
	private static void testGetEnvironmentCredentialMappingsNotMocked(){
		Test.startTest();
		List<Environment_Credential_Mapping__mdt> mappings = MetadataSelector.getEnvironmentCredentialMappings();
		Test.stopTest();

		Assert.areEqual(Environment_Credential_Mapping__mdt.getAll().size(), mappings.size(), 'The amount of mappings returned should match that of the org');
	}

	@IsTest
	private static void testGetDocumentIdentifierMappingsSuccess(){
		String label = 'Custom_Field__c';
		String productDocumentIdentifier = 'Mobile Type Products';

		List<Document_Identifier__mdt> mockedMappings = new List<Document_Identifier__mdt>();
		Document_Identifier__mdt mockedMapping = new Document_Identifier__mdt();
		mockedMapping.Label = label;
		mockedMapping.Product_Document_Identifier__c = productDocumentIdentifier;
		mockedMappings.add(mockedMapping);

		MetadataSelector.setMock(new MetadataSelectorMock(mockedMappings));

		Test.startTest();
		List<Document_Identifier__mdt> mappings = MetadataSelector.getDocumentIdentifierMappings();
		Test.stopTest();

		Assert.isNotNull(mappings, 'Mappings should be returned');
		Assert.areEqual(mockedMappings.size(), mappings.size(), 'Amount of mappings returned should match the amount of test mappings');
		Assert.areEqual(productDocumentIdentifier, mappings[0].Product_Document_Identifier__c, 'Response should match the Product_Document_Identifier__c field from Custom Metadata');
	}

	@IsTest
	private static void testGetDocumentIdentifierMappingsNoMappings(){
		List<Document_Identifier__mdt> mockedMappings = new List<Document_Identifier__mdt>();

		MetadataSelector.setMock(new MetadataSelectorMock(mockedMappings));

		Test.startTest();
		List<Document_Identifier__mdt> mappings = MetadataSelector.getDocumentIdentifierMappings();
		Test.stopTest();

		Assert.isTrue(mappings.isEmpty(), 'No mappings should be returned');
	}

	@IsTest
	private static void testGetDocumentIdentifierMappingsNotMocked(){
		Test.startTest();
		List<Document_Identifier__mdt> mappings = MetadataSelector.getDocumentIdentifierMappings();
		Test.stopTest();

		Assert.areEqual(Document_Identifier__mdt.getAll().size(), mappings.size(), 'The amount of mappings returned should match that of the org');
	}

}