force-app/main/default/objects/Subscription_Line_Detail__c/Subscription_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Detail</label>
    <nameField>
        <displayFormat>SLD-{000000}</displayFormat>
        <label>Subscription Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Details</relationshipLabel>
    <relationshipName>Subscription_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>TerminatedDate__c</fullName>
    <label>TerminatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>These field has been created to hold 255 signs of additional information that might be useful in problem solving of this error.</description>
    <inlineHelpText>Additional helpful information like name of class/flow ect.</inlineHelpText>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Subscription_Line_Detail_Update.cls
public class Subscription_Line_Detail_Update implements Database.Batchable<sObject>{
    public String query;    
    public Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select Id,CreatedDate, Subscription__c, Quantity__c  ' +
                                        'from Subscription_Line_Detail__c where CreatedDate >=TODAY OR ' +
                                        ' (LastModifiedDate >=TODAY AND  TerminatedDate__c != null)');
    }
    
    public void execute(Database.BatchableContext BC, List<Subscription_Line_Detail__c> scope){

    map<String,Integer> SubscriptionUpdates = new Map <String,Integer>(); //SubscriberId,Quantity
    integer quantity;
    string subscriptionId;
    string subscriptiondetailId; 
    string contractid;
    try
     {
        system.debug('Start');
        for(Subscription_Line_Detail__c s : scope)
      	{ 
          if(s.CreatedDate >=System.today()) //new insert
          { 
              if(SubscriptionUpdates.get(s.Subscription__c)!=null)
               {   
                   quantity = SubscriptionUpdates.get(s.Subscription__c);
                   SubscriptionUpdates.put(s.Subscription__c, quantity + (s.Quantity__c == null ? 1 : Integer.valueOf(s.Quantity__c)));
               }
              else
               {   
                   system.debug('Missing');
                   SubscriptionUpdates.put(s.Subscription__c, (s.Quantity__c == null ? 1 : Integer.valueOf(s.Quantity__c)));
               }   
          }
          else //Delete
          {  
              if(SubscriptionUpdates.get(s.Subscription__c)!=null)
               {   
                   quantity = SubscriptionUpdates.get(s.Subscription__c);
                   SubscriptionUpdates.put(s.Subscription__c, quantity - Integer.valueOf(s.Quantity__c));
               }
              else
               {   
                   System_Log__c  logerror = new System_Log__c (Origin__c  = 'Apex',Error_Body__c = s.Id +' is deleted from Fokus without a matching Subscription in Salesforce',Additional_Information__c = 'Subscription_Line_Detail_Update');
           		   insert logerror; 
               } 
          }
      }    
    List<Subscription_Line_Detail__c> UpdateSubscriptionLineDetails = new List<	Subscription_Line_Detail__c>();    
    Subscription_Line_Detail__c  SubscriptionLine = new Subscription_Line_Detail__c();
	update UpdateSubscriptionLineDetails;
    system.debug(UpdateSubscriptionLineDetails);  
         }//try
         catch(Exception e){
            System_Log__c  logerror = new System_Log__c (Origin__c  = 'Apex',Error_Body__c = e.getMessage(),Additional_Information__c = 'Fokus_SubscriptionService_Update');
            insert logerror;  
       }
    } 
    public void finish(Database.BatchableContext BC){        
    }
}