force-app/main/default/objects/Subscription_Line_Detail__c/Subscription_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Detail</label>
    <nameField>
        <displayFormat>SLD-{000000}</displayFormat>
        <label>Subscription Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Detail__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Details</relationshipLabel>
    <relationshipName>Subscription_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubscriptionLineDetailTriggerHandler.cls
public class SubscriptionLineDetailTriggerHandler extends TriggerHandler {
	private final SubscriptionService subscriptionService;

	private List<Subscription_Line_Detail__c> newSubscriptionLineDetails;
	private List<Subscription_Line_Detail__c> oldSubscriptionLineDetails;

	public SubscriptionLineDetailTriggerHandler() {
		this(SingletonFactory.getFactory());
	}

	private SubscriptionLineDetailTriggerHandler(SingletonFactory singletonFactory) {
		this.subscriptionService = (SubscriptionService) singletonFactory.getOrRegisterSingleton(
			SubscriptionService.class
		);

		this.newSubscriptionLineDetails = (List<Subscription_Line_Detail__c>) Trigger.new;
		this.oldSubscriptionLineDetails = (List<Subscription_Line_Detail__c>) Trigger.old;
	}

	@TestVisible
	private SubscriptionLineDetailTriggerHandler(SubscriptionService subscriptionService) {
		this.subscriptionService = subscriptionService;
	}

	protected override void afterInsert() {
		Set<Id> subscriptionIds = new Set<Id>(
			SObjectCollectionUtil.of(newSubscriptionLineDetails).pluckIds(Subscription_Line_Detail__c.Subscription__c)
		);

		subscriptionService.updateSubscriptionQuantity(subscriptionIds);
	}

	protected override void afterUpdate() {
		Set<Id> subscriptionIds = new Set<Id>(
			SObjectCollectionUtil.of(newSubscriptionLineDetails).pluckIds(Subscription_Line_Detail__c.Subscription__c)
		);

		subscriptionService.updateSubscriptionQuantity(subscriptionIds);
	}

	protected override void afterDelete() {
		Set<Id> subscriptionIds = new Set<Id>(
			SObjectCollectionUtil.of(oldSubscriptionLineDetails).pluckIds(Subscription_Line_Detail__c.Subscription__c)
		);

		subscriptionService.updateSubscriptionQuantity(subscriptionIds);
	}
}