force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>Date the Lead was set to Qualified or Unqualified. Used by SalesPlayManagementGetAccountsAction to filter Accounts for Sales Play Lead creation.</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unqualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unqualified_Reason__c</fullName>
    <description>Field used for entering an Unqualified Reason, Used in Validation Rule</description>
    <inlineHelpText>If a Lead is Unqualified you are required to enter a reason</inlineHelpText>
    <label>Unqualified Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Time – Timing</fullName>
            </value>
            <value>
                <fullName>No need</fullName>
            </value>
            <value>
                <fullName>Missing product</fullName>
            </value>
            <value>
                <fullName>In binding with another provider</fullName>
            </value>
            <value>
                <fullName>Bad experience with Telia</fullName>
            </value>
            <value>
                <fullName>No interest - other</fullName>
            </value>
            <value>
                <fullName>Poor lead quality</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Bad experience with Norlys</fullName>
                <isActive>false</isActive>
                <label>Bad experience with Norlys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
public with sharing class LeadSelector {
    @TestVisible
	private static final String LEAD_STATUS_QUALIFIED = 'Qualified';
	@TestVisible
	private static final String LEAD_STATUS_UNQUALIFIED = 'Unqualified';
    @TestVisible
    private static final String LEAD_UNQUALIFIED_REASON_DEACTIVATED = 'Deactivated';
    
	private static final Set<String> LEAD_STATUSES_CLOSED = new Set<String>{
		LEAD_STATUS_QUALIFIED,
		LEAD_STATUS_UNQUALIFIED
	};

    public static List<Lead> getOrderedOpenOrClosedLeadsByAccountsAndCloseDate(List<Account> accounts, Date filterDate) {
        return [
			SELECT Id, Account__c, Status, Close_Date__c
			FROM Lead
			WHERE Account__c IN :accounts
                AND (Status != :LEAD_STATUS_UNQUALIFIED OR Unqualified_Reason__c != :LEAD_UNQUALIFIED_REASON_DEACTIVATED)                 
				AND (                    
					(Status NOT IN :LEAD_STATUSES_CLOSED) OR
					(Status IN :LEAD_STATUSES_CLOSED AND Close_Date__c > :filterDate)
				)
			ORDER BY Close_Date__c, Status
		];
    }
}