force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Framework</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <description>User Story ID: 45</description>
    <inlineHelpText>The reason we lost the business</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Our relation to the customer</fullName>
                <label>Manglende relationer</label>
            </value>
            <value>
                <fullName>Our Products are missing features</fullName>
                <label>Manglende produkter (beskriv i Other Loss Reason)</label>
            </value>
            <value>
                <fullName>Onboarding was not strong enough</fullName>
                <label>Mangelfuld implementering</label>
            </value>
            <value>
                <fullName>Customer Service was not good enough</fullName>
                <label>Mangelfuld kundeservice</label>
            </value>
            <value>
                <fullName>Our prices are too high</fullName>
                <label>Pris</label>
            </value>
            <value>
                <fullName>Mangelfuld subsidie</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <label>Opgivet</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Andet/Ved ikke (beskriv i Other Loss Reason)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <description>User story ID: 94</description>
    <inlineHelpText>Specify here which products are included in this opportunity</inlineHelpText>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Telia Enterprise</businessProcess>
    <description>Used for tracking sales</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/OpportunitySelectorTest.cls
@IsTest
private with sharing class OpportunitySelectorTest {
	private static final String CVR = '23232323';

	@TestSetup
	private static void makeData() {
		Account acc = TestDataFactory.createAccountWithCVR(CVR);
		insert acc;
	}

	@IsTest
	private static void testGetById() {
		Account acc = AccountSelector.getByCVR(CVR);

		Opportunity opp1 = new Opportunity(
			Name = 'Opp1',
			StageName = 'Needs Analysis',
			AccountId = acc.Id,
			Agreement_Type__c = 'Specified',
			Product_s_in_scope__c = 'Home Office',
			CloseDate = Date.today() + 30
		);
		insert opp1;

		Test.startTest();
		Opportunity oppById = OpportunitySelector.getById(opp1.Id);
		Test.stopTest();

		Assert.areEqual('Opp1', oppById.Name, 'Opportunity Name should match');
	}

	@IsTest
	private static void testGetHomeOfficeOppByOppContactRoleAndContact() {
		Account acc = AccountSelector.getByCVR(CVR);

		Contact contct = new Contact(LastName = 'LastName', FirstName = 'FirstName', Email = 'contact@email.com', AccountId = acc.Id);
		insert contct;

		Opportunity opp1 = new Opportunity(
			Name = 'Opp1',
			StageName = 'Needs Analysis',
			AccountId = acc.Id,
			ContactId = contct.Id,
			Agreement_Type__c = 'Specified',
			Product_s_in_scope__c = 'Home Office',
			CloseDate = Date.today() + 30
		);
		insert opp1;

		OpportunityContactRole opCtRole = new OpportunityContactRole();
		opCtRole.OpportunityId = opp1.Id;
		opCtRole.Contactid = contct.Id;
		opCtRole.Role = 'Sales Contact';
		insert opCtRole;

		Test.startTest();
		Opportunity opp = OpportunitySelector.getHomeOfficeOppByOppContactRoleAndContact(contct.Id);
		Test.stopTest();

		Assert.isNotNull(opp, 'An opportunity should be returned');
	}

	@IsTest
	private static void testGetByAccountId() {
		Account acc = AccountSelector.getByCVR(CVR);

		Opportunity opp1 = new Opportunity(
			Name = 'Opp1',
			StageName = 'Needs Analysis',
			AccountId = acc.Id,
			Agreement_Type__c = 'Specified',
			Product_s_in_scope__c = 'Home Office',
			CloseDate = Date.today() + 30
		);
		insert opp1;

		Test.startTest();
		Opportunity opp = OpportunitySelector.getByAccountId(acc.Id);
		Test.stopTest();

		Assert.isNotNull(opp, 'An opportunity should be returned');
	}

	@IsTest
	private static void testGetOrderedOpenOrClosedOpportunitiesByAccountsAndCloseDate() {
		Account acc = AccountSelector.getByCVR(CVR);

		List<Opportunity> opportunities = TestDataFactory.createOpportunitiesForAccounts(2, new List<Account>{acc});
		opportunities[0].StageName = 'Closed Lost';
		opportunities[0].Loss_Reason__c = 'Opgivet';
		update opportunities[0];

		Test.startTest();
		List<Opportunity> orderedOpportunities = OpportunitySelector.getOrderedOpenOrClosedOpportunitiesByAccountsAndCloseDate(
			new List<Account>{acc},
			System.today().addDays(-180)
		);
		Test.stopTest();

		Assert.areEqual(2, orderedOpportunities.size(), '2 Opportunities should be returned');
	}
}