force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK( Street_Name__c ), &apos;&apos;, (Street_Name__c + &apos; &apos; + Number__c)) +
IF(ISBLANK( Floor__c ), &apos;&apos;, (&apos;, &apos; + Floor__c)) +
IF(ISBLANK( Door__c ), &apos;&apos;, IF((FIND(&apos;.&apos;, Floor__c)) &gt; 0, (&apos; &apos; + Door__c), (&apos;. &apos; + Door__c))) +
IF(ISBLANK( ZIP_Code__c ), &apos;&apos;, (&apos;, &apos; + ZIP_Code__c)) +
IF(ISBLANK( City__c ), &apos;&apos;, (&apos; &apos; + City__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address_ID__c.field-meta.xml
<CustomField>
    <fullName>Address_ID__c</fullName>
    <label>Address ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address_Wash_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Wash_Status__c</fullName>
    <label>Address Wash Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Not Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/addressWash_Category__c.field-meta.xml
<CustomField>
    <fullName>addressWash_Category__c</fullName>
    <label>Address Wash Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Door__c.field-meta.xml
<CustomField>
    <fullName>Door__c</fullName>
    <label>Door</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Municipality_Code__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Code__c</fullName>
    <label>Municipality Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/POQ_Item_Created__c.field-meta.xml
<CustomField>
    <fullName>POQ_Item_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When POQ Item has been created this is true</description>
    <label>POQ Item Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/POQ_ProductOfferingId__c.field-meta.xml
<CustomField>
    <fullName>POQ_ProductOfferingId__c</fullName>
    <label>POQ ProductOfferingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/POQ_ProductOfferingQualificationItemId__c.field-meta.xml
<CustomField>
    <fullName>POQ_ProductOfferingQualificationItemId__c</fullName>
    <label>POQ ProductOfferingQualificationItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Code__c.field-meta.xml
<CustomField>
    <fullName>Street_Code__c</fullName>
    <label>Street Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VAS_product__c.field-meta.xml
<CustomField>
    <fullName>VAS_product__c</fullName>
    <label>VAS product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_VAS_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/POQ_Status__c.field-meta.xml
<CustomField>
    <fullName>POQ_Status__c</fullName>
    <label>POQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not ready</fullName>
                <default>true</default>
                <label>Not ready</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done Updating LL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POQ_batch_chunks__c/POQ_batch_chunks__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A simple setting to keep the chunk size for POQ first request and full request.</description>
    <label>POQ batch chunks</label>
</CustomObject>

force-app/main/default/objects/POQ_batch_chunks__c/fields/Full_Qualification_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Full_Qualification_Batch_Size__c</fullName>
    <defaultValue>50</defaultValue>
    <description>Define the number of address lines should be included in a full qualification POQ request. Here it can be maximum up to 100, but keep the number lower, so the fail rate will be lower</description>
    <label>Full Qualification Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>This object has been created to gather in it any kinds of errors.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>ErLog-{000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>These field has been created to hold 255 signs of additional information that might be useful in problem solving of this error.</description>
    <inlineHelpText>Additional helpful information like name of class/flow ect.</inlineHelpText>
    <label>Additional Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Error_Body__c.field-meta.xml
<CustomField>
    <fullName>Error_Body__c</fullName>
    <description>This field should contains body of error and information that will allow to locate source of error and fix the issue.</description>
    <inlineHelpText>This is Error body with any additional required information.</inlineHelpText>
    <label>Error Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This values should allow user to distinguish origin of the error. So if the error occurred in Apex or in Flow. It should also allow easier way of finding specific error record.</description>
    <inlineHelpText>This is the origin of error like Apex code execution, flow fail ect.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Not defined</fullName>
                <default>true</default>
                <label>Not defined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QueueablePOQ.cls
/**
 *
 * @author Frederik
 *
 * @author Mujahid (qet9252)
 * @description QueueablePOQ will get the available opportunites and chunk teh address in to default 50 records chunks and send to POQ API, which will then validate the information provided.
 */
public without sharing class QueueablePOQ implements Queueable, Database.AllowsCallouts {
	private List<List<Location_Line__c>> listOfLocationLineListsToCallout;
	private List<Location_Line__c> theLines; // quick fix because VS code was confused
	private List<System_Log__c> errorsList = new List<System_Log__c>();
	private final String ERROR_FIELDS = ' Fields that affected this error: ';
	private final String QUEUEABLE_ERROR = 'QueueablePOQ Error : ';
	private final String ERROR_ADDITIONAL_INFO = 'QueueablePOQ';
	private final String ERROR_ORIGIN = 'Apex';
	// reference here: https://salesforce.stackexchange.com/a/181235/78049
	@TestVisible
	private static Boolean doChainJob = true;

	// Constructor
	public QueueablePOQ(List<String> qualifyingOpportunityIds) {
		List<List<Location_Line__c>> lineChunks = new List<List<Location_Line__c>>();
		List<Location_Line__c> currentChunk = new List<Location_Line__c>();
		List<Location_Line__c> locationLines = new List<Location_Line__c>();
		POQ_batch_chunks__c batchChunks = POQ_batch_chunks__c.getOrgDefaults();

		Integer chunkSize = Test.isRunningTest() ? 1 : batchChunks.Full_Qualification_Batch_Size__c.intValue();

		for (Location_Line__c line : [
			SELECT
				Id,
				Name,
				addressWash_Category__c,
				ZIP_Code__c,
				City__c,
				Door__c,
				Number__c,
				Floor__c,
				Street_Name__c,
				Employee_ID__c,
				Address__c,
				Subscription_product__c,
				OTC_product__c,
				VAS_product__c,
				Opportunity__c,
				Address_ID__c,
				POQ_Item_Created__c,
				Address_Wash_Status__c,
				Street_Code__c,
				Municipality_Code__c,
				POQ_ProductOfferingQualificationItemId__c,
				POQ_ProductOfferingId__c
			FROM Location_Line__c
			WHERE Opportunity__c IN :qualifyingOpportunityIds
			ORDER BY Id
		]) {
			if (currentChunk.size() < chunkSize) {
				currentChunk.add(line);
			} else {
				lineChunks.add(currentChunk);
				currentChunk = new List<Location_Line__c>{ line };
			}
			locationLines.add(line);
		}

		if (!currentChunk.isEmpty()) {
			lineChunks.add(currentChunk);
		}
		this.theLines = locationLines;
		this.listOfLocationLineListsToCallout = lineChunks;
	}

	public void execute(QueueableContext context) {
		Set<String> oppIds = new Set<String>();
		for (Location_Line__c line : this.theLines) {
			oppIds.add(line.Opportunity__c);
		}
		System.debug('oppIds in QueablePOQ = ' + oppIds);

		Integer sentCount = 0;
		Boolean hitLimit = false;
		System.debug('start execute');
		// Process as many as possible in this transaction, based on limits
		for (List<Location_Line__c> lines : listOfLocationLineListsToCallout) {
			// String failMsg = '';

			if (sentCount == 1) {
				hitLimit = true;
				break;
			}

			// Do your callout
			List<List<Location_Line__c>> outerLines = new List<List<Location_Line__c>>();
			outerLines.add(lines);

			// The call to product offering qualification which will make the second poq call. The exceptions will be handle in the main method itself.
			ProductOfferingQualification.main(outerLines, true);

			if ((listOfLocationLineListsToCallout.size() == 1)) {
				List<Opportunity> oppsToUpdate = new List<Opportunity>();
				for (Opportunity opp : [SELECT POQ_Status__c FROM Opportunity WHERE Id IN :oppIds]) {
					opp.POQ_Status__c = 'Done';
					oppsToUpdate.add(opp);
				}
				if (!system.isFuture() && !system.isBatch()) {
					Database.SaveResult[] oppsUpdateResult = Database.update(oppsToUpdate, false);
					for (Database.SaveResult sr : oppsUpdateResult) {
						if (!sr.isSuccess()) {
							for (Database.Error err : sr.getErrors()) {
								String errorMsg =
									this.QUEUEABLE_ERROR +
									err.getStatusCode() +
									': ' +
									err.getMessage() +
									', ' +
									this.ERROR_FIELDS +
									err.getFields();
								this.errorsList.add(createErrorLog(errorMsg));
							}
						}
					}
				}
				if (this.errorsList.size() > 0) {
					insert this.errorsList;
				}
			}
			// Track how many have been processed
			sentCount++;
		}

		if (hitLimit) {
			System.debug('hitLimit !!!');
			// Need to chain this queueable to finish processing. First clean up
			// the list of leads needing a callout, removing all those that have
			// been sent already
			for (Integer index = 0; index < sentCount; index++) {
				listOfLocationLineListsToCallout.remove(0);
			}

			// Now ensure the remainder get processed by simply re-enqueuing this
			// queueable with its adjusted state
			if (doChainJob) {
				System.enqueueJob(this);
			}
		}
	}

	@TestVisible
	private System_Log__c createErrorLog(String errorMsg) {
        System.debug('errorMsg = ' + errorMsg);
		System_Log__c errorLog = new System_Log__c(
			Origin__c = this.ERROR_ORIGIN,
			Error_Body__c = errorMsg,
			Additional_Information__c = this.ERROR_ADDITIONAL_INFO
		);
		return errorLog;
	}

	public class queueablePOQexception extends Exception {
	}
}