force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK( Street_Name__c ), &apos;&apos;, (Street_Name__c + &apos; &apos; + Number__c)) +
IF(ISBLANK( Floor__c ), &apos;&apos;, (&apos;, &apos; + Floor__c)) +
IF(ISBLANK( Door__c ), &apos;&apos;, IF((FIND(&apos;.&apos;, Floor__c)) &gt; 0, (&apos; &apos; + Door__c), (&apos;. &apos; + Door__c))) +
IF(ISBLANK( ZIP_Code__c ), &apos;&apos;, (&apos;, &apos; + ZIP_Code__c)) +
IF(ISBLANK( City__c ), &apos;&apos;, (&apos; &apos; + City__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Address_Wash_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Wash_Status__c</fullName>
    <label>Address Wash Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Not Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/addressWash_Category__c.field-meta.xml
<CustomField>
    <fullName>addressWash_Category__c</fullName>
    <label>Address Wash Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LineInquiry.cls
public without sharing class LineInquiry {

    public class DawaRes {
    	public String kategori;
	}

	public static DawaRes parse(String json) {
		return (DawaRes) System.JSON.deserialize(json, DawaRes.class);
	}
	

    public static Location_Line__c theCall(Location_Line__c line) {
        String fullAddress = EncodingUtil.urlEncode((String) line.get('Address__c'), 'UTF-8');               
        HttpRequest req = new HttpRequest(); 
        req.setEndpoint('https://api.dataforsyningen.dk/datavask/adresser?betegnelse=' + fullAddress); 
        req.setMethod('GET'); 
        Http http = new Http(); 
        HTTPResponse res = http.send(req); 
        DawaRes obj = DawaRes.parse(res.getBody());

        line.addressWash_Category__c = obj.kategori;
        if (obj.kategori == 'A') {
            line.Address_Wash_Status__c = 'Valid';
        } else {
            line.Address_Wash_Status__c = 'Not Valid';   
        }
        
        return line;
    }

    @InvocableMethod(label='Line Inquiry Address Wash' description='CALL DAWA.' callout=true)
    public static void callDawa(List<List<Location_Line__c>> locations) {       
        List<Location_Line__c> als = new List<Location_Line__c>();
        
        for (List<Location_Line__c> location : locations) {
            for (Location_Line__c line : location) {
                Location_Line__c result = theCall(line);
                als.add(result);
            }
        }

        update als;
    }    
}