force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/POQ_Status__c.field-meta.xml
<CustomField>
    <fullName>POQ_Status__c</fullName>
    <label>POQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not ready</fullName>
                <default>true</default>
                <label>Not ready</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done Updating LL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
public class OpportunityService {
    private final OpportunitySelector opportunitySelector;

    @TestVisible
    private OpportunityService(OpportunitySelector opportunitySelector) {
        this.opportunitySelector = opportunitySelector;
    }

    public OpportunityService() {
        this(SingletonFactory.getFactory());
    }

    private OpportunityService(SingletonFactory singletonFactory) {
        this.opportunitySelector = (OpportunitySelector) singletonFactory.getOrRegisterSingleton(OpportunitySelector.class);
    }

    public List<String> getOpportunitesForProductOfferingQualification(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunitiesMap){
        Logger.logInfo(String.format('getOpportunitesForProductOfferingQualification( {0} )', new List<Object>{newOpportunities, oldOpportunitiesMap}));

        List<String> qualifyingOpportunityIds = new List<String>();
        
        // Iterate through the updated Opportunities
        for(Opportunity newOpportunity : newOpportunities){
            Opportunity oldOpportunity = oldOpportunitiesMap.get(newOpportunity.Id);

            // Check if the Product Qualification Status has changed to "Ready"
			if (newOpportunity.POQ_Status__c == 'Ready' && oldOpportunity.POQ_Status__c != 'Ready' ) {
				qualifyingOpportunityIds.add(newOpportunity.Id);
			}
        }

        return qualifyingOpportunityIds;
    }

    public List<Opportunity> getOpportunitesWithProcessedQualification(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunitiesMap){
        Logger.logInfo(String.format('getOpportunitesWithProcessedQualification( {0} )', new List<Object>{newOpportunities, oldOpportunitiesMap}));
        
        List<Opportunity> qualifyingOpportunityIds = new List<Opportunity>();
        
        // Iterate through the updated Opportunities
        for(Opportunity newOpportunity : newOpportunities){
            Opportunity oldOpportunity = oldOpportunitiesMap.get(newOpportunity.Id);

            // Check if the Product Qualification Status has changed to "Ready"
			if (newOpportunity.POQ_Status__c == 'Done' && oldOpportunity.POQ_Status__c != 'Done' ) {
				qualifyingOpportunityIds.add(newOpportunity);
			}
        }

        return qualifyingOpportunityIds;
    }

    public void enqueueOpportunitesForProductOfferingQualification(List<String> opportunityIds){
        Logger.logInfo(String.format('enqueueOpportunitesForProductOfferingQualification( {0} )', new List<Object>{opportunityIds}));
        if(opportunityIds.isEmpty()){
            return;
        }

        List<Location_Line__c> locationLines = opportunitySelector.getLocationLinesByOpportunityIds(opportunityIds);
        
		//We have at least one opportunity and locationline to process. The QueueablePOQ handles the processing.
		if (!locationLines.isEmpty()) {
			QueueablePOQ job = new QueueablePOQ(opportunityIds);
			System.enqueueJob(job);
		}
    }

    public void processLocationLineItemsByOpportunitys(List<Opportunity> opportunitys){
        Logger.logInfo(String.format('processLocationLineItemsByOpportunity( {0} )', new List<Object>{opportunitys}));
        if(opportunitys.isEmpty()){
            return;
        }

        UpdateLocationLines.finalUpdate(opportunitys);
    }
}