force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Address_Wash_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Wash_Status__c</fullName>
    <label>Address Wash Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Not Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <label>Employee ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The QuoteLine that resulted from this LocationLine.</description>
    <inlineHelpText>The QuoteLine that resulted from this LocationLine.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDF_LocationLineUtils.cls
@IsTest
public with sharing class TDF_LocationLineUtils {

	public static Location_Line__c createLocationLine(String productId) {
		return new Location_Line__c(
			ZIP_Code__c = '2650',
			City__c = 'Hvidovre',
			Number__c = '8',
			Street_Name__c = 'Daglykkevej',
			Employee_ID__c = '20',
			Subscription_product__c = productId,
			Address_Wash_Status__c = 'Valid',
			SiteId__c = 'SiteId',
			AddressRefId__c = 'AddressRefId',
			lineConnectionStatus__c = 'lineConnectionStatus'
		);
	}
	
	/**
	 * Create a Location Line for an Opportunity with a subscriptionProduct and give quote line
	 * @param opp - Opportunity
	 * @param subscriptionProduct - Subscription Product
	 * @param quoteLine - Quote Line
	 * @return Location Line
	 */
	public static Location_Line__c createLocationLineForOpportunity(Opportunity opp, String subscriptionProduct, SBQQ__QuoteLine__c quoteLine) {
		return new Location_Line__c(
			Opportunity__c = opp.Id,
			Quote_Line__c = quoteLine?.Id,
			ZIP_Code__c = '2650',
			City__c = 'Hvidovre',
			Number__c = '8',
			Street_Name__c = 'Daglykkevej',
			Employee_ID__c = '20',
			Subscription_product__c = subscriptionProduct,
			Address_Wash_Status__c = 'Valid',
			SiteId__c = 'SiteId',
			AddressRefId__c = 'AddressRefId',
			lineConnectionStatus__c = 'lineConnectionStatus'
		);
	}

}