force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Door__c.field-meta.xml
<CustomField>
    <fullName>Door__c</fullName>
    <label>Door</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressAutocompleteTest.cls
/**
 * 
 * @author keh
 * @since 14032025
 */
@isTest
public class AddressAutocompleteTest {

    /**
     * uploadLines_validInput_resultsInCorrectLines
     */
    @isTest
    public static void uploadLines_validInput_resultsInCorrectLines() {
        
        //ARRANGE
        Account acc = TDF_AccountUtils.creatActiveAccountWithCVRAndOwner();
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test Name', 
            StageName = 'Qualification', 
            CloseDate = Date.today(),
            AccountId = acc.Id
        );
        insert opp;
        
        Location_Line__c line = new Location_Line__c(
            City__c = 'Test City',
            Door__c = 'Test Door',
            Floor__c = 'Test Floor',
            Number__c = 'Test Number',
            Street_Name__c = 'Test Street',
            ZIP_Code__c = 'Test Zip',
            Opportunity__c = opp.Id
        );
        List<Location_Line__c> linesToInsert = new List<Location_Line__c>{ line };
        String jsonData = JSON.serialize(linesToInsert);
        
        //ACT
        Test.startTest();
        AddressAutocomplete.uploadLines(jsonData);
        Test.stopTest();
        
        //ASSERT
        List<Location_Line__c> insertedLines = [
            SELECT Id, City__c, Door__c, Floor__c, Number__c, Street_Name__c, ZIP_Code__c
            FROM Location_Line__c
        ];
        System.assertEquals(1, insertedLines.size(), 'Expected one line to be inserted');
        
        Location_Line__c insertedLine = insertedLines[0];
        System.assertEquals(line.City__c, insertedLine.City__c, 'City should match');
        System.assertEquals(line.Door__c, insertedLine.Door__c, 'Door should match');
        System.assertEquals(line.Floor__c, insertedLine.Floor__c, 'Floor should match');
        System.assertEquals(line.Number__c, insertedLine.Number__c, 'Number should match');
        System.assertEquals(line.Street_Name__c, insertedLine.Street_Name__c, 'Street should match');
        System.assertEquals(line.ZIP_Code__c, insertedLine.ZIP_Code__c, 'Zip should match');
    }
}