force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/POQ_ProductOfferingId__c.field-meta.xml
<CustomField>
    <fullName>POQ_ProductOfferingId__c</fullName>
    <label>POQ ProductOfferingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/POQ_ProductOfferingQualificationItemId__c.field-meta.xml
<CustomField>
    <fullName>POQ_ProductOfferingQualificationItemId__c</fullName>
    <label>POQ ProductOfferingQualificationItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VAS_product__c.field-meta.xml
<CustomField>
    <fullName>VAS_product__c</fullName>
    <label>VAS product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_VAS_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/priceplanCode__c.field-meta.xml
<CustomField>
    <fullName>priceplanCode__c</fullName>
    <label>priceplanCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/ProductOfferingId__c.field-meta.xml
<CustomField>
    <fullName>ProductOfferingId__c</fullName>
    <label>ProductOfferingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/ProductOfferingQualificationItemId__c.field-meta.xml
<CustomField>
    <fullName>ProductOfferingQualificationItemId__c</fullName>
    <label>ProductOfferingQualificationItemId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HomeOfficeController.cls
public without sharing class HomeOfficeController {
	@AuraEnabled
	public static void updateProduct(String locationLine, String productCode) {
		Location_Line__c line = [
			SELECT Id, Subscription_product__c, OTC_product__c, VAS_product__c, POQ_ProductOfferingId__c, POQ_ProductOfferingQualificationItemId__c
			FROM Location_Line__c
			WHERE Id = :locationLine
			LIMIT 1
		];

		POQ_item__c item = [
			SELECT Id, ProductOfferingId__c, ProductOfferingQualificationItemId__c
			FROM POQ_Item__c
			WHERE priceplanCode__c = :productCode AND Location_Line__c = :line.Id
			LIMIT 1
		];

		line.OTC_product__c = null;

		line.POQ_ProductOfferingId__c = item.ProductOfferingId__c;

		line.POQ_ProductOfferingQualificationItemId__c = item.ProductOfferingQualificationItemId__c;

		line.Subscription_product__c = productCode;

		line.VAS_product__c = null;

		System.debug('line = ' + line);

		update line;
	}

	@AuraEnabled
	public static void updateVAS(String locationLine, Boolean staticIP) {
		Location_Line__c line = [SELECT Id, VAS_product__c FROM Location_Line__c WHERE Id = :locationLine LIMIT 1];

		line.VAS_product__c = null;

		if (staticIP == true) {
			line.VAS_product__c = 'FASTIP';
		}

		update line;
	}
}