force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Framework</fullName>
            </value>
            <value>
                <fullName>Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Primary_Quote__c.field-meta.xml
<CustomField>
    <fullName>Original_Primary_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>MK - CPQ-32 - 22092021 - Identifies the Initial Primary Quote before an Activation quote was created and became a Primary Quote.</description>
    <label>Original Primary Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities (Original Primary Quote)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s_in_scope__c.field-meta.xml
<CustomField>
    <fullName>Product_s_in_scope__c</fullName>
    <description>User story ID: 94</description>
    <inlineHelpText>Specify here which products are included in this opportunity</inlineHelpText>
    <label>Product(s) in scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Telia_Product_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Telia Enterprise</businessProcess>
    <description>Used for tracking sales</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/OpportunitySelector.cls
public without sharing class OpportunitySelector {
	public List<Location_Line__c> getLocationLinesByOpportunityIds(List<String> opportunityIds) {
        Logger.logInfo(String.format('getLocationLinesByOpportunityIds( {0} )', new List<Object>{opportunityIds}));

		return [
			SELECT Id
			FROM Location_Line__c
			WHERE Opportunity__c IN :opportunityIds
			ORDER BY Id
		];
	}

	public static Opportunity getById(String oppId) {
		Opportunity opp = [SELECT Name, StageName, Description, IsWon FROM Opportunity WHERE Id = :oppId LIMIT 1];
		return opp;
	}

	public static Opportunity getHomeOfficeOppByOppContactRoleAndContact(String contactId) {
		List<Opportunity> opps = [
			SELECT Id, (SELECT OpportunityId FROM OpportunityContactRoles)
			FROM Opportunity
			WHERE
				Id IN (
					SELECT OpportunityId
					FROM OpportunityContactRole
					WHERE ContactId = :contactId AND Role = 'Sales Contact'
				)
				AND ((StageName IN ('Needs Analysis', 'Closed Won')
				AND Agreement_Type__c = 'Specified')
				OR (StageName = 'Closed Won'
				AND Agreement_Type__c = 'Framework'))
				AND Product_s_in_scope__c INCLUDES ('Home Office')
		];
		return opps.size() > 0 ? opps.get(0) : null;
	}

	public static Opportunity getByAccountId(String accountId) {
		return [
			SELECT Id, AccountId, Name, StageName, Description, IsWon, SBQQ__PrimaryQuote__c, Original_Primary_Quote__c
			FROM Opportunity
			WHERE AccountId = :accountId
			LIMIT 1
		];
	}

	public static List<Opportunity> getOrderedOpenOrClosedOpportunitiesByAccountsAndCloseDate(
		List<Account> accounts,
		Date filterDate
	) {
		return [
			SELECT Id, AccountId, IsClosed, IsWon
			FROM Opportunity
			WHERE AccountId IN :accounts AND (IsClosed = FALSE OR (IsClosed = TRUE AND CloseDate > :filterDate))
			ORDER BY IsClosed, IsWon DESC
		];
	}
}