force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/DIGGING_NEEDED__c.field-meta.xml
<CustomField>
    <fullName>DIGGING_NEEDED__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIGGING_NEEDED</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/plugTechnicianRequired__c.field-meta.xml
<CustomField>
    <fullName>plugTechnicianRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>plugTechnicianRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateLocationLineTest.cls
@IsTest
private class UpdateLocationLineTest {
	private static final String CVR = '23456789';

	private static List<String> productIds = new List<String>{
		'FIBHOF09',
		'FIBHOF08',
		'FIBHOF06',
		'FIBHOF05',
		'FIBHOF03',
		'FIBHOF02',
		'COAHOF03',
		'COAHOF02',
		'DSLHOF01'
	};

	@TestSetup
	static void makeData() {
		Account acct = testDataFactory.createCVRAccountWithBillingAddress(CVR);
		List<Opportunity> opportunities = testDataFactory.createOpportunitiesForAccounts(1, new List<Account>{ acct });

		List<Location_Line__c> locations = new List<Location_Line__c>();
		for (String productId : productIds) {
			Location_Line__c location = testDataFactory.createLocationLine(productId);
			location.Opportunity__c = opportunities.get(0).Id;
			locations.add(location);
		}
		insert locations;

		List<POQ_Item__c> poqItems = testDataFactory.createPOQItems(locations);
	}

	@IsTest
	private static void testFinalUpdate() {
		Account acc = AccountSelector.getByCVR(CVR);
		Opportunity opp = OpportunitySelector.getByAccountId(acc.Id);
		List<String> otcProducts = new List<String>();
		Map<Id, POQ_Item__c> itemsToUpdate = new Map<Id, POQ_Item__c>();
		Test.startTest();

		// Test when plugTechnicianRequired__c = true and DIGGING_NEEDED__c = false
		Map<Id, Location_Line__c> locations = new Map<Id, Location_Line__c>(
			[SELECT Id, Name, Subscription_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]
		);
		List<POQ_Item__c> poqItems = POQItemSelector.getPOQItemsByLocationIds(locations.keySet());
		for (POQ_Item__c item : poqItems) {
			item.plugTechnicianRequired__c = true;
			item.DIGGING_NEEDED__c = false;
			itemsToUpdate.put(item.Id, item);
		}
		update itemsToUpdate.values();
		UpdateLocationLines.finalUpdate(new List<Opportunity>{ opp });
		for (Location_Line__c line : [SELECT Id, OTC_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]) {
			otcProducts.add(line.OTC_product__c);
		}
		Assert.areEqual(9, otcProducts.size());

		// Test when plugTechnicianRequired__c = false and DIGGING_NEEDED__c = true
		itemsToUpdate.clear();
		otcProducts.clear();
		Map<Id, Location_Line__c> locations1 = new Map<Id, Location_Line__c>(
			[SELECT Id, Name, Subscription_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]
		);
		List<POQ_Item__c> poqItems1 = POQItemSelector.getPOQItemsByLocationIds(locations1.keySet());
		for (POQ_Item__c item : poqItems1) {
			item.plugTechnicianRequired__c = false;
			item.DIGGING_NEEDED__c = true;
			itemsToUpdate.put(item.Id, item);
		}
		update itemsToUpdate.values();
		UpdateLocationLines.finalUpdate(new List<Opportunity>{ opp });
		for (Location_Line__c line : [SELECT Id, OTC_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]) {
			otcProducts.add(line.OTC_product__c);
		}
		Assert.areEqual(9, otcProducts.size());

		// Test when plugTechnicianRequired__c = true and DIGGING_NEEDED__c = true
		itemsToUpdate.clear();
		otcProducts.clear();
		Map<Id, Location_Line__c> locations2 = new Map<Id, Location_Line__c>(
			[SELECT Id, Name, Subscription_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]
		);
		List<POQ_Item__c> poqItems2 = POQItemSelector.getPOQItemsByLocationIds(locations2.keySet());
		for (POQ_Item__c item : poqItems2) {
			item.plugTechnicianRequired__c = true;
			item.DIGGING_NEEDED__c = true;
			itemsToUpdate.put(item.Id, item);
		}
		update itemsToUpdate.values();
		UpdateLocationLines.finalUpdate(new List<Opportunity>{ opp });
		for (Location_Line__c line : [SELECT Id, OTC_product__c FROM Location_Line__c WHERE Opportunity__c = :opp.Id]) {
			otcProducts.add(line.OTC_product__c);
		}
		Assert.areEqual(9, otcProducts.size());

		Test.stopTest();
	}
}