force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/POQItemSelectorTest.cls
@IsTest
private class POQItemSelectorTest {
	private static final String CVR = '23456789';

	@TestSetup
	static void makeData() {
		Account acct = testDataFactory.createCVRAccountWithBillingAddress(CVR);
		List<Opportunity> opportunities = testDataFactory.createOpportunitiesForAccounts(1, new List<Account>{ acct });
		Location_Line__c location = testDataFactory.createLocationLine('FIBHOF02');
		location.Opportunity__c = opportunities.get(0).Id;
		insert location;
		List<POQ_Item__c> poqItems = testDataFactory.createPOQItems(new List<Location_Line__c>{ location });
	}

	@IsTest
	private static void testGetPOQItemsByLocationIds() {
		Location_Line__c line = [SELECT Id FROM Location_Line__c WHERE Subscription_product__c = 'FIBHOF02' LIMIT 1];

		Test.startTest();

		List<POQ_Item__c> items = POQItemSelector.getPOQItemsByLocationIds(new Set<Id>{ line.Id });

		Test.stopTest();

		Assert.isTrue(items.size() > 0);
	}
}