force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeletePOQItems.cls
public class DeletePOQItems {
    @InvocableMethod(label='Delete POQ Items from Location Lines' description='Delete POQ Items from Location Lines')
    public static void deleteItems(List<List<SObject>> Location_Lines_List) {
        List<Id> locationLineIds = new List<Id>();
        
        // Collect Location_Line Ids from the input
        for (List<SObject> locationLines : Location_Lines_List) {
            for (SObject locationLine : locationLines) {
                Id locationLineId = (Id)locationLine.get('Id');
                locationLineIds.add(locationLineId);
            }
        }

        // Retrieve related POQ_Item__c records
        List<POQ_Item__c> POQ_Items = [SELECT Id FROM POQ_Item__c WHERE Location_Line__c IN :locationLineIds];

        // Delete POQ_Items
        try {
            delete POQ_Items;
        } catch (DmlException e) {
            // Handle any potential exceptions
            System.debug('Error deleting POQ_Items: ' + e);
        }
    }
}