force-app/main/default/objects/Location_Line__c/Location_Line__c.object-meta.xml
<CustomObject>
    <description>Used to gather all data coming from the Address Portal / API. Including all relevant data for the automatically quote creation.</description>
    <label>Location Line</label>
    <nameField>
        <displayFormat>LL-{0000000}</displayFormat>
        <label>Location Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Line__c/fields/Active_Blocking_Line_Present__c.field-meta.xml
<CustomField>
    <fullName>Active_Blocking_Line_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value comes from POQ Item record</description>
    <label>Active Blocking Line Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Location Lines</relationshipLabel>
    <relationshipName>Location_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/OTC_product__c.field-meta.xml
<CustomField>
    <fullName>OTC_product__c</fullName>
    <label>OTC product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subscription_product__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Home_Office_OTC_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Plug_Technician_Required__c.field-meta.xml
<CustomField>
    <fullName>Plug_Technician_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plug Technician Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/plugPresentPositiveValidation__c.field-meta.xml
<CustomField>
    <fullName>plugPresentPositiveValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>plugPresentPositiveValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/Subscription_product__c.field-meta.xml
<CustomField>
    <fullName>Subscription_product__c</fullName>
    <label>Subscription product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Office_Subscription_products</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VendorProductCatalogId__c.field-meta.xml
<CustomField>
    <fullName>VendorProductCatalogId__c</fullName>
    <label>VendorProductCatalogId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Line__c/fields/VendorProductCode__c.field-meta.xml
<CustomField>
    <fullName>VendorProductCode__c</fullName>
    <label>VendorProductCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/POQ_Item__c.object-meta.xml
<CustomObject>
    <label>POQ Item</label>
    <nameField>
        <label>Product Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POQ Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/POQ_Item__c/fields/Active_Blocking_Line_Present__c.field-meta.xml
<CustomField>
    <fullName>Active_Blocking_Line_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value comes from POQ API</description>
    <label>Active Blocking Line Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/AddressRefId__c.field-meta.xml
<CustomField>
    <fullName>AddressRefId__c</fullName>
    <label>AddressRefId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/DIGGING_NEEDED__c.field-meta.xml
<CustomField>
    <fullName>DIGGING_NEEDED__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DIGGING_NEEDED</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/lineConnectionStatus__c.field-meta.xml
<CustomField>
    <fullName>lineConnectionStatus__c</fullName>
    <label>lineConnectionStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/lineProvider__c.field-meta.xml
<CustomField>
    <fullName>lineProvider__c</fullName>
    <label>lineProvider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/Location_Line__c.field-meta.xml
<CustomField>
    <fullName>Location_Line__c</fullName>
    <label>Location Line</label>
    <referenceTo>Location_Line__c</referenceTo>
    <relationshipLabel>POQ Items</relationshipLabel>
    <relationshipName>POQ_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/plugPresentPositiveValidation__c.field-meta.xml
<CustomField>
    <fullName>plugPresentPositiveValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value received from POQ to be transferred to the Order API</description>
    <label>plugPresentPositiveValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/plugTechnicianRequired__c.field-meta.xml
<CustomField>
    <fullName>plugTechnicianRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>plugTechnicianRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/priceplanCode__c.field-meta.xml
<CustomField>
    <fullName>priceplanCode__c</fullName>
    <label>priceplanCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/SiteId__c.field-meta.xml
<CustomField>
    <fullName>SiteId__c</fullName>
    <description>Added September 2023 (Fibia)</description>
    <label>SiteId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POQ_Item__c/fields/VendorProductCatalogId__c.field-meta.xml
<CustomField>
    <fullName>VendorProductCatalogId__c</fullName>
    <description>Used for the catalogId from NetworkProviderProductCatalogIdNote in POQ response</description>
    <label>VendorProductCatalogId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateLocationLines.cls
/**
 *
 * @author Frederik
 *
 * @author by Mujahid
 * @since 22/06/2022
 * @description UpdateLocationLines find relevant POQ Item record and update the OTC products and few extra flags that are needed for order api in the location line record
 */
public without sharing class UpdateLocationLines {
    private static final String DSL_INSTALLATION = 'CHXT01';
    private static final String COAX_INSTALLATION = 'CHXT08';
    private static final String FIBER_INSTALLATION_A_DIGGING = 'CHXT02';
    private static final String FIBER_INSTALLATION_A = 'CHXT03';
    private static final String FIBER_INSTALLATION_B_DIGGING = 'CHXT04';
    private static final String FIBER_INSTALLATION_B = 'CHXT05';
    private static final String FIBER_INSTALLATION_C_DIGGING = 'CHXT06';
    private static final String FIBER_INSTALLATION_C = 'CHXT07';
    private static final String FIBER_INSTALLATION_D_DIGGING = 'CHXT11';
    private static final String FIBER_INSTALLATION_D = 'CHXT12';
    
    private static Map<String, String> productMapWithDigging = new Map<String, String>{
        'FIBHOF03' => FIBER_INSTALLATION_A_DIGGING,
        'FIBHOF02' => FIBER_INSTALLATION_A_DIGGING,
        'FIBHOF06' => FIBER_INSTALLATION_B_DIGGING,
        'FIBHOF05' => FIBER_INSTALLATION_B_DIGGING,
        'FIBHOF09' => FIBER_INSTALLATION_C_DIGGING,
        'FIBHOF08' => FIBER_INSTALLATION_C_DIGGING,
        'FIBHOF10' => FIBER_INSTALLATION_A_DIGGING,
        'FIBHOF11' => FIBER_INSTALLATION_B_DIGGING,
        'FIBHOF12' => FIBER_INSTALLATION_C_DIGGING,
        'FIBHOF13' => FIBER_INSTALLATION_D_DIGGING,
        'FIBHOF14' => FIBER_INSTALLATION_D_DIGGING,
        'FIBHOF15' => FIBER_INSTALLATION_D_DIGGING
    };

    private static Map<String, String> productMapWithoutDigging = new Map<String, String>{
        'FIBHOF03' => FIBER_INSTALLATION_A,
        'FIBHOF02' => FIBER_INSTALLATION_A,
        'FIBHOF06' => FIBER_INSTALLATION_B,
        'FIBHOF05' => FIBER_INSTALLATION_B,
        'FIBHOF09' => FIBER_INSTALLATION_C,
        'FIBHOF08' => FIBER_INSTALLATION_C,
        'COAHOF03' => COAX_INSTALLATION,
        'COAHOF02' => COAX_INSTALLATION,
        'DSLHOF01' => DSL_INSTALLATION,
        'FIBHOF10' => FIBER_INSTALLATION_A,
        'FIBHOF11' => FIBER_INSTALLATION_B,
        'FIBHOF12' => FIBER_INSTALLATION_C,
        'FIBHOF13' => FIBER_INSTALLATION_D,
        'FIBHOF14' => FIBER_INSTALLATION_D,
        'FIBHOF15' => FIBER_INSTALLATION_D
    };

    @InvocableMethod(label='Update Location Lines from POQ Items' description='Update Location Lines from POQ Items' callout=false)
    public static void finalUpdate(List<Opportunity> opps) {
        Map<String, Location_Line__c> linesById = getLocationLinesByOpp(opps);

        List<Location_Line__c> linesToBeUpdated = new List<Location_Line__c>();

        for (POQ_item__c item : [
            SELECT
                Id,
                DIGGING_NEEDED__c,
                Location_Line__c,
                priceplanCode__c,
                plugPresentPositiveValidation__c,
                plugTechnicianRequired__c,
                Active_Blocking_Line_Present__c,
                VendorProductCode__c,
			    VendorProductCatalogId__c,
                AddressRefId__c,
                lineConnectionStatus__c,
                lineProvider__c,
                SiteId__c
            FROM POQ_Item__c
            WHERE Location_Line__c IN :linesById.keySet()
        ]) {
            Location_Line__c line = linesById.get(item.Location_Line__c);
            if (line != null && line.Subscription_product__c == item.priceplanCode__c) {
                line.plugPresentPositiveValidation__c = item.plugPresentPositiveValidation__c;
                line.Plug_Technician_Required__c = item.plugTechnicianRequired__c;
                line.Active_Blocking_Line_Present__c = item.Active_Blocking_Line_Present__c;
                line.OTC_product__c = getOTCProduct(item, line);
                line.VendorProductCode__c = item.VendorProductCode__c;
                line.VendorProductCatalogId__c = item.VendorProductCatalogId__c;
                line.AddressRefId__c = item.AddressRefId__c;
                line.lineConnectionStatus__c = item.lineConnectionStatus__c;
                line.lineProvider__c = item.lineProvider__c;
                line.SiteId__c = item.SiteId__c;
                linesToBeUpdated.add(line);
            }
        }

        update linesToBeUpdated;
    }

    @TestVisible
    private static Map<String, Location_Line__c> getLocationLinesByOpp(List<Opportunity> opps) {
        Map<String, Location_Line__c> linesById = new Map<String, Location_Line__c>();
        for (Location_Line__c line : [
            SELECT Id, OTC_product__c, Subscription_product__c, plugPresentPositiveValidation__c, Plug_Technician_Required__c, Active_Blocking_Line_Present__c, VendorProductCode__c, VendorProductCatalogId__c, AddressRefId__c, lineConnectionStatus__c, lineProvider__c, siteId__c
            FROM Location_Line__c
            WHERE Opportunity__c = :opps.get(0).Id
        ]) {
            line.OTC_product__c = null;
            line.plugPresentPositiveValidation__c = false;
            line.Plug_Technician_Required__c = false;
            line.Active_Blocking_Line_Present__c = false;
            line.VendorProductCode__c = null;
            line.VendorProductCatalogId__c = null;
            line.AddressRefId__c = null;
            line.lineConnectionStatus__c = null;
            line.lineProvider__c = null;
            line.SiteId__c = null;
            linesById.put(line.Id, line);
        }
        update linesById.values();
        return linesById;
    }

    @TestVisible
    private static String getOTCProduct(POQ_Item__c item, Location_Line__c line) {
        if (line.Subscription_product__c == item.priceplanCode__c) {
            // OTC Products should be assigned depending on the DIGGING_NEEDED
            String productCode = line.Subscription_product__c;

            if (item.plugTechnicianRequired__c == true) {
                if (item.DIGGING_NEEDED__c == false) {
                    return productMapWithoutDigging.get(productCode);
                } else {
                    return productMapWithDigging.get(productCode);
                }
            } else {
                // plugTechnicianRequired__c false
                if (item.DIGGING_NEEDED__c == true) {
                    return productMapWithDigging.get(productCode);
                }
            }
        }
        return null;
    }
}