force-app/main/default/objects/Quote_Line_Detail__c/Quote_Line_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Detail</label>
    <nameField>
        <displayFormat>QLD-{000000}</displayFormat>
        <label>Quote Line Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Detail__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Line Details</relationshipLabel>
    <relationshipName>Quote_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteLineDetailsTriggerHandler.cls
public class QuoteLineDetailsTriggerHandler extends TriggerHandler {
    private QuoteLineDetailsService quoteLineDetailsService;

    /**
     * Collection of newly inserted records from the trigger context
     */
    private List<Quote_Line_Detail__c> oldList;
    private List<Quote_Line_Detail__c> newList;

    public QuoteLineDetailsTriggerHandler() {
        this(SingletonFactory.getFactory());
    }

    public QuoteLineDetailsTriggerHandler(SingletonFactory singletonFactory) {
        this.oldList = (List<Quote_Line_Detail__c>) Trigger.old;
        this.newList = (List<Quote_Line_Detail__c>) Trigger.new;
        this.quoteLineDetailsService = (QuoteLineDetailsService) singletonFactory.getOrRegisterSingleton(
            QuoteLineDetailsService.class
        );
    }

    protected override void beforeInsert() {
        Set<Id> quoteLineIds = new Set<Id>(
            SObjectCollectionUtil.of(newList).pluckIds(Quote_Line_Detail__c.Quote_Line__c)
        );

        quoteLineDetailsService.saveDataLimitFromOriginalProduct(newList);
    }

    protected override void afterInsert() {
        Set<Id> quoteLineIds = new Set<Id>(
            SObjectCollectionUtil.of(newList).pluckIds(Quote_Line_Detail__c.Quote_Line__c)
        );

        quoteLineDetailsService.updateQuoteLineQuantity(quoteLineIds);
    }

    protected override void afterDelete() {
        Set<Id> quoteLineIds = new Set<Id>(
            SObjectCollectionUtil.of(oldList).pluckIds(Quote_Line_Detail__c.Quote_Line__c)
        );

        quoteLineDetailsService.updateQuoteLineQuantity(quoteLineIds);
    }

    protected override void afterUpdate() {
        Set<Id> quoteLineIds = new Set<Id>();
        quoteLineIds.addAll(SObjectCollectionUtil.of(newList).pluckIds(Quote_Line_Detail__c.Quote_Line__c));
        quoteLineIds.addAll(SObjectCollectionUtil.of(oldList).pluckIds(Quote_Line_Detail__c.Quote_Line__c));

        quoteLineDetailsService.updateQuoteLineQuantity(quoteLineIds);
    }
}