force-app/main/default/objects/Account_Phone_Number_Assignment__c/Account_Phone_Number_Assignment__c.object-meta.xml
<CustomObject>
    <description>Represents individual phone numbers within a series (DKT-45211).</description>
    <label>Account Phone Number Assignment</label>
    <nameField>
        <displayFormat>APNA-{000000000}</displayFormat>
        <label>Account Phone Number Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Number Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Activation_line__c.field-meta.xml
<CustomField>
    <fullName>Activation_line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for the Activation Line Phone Number assignment</description>
    <label>Activation line</label>
    <referenceTo>Activation_line__c</referenceTo>
    <relationshipLabel>Account Phone Number Assignments</relationshipLabel>
    <relationshipName>Account_Phone_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Phone_Number_Assignment__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activation__c/Activation__c.object-meta.xml
<CustomObject>
    <label>Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations</relationshipLabel>
    <relationshipName>Activations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <formula>IF(
	RecordType.DeveloperName  &lt;&gt; &apos;Voice_activation&apos;, 
	&apos;&apos;, 
	IF( 
		AND(
			Count_Reservation_Status_INPROGRESS__c = 0, 
			Count_Reservation_Status_ERROR__c = 0, 
			Count_Reservation_Status_SUCCESS__c = 0
		), 
		&apos;&apos;,
		IF( 
			AND(
				Count_Reservation_Status_INPROGRESS__c = 0, 
				Count_Reservation_Status_ERROR__c = 0,
				Count_Reservation_Status_SUCCESS__c &gt; 0,
				Count_Empty_Mobile_Number__c = 0
			), 
			&apos;SUCCESS&apos;,
			IF(
				AND(
					Count_Reservation_Status_SUCCESS__c &gt; 0,
					Count_Empty_Mobile_Number__c &gt; 0
				),
				&apos;&apos;,
				IF( 
					Count_Reservation_Status_INPROGRESS__c &gt; 0, 
					&apos;INPROGRESS&apos;, 
					&apos;ERROR&apos;
				)
			)
		)
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Number Reservation Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/Activation_line__c.object-meta.xml
<CustomObject>
    <description>For activating single line items, e.g. one SIM or one fiber installation</description>
    <label>Activation line</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>Activation Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activations lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activation_line__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <description>Relation to Action object</description>
    <label>Activation</label>
    <referenceTo>Activation__c</referenceTo>
    <relationshipLabel>Activation lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used for linking the activation line to an activation case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activations lines</relationshipLabel>
    <relationshipName>Activations_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Mobile_no__c.field-meta.xml
<CustomField>
    <fullName>Mobile_no__c</fullName>
    <description>Mobile number that can have max 8 digits</description>
    <inlineHelpText>Mobile number that can have max 8 digits</inlineHelpText>
    <label>Mobile no.</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Not_to_Activation__c.field-meta.xml
<CustomField>
    <fullName>Not_to_Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</description>
    <inlineHelpText>Use the checkbox to exclude the activation line to be inside the Activation order created by the &quot;Send To Activation&quot; button</inlineHelpText>
    <label>Don&apos;t send to Activation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activation_line__c/fields/Phone_Number_Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Reservation_Status__c</fullName>
    <label>Phone Number Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PhoneNumberReservationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/NumberActivationLinesExecutorInput.cls
/**
 * The NumberActivationLinesExecutorInput class is an invocable action that creates a mapping between activation lines and phone number assignments.
 * It is used in a flow to prepare the input for the NumberActivationLinesExecutorHandler.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         27/07/2025      Initial version
 *
 * 
 * @author Kenneth Houkjær
 * @date 27/07/2025
 */
public with sharing class NumberActivationLinesExecutorInput {
    private static String PHONE_NUMBER_RESERVATION_STATUS_INPROGRESS = 'INPROGRESS';

    /**
     * @description This method is called from a flow to create a mapping between activation lines and phone number assignments.
     * @param inputVariables A list of input variables from the flow.
     * @return A list of output variables containing the mapping.
     */
    @InvocableMethod(category='Number' label='Create ActivationLineExecutor Input' description='Creates a List<IdToString> collection mapping activationLines and assignments.')
    public static List<OutputVariables> createActivationLineToAssignmentMappings(List<InputVariables> inputVariables) {        
        OutputVariables output = new OutputVariables();
        output.activationLineIdToAssignementId = new List<IdToString>();
        
        try {
            // keep SOQL here instead of using selector class, advised by Kenneth
            Activation__c activation = [
                SELECT Id, Case__r.Id, Case__r.AccountId 
                FROM Activation__c 
                WHERE Id = :inputVariables.get(0).activation.Id
            ];

            Account acc = AccountSelector.getAccountByCaseId(activation.case__r.id);

            // we only want Account_Phone_Number_Assignment__c records where the Lookup field to Activation Line is null
            List<Account_Phone_Number_Assignment__c> listOfPhoneNumberAssignments = AccountPhoneNumberAssignmentSelector.getAssignmentsUnlinkedToActivationLine(acc);

            //TODO: khp we should filter the activationlines to those who need phone numbers
            // List<Activation_line__c> listOfActivationLines = ActivationLineSelector.getActivationLinesByCaseId(activation.Case__c);

            // we only want Activation_line__c records where Mobile_no__c is blank
            // keep SOQL here instead of using selector class, advised by Kenneth
            List<Activation_line__c> listOfActivationLines = [
                SELECT Id
                FROM Activation_line__c
                WHERE Activation__r.Case__c = :activation.Case__c AND Not_to_Activation__c = FALSE AND Mobile_no__c = ''
            ];

            Logger.logInfo('listOfActivationLines: ' + listOfActivationLines);
            Logger.logInfo('listOfActivationLines.size(): ' + listOfActivationLines.size());
            Logger.logInfo('listOfPhoneNumberAssignments: ' + listOfPhoneNumberAssignments);
            Logger.logInfo('listOfPhoneNumberAssignments.size(): ' + listOfPhoneNumberAssignments.size());

            for (integer i = 0; i < listOfActivationLines.size(); i++) {                
                Activation_line__c activationLine = listOfActivationLines.get(i);
                activationLine.Phone_Number_Reservation_Status__c = PHONE_NUMBER_RESERVATION_STATUS_INPROGRESS;
            }
            update listOfActivationLines;
            
            for (integer i = 0; i < listOfActivationLines.size(); i++) {                
                //were assigning new numbers to activationlines, so we do not care about the index as long as we have enough.            
                Activation_line__c activationLine = listOfActivationLines.get(i);
                Account_Phone_Number_Assignment__c assignment = listOfPhoneNumberAssignments.get(i);

                IdToString idToString = new IdToString();
                idToString.key = activationLine.Id;
                idToString.value = assignment.Id;
                output.activationLineIdToAssignementId.add(idToString);
            }
            Logger.emit();
        } catch(HTTPException ex) {
            Logger.logError(ex);
            Logger.emit();
            throw ex;
        }
        
        return new List<OutputVariables>{output};
  }

    public class InputVariables {
    @InvocableVariable
    public Activation__c activation;
  }

  public class OutputVariables {
        @InvocableVariable
        public List<IdToString> activationLineIdToAssignementId;
  }
}