force-app/main/default/objects/Environment_Credential_Mapping__mdt/Environment_Credential_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to dynamically get the right Named and External Credential based on Salesforce environment.</description>
    <label>Environment Credential Mapping</label>
    <pluralLabel>Environment Credential Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Environment_Credential_Mapping__mdt/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <inlineHelpText>Name of the sandbox (or prod) for which to use the specified Named Credential. Make a default/fall back record by setting this to &quot;default&quot;</inlineHelpText>
    <label>Environment Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Credential_Mapping__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <inlineHelpText>The API name of the Named Credential to be used for the specified environment.</inlineHelpText>
    <label>Named Credential</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NamedCredentialServiceTest.cls
@IsTest
public with sharing class NamedCredentialServiceTest {
    @IsTest
    private static void testFindMetadataByEnvironmentSuccess() {
        String namedCredentialPrefix = 'MyTestCredential';
        String environmentName = NamedCredentialService.getEnvironmentName();

        List<Environment_Credential_Mapping__mdt> testMappings = new List<Environment_Credential_Mapping__mdt>();
        Environment_Credential_Mapping__mdt testMapping = new Environment_Credential_Mapping__mdt();
        testMapping.Environment_Name__c = environmentName;
        testMapping.Named_Credential__c = namedCredentialPrefix + environmentName;
        testMappings.add(testMapping);
        
        MetadataSelector.setMock(new MetadataSelectorMock(testMappings));
        
        Test.startTest();
        String namedCredential = NamedCredentialService.getNamedCredential(namedCredentialPrefix);
        Test.stopTest();

        Assert.areEqual(testMapping.Named_Credential__c, namedCredential, 'Response should match the Named_Credential__c field from Custom Metadata');
    }

    @IsTest
    private static void testFindMetadataByDefaultSuccess() {
        String namedCredentialPrefix = 'MyTestCredential';
        String environmentName = NamedCredentialService.DEFAULT_ENVIRONMENT;

        List<Environment_Credential_Mapping__mdt> testMappings = new List<Environment_Credential_Mapping__mdt>();
        Environment_Credential_Mapping__mdt testMapping = new Environment_Credential_Mapping__mdt();
        testMapping.Environment_Name__c = environmentName;
        testMapping.Named_Credential__c = namedCredentialPrefix + environmentName;
        testMappings.add(testMapping);
        
        MetadataSelector.setMock(new MetadataSelectorMock(testMappings));
        
        Test.startTest();
        String namedCredential = NamedCredentialService.getNamedCredential(namedCredentialPrefix);
        Test.stopTest();

        Assert.areEqual(testMapping.Named_Credential__c, namedCredential, 'Response should match the Named_Credential__c field from Custom Metadata');
    }

    @IsTest
    private static void testThrowExceptionWhenNoMetadataMatching() {
        String namedCredentialPrefix = 'MyTestCredential';
        String environmentName = NamedCredentialService.getEnvironmentName();
        String badNamedCredentialPrefix = 'ThisIsNotMatching';

        List<Environment_Credential_Mapping__mdt> testMappings = new List<Environment_Credential_Mapping__mdt>();
        Environment_Credential_Mapping__mdt testMapping = new Environment_Credential_Mapping__mdt();
        testMapping.Environment_Name__c = environmentName;
        testMapping.Named_Credential__c = namedCredentialPrefix + environmentName;
        testMappings.add(testMapping);
        
        MetadataSelector.setMock(new MetadataSelectorMock(testMappings));

        NamedCredentialService.NamedCredentialServiceException testException;
        Test.startTest();
        try {
            String namedCredential = NamedCredentialService.getNamedCredential(badNamedCredentialPrefix);
        } catch(NamedCredentialService.NamedCredentialServiceException e) {
            testException = e;
        }
        Test.stopTest();

        Assert.isNotNull(testException, 'An exception should be thrown');
        Assert.areEqual(
            String.format(NamedCredentialService.NO_NAMED_CREDENTIAL_FOUND, new List<String>{badNamedCredentialPrefix, environmentName}),
            testException.getMessage(),
            'Exception message should match'
        );
    }
}